plone/volto

package.json

This will test correctly, but fail when actually using `yarn dev`

WIP Pin latest LTS

---

CHANGELOG.md
src/components/index.js
src/components/theme/View/ListView.jsx
src/components/theme/View/ListingView.jsx
src/components/theme/View/ListingView.test.jsx
src/components/theme/View/View.jsx
src/components/theme/View/__snapshots__/ListingView.test.jsx.snap

Add listing_views and provide test with @obct537

Listing view

---

.travis.yml
LICENSE.md
package.json

As discussed with @polyester. React uses MIT.

Switch to MIT license.

---

package.json
test-setup.js

enzyme configured

---

CHANGELOG.md
package.json
src/components/index.js
src/components/theme/Comments/CommentEditModal.jsx
src/components/theme/Comments/CommentEditModal.test.jsx
src/components/theme/Comments/Comments.jsx
src/components/theme/Comments/Comments.test.jsx
src/components/theme/Comments/__snapshots__/CommentEditModal.test.jsx.snap
src/components/theme/Comments/__snapshots__/Comments.test.jsx.snap
src/components/theme/SocialSharing/SocialSharing.jsx
src/components/theme/SocialSharing/SocialSharing.test.jsx
src/components/theme/SocialSharing/__snapshots__/SocialSharing.test.jsx.snap
src/components/theme/Tags/Tags.jsx
src/components/theme/Tags/Tags.test.jsx
src/components/theme/Tags/__snapshots__/Tags.test.jsx.snap
src/components/theme/View/View.jsx
src/components/theme/View/__snapshots__/View.test.jsx.snap
yarn.lock

Added social sharing.

---

api/docker/requirements.txt
bin/plone-react.js
package.json
yarn.lock

Plone-react as executable script in `bin/`.

Added plone-react as executable script

---

src/components/manage/Form/Form.jsx

Is this the right approach? How would I go about testing it?

Initialize form defaults from schema

---

CHANGELOG.md
src/components/manage/Display/Display.jsx
src/components/theme/View/View.jsx
src/helpers/Content/Content.js
src/helpers/index.js
yarn.lock

There is still a problem on storing the updateContent. The nestFunction is not deflattening the payload to update the content layout attribute.

Layout guillotina

---

.travis.yml
CHANGELOG.md
package.json
src/components/manage/Controlpanels/__snapshots__/UsersControlpanel.test.jsx.snap
src/components/manage/Delete/__snapshots__/Delete.test.jsx.snap
src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
src/components/manage/Form/__snapshots__/Form.test.jsx.snap
src/components/manage/Preferences/__snapshots__/ChangePassword.test.jsx.snap
src/components/manage/Preferences/__snapshots__/PersonalInformation.test.jsx.snap
src/components/manage/Preferences/__snapshots__/PersonalPreferences.test.jsx.snap
src/components/manage/Sharing/__snapshots__/Sharing.test.jsx.snap
src/components/manage/Toolbar/__snapshots__/Toolbar.test.jsx.snap
src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap
src/components/theme/Comments/__snapshots__/Comments.test.jsx.snap
src/components/theme/Footer/__snapshots__/Footer.test.jsx.snap
src/components/theme/Login/__snapshots__/Login.test.jsx.snap
src/components/theme/PasswordReset/__snapshots__/PasswordReset.test.jsx.snap
src/components/theme/PasswordReset/__snapshots__/RequestPasswordReset.test.jsx.snap
src/components/theme/Register/__snapshots__/Register.test.jsx.snap
src/components/theme/SearchWidget/__snapshots__/SearchWidget.test.jsx.snap
src/components/theme/SocialSharing/__snapshots__/SocialSharing.test.jsx.snap
src/components/theme/Tags/__snapshots__/Tags.test.jsx.snap

Fix failing tests, remove not used Coveralls setup. I tried to make it work, but it keeps refusing to work. Something to look after in next sprint.

Fix travis unit tests false green

---

CHANGELOG.md
package.json
src/components/manage/Tiles/Image/View.jsx
src/components/manage/Tiles/Image/__snapshots__/View.test.jsx.snap
yarn.lock

Image-zoom

---

CHANGELOG.md
README.md

This PR improves the README by:
- Fixing typos
- Add better link target descriptions which, will also work with screen readers 
- Use valid markdown with code tags for code blocks
- Improve readability
There is more what needs to be done, this is the first PR in this line of improvements!

[docs] Improve README

---

.travis.yml
CHANGELOG.md
package.json
src/components/manage/Contents/Contents.jsx
src/components/manage/Form/ModalForm.jsx
src/components/manage/History/History.jsx
src/components/manage/Tiles/HTML/Edit.jsx
src/components/manage/Tiles/HeroImageLeft/Edit.jsx
src/components/manage/Tiles/Image/Edit.jsx
src/components/manage/Tiles/Maps/Edit.jsx
src/components/manage/Tiles/Video/Edit.jsx
src/components/manage/Widgets/ReferenceWidget.jsx
src/components/mosaic/Row/Row.jsx
src/components/theme/Footer/Footer.md
src/components/theme/Header/Header.md
src/components/theme/Login/Login.md
src/components/theme/Logo/Logo.md
src/components/theme/Search/Search.md
src/components/theme/SearchWidget/SearchWidget.md
src/components/theme/Title/Title.md
src/config/RichTextEditor/ToHTML.jsx
src/helpers/Api/Api.js
src/i18n.js
src/reducers/emailNotification/emailNotification.js
src/reducers/messages/messages.js
yarn.lock

- Add 'prettier:check' command to check if there are any missing prettier fixes
- Run 'prettier:check' on Travis and fail the build if there are missing prettier fixes
- Add 'prettier:fix' command to fix all missing prettier fixes at once
- Run 'prettier:fix' once and commit all fixes

Prettier pre commit hook

---

CHANGELOG.md
docs/source/03-semantic-ui/01-about-semantic.md
docs/source/05-customizing/03-customizing-components.md

Volto tiny updates

---

CHANGELOG.md
src/components/manage/Widgets/SelectWidget.jsx

fix warnings in console when the edit view has selectwidgets rendering booleans.

fix warnings in console

---

CHANGELOG.md
api/base.cfg

Add development mode for kitkoncept.voltodemo

---

CHANGELOG.md
src/config/RichTextEditor/ToHTML.jsx

Show images in Rich Text editor

---

locales/it/LC_MESSAGES/volto.po

Completed italian translations with new entries.

Updated italian translations

---

CHANGELOG.md
src/actions/search/search.js
src/actions/search/search.test.js
src/components/manage/Toolbar/Toolbar.jsx
src/components/manage/Toolbar/__snapshots__/Toolbar.test.jsx.snap
src/components/theme/Search/Search.jsx

- Fix link to contextual contents in toolbar

Several quick fixes

---

.travis.yml
CHANGELOG.md
package.json

Fixes https://github.com/plone/volto/issues/938

Add support for Node 12.

---

CHANGELOG.md
src/start-server.js

See https://github.com/jaredpalmer/razzle/issues/1036

Report port number on frontend startup

---

README.md

Fix installation step in README

---

CHANGELOG.md
src/start-client.jsx
src/theme.js

This allows for easier customization of the styles and themes that we import.

Move styles import to a separate file

---

CHANGELOG.md
src/actions/index.js

Useful export imho to clean up block subrequests.

Export the resetContent action

---

CHANGELOG.md
src/components/manage/Blocks/Table/Edit.jsx

 fix bug that lead to crashing the view when deleting last row of a table 

---

CHANGELOG.md
src/components/manage/Blocks/Text/View.jsx

empty text blocks are shown as `<br />` in the view.

Empty text blocks

---

CHANGELOG.md
src/components/manage/Edit/Edit.jsx

A simple fix for #1030, hopefully it will be enough

Disable save button in Edit form, based on network activity

---

CHANGELOG.md
src/components/manage/Diff/DiffField.jsx
src/components/manage/Diff/DiffField.test.jsx
src/components/manage/Diff/__snapshots__/DiffField.test.jsx.snap
src/components/theme/View/DefaultView.jsx

Fix DiffField for all possibile values coming from dexterity

Refs #982 - Fix DefaultView within History Diff context

---

CHANGELOG.md
src/components/manage/Widgets/ArrayWidget.jsx

Fixes #1332 
I tried to follow the practice in SelectWidget

Fix ArrayWidget to support static supermodel vocabulary

---

CHANGELOG.md
src/components/manage/Blocks/HTML/Edit.jsx
src/components/theme/App/App.jsx
src/middleware/crashReporter.js

- Lazy load `pretty` library, used in the HTML block
- Lazy load Raven lib

Easy low hanging fruits candidates for lazy loading

---

CHANGELOG.md
cypress/integration/user-control-panel.js
src/components/manage/Controlpanels/UsersControlpanel.jsx
src/components/manage/Controlpanels/UsersControlpanelUser.jsx
src/components/manage/Controlpanels/__snapshots__/UsersControlpanel.test.jsx.snap
src/components/manage/Controlpanels/__snapshots__/UsersControlpanelUser.test.jsx.snap

Adding new User to User Control Panel

---

README.md

Added a new website developed by RedTurtle and now published.

Added Stradanove to "Volto in Production"

---

CHANGELOG.md
theme/themes/pastanaga/extras/main.less
theme/themes/pastanaga/extras/print.less

Removing navbar, breadcrumbs, search icon from print

---

CHANGELOG.md
cypress/integration/folder-contents.js
src/components/manage/Blocks/Image/__snapshots__/ImageSidebar.test.jsx.snap
src/components/manage/Blocks/LeadImage/__snapshots__/LeadImageSidebar.test.jsx.snap
src/components/manage/Blocks/Listing/__snapshots__/ListingData.test.jsx.snap
src/components/manage/Blocks/Listing/__snapshots__/ListingSidebar.test.jsx.snap
src/components/manage/Sidebar/__snapshots__/ObjectBrowserBody.test.jsx.snap
src/components/manage/Widgets/CheckboxWidget.jsx
src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap

Make label of checkboxwidget clickable 

---

CHANGELOG.md
cypress/integration/folder-contents.js
src/components/manage/Contents/Contents.jsx
src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap

Adding cypress test for sorting in folder-content based on create field

---

CHANGELOG.md
src/actions/content/content.js
src/components/manage/Contents/Contents.jsx
src/reducers/content/content.js

Fix for https://github.com/plone/volto/issues/1461
Still without test. Please review, then I'll add a test.

Remember selected folder contents sort on and order

---

CHANGELOG.md
src/components/manage/Form/Form.jsx
src/components/theme/Comments/Comments.jsx
src/components/theme/Comments/__snapshots__/Comments.test.jsx.snap

fix error in comment form

---

CHANGELOG.md
cypress/integration/blocks-image.js
cypress/integration/blocks-indexing.js
cypress/integration/blocks-listing.js
cypress/integration/blocks-text.js
cypress/integration/blocks-video.js
cypress/integration/blocks.js
cypress/integration/createContent.js
cypress/integration/folder-contents.js
cypress/integration/listing-template.js
cypress/support/commands.js

Refactoring createContent command

---

CHANGELOG.md
cypress/integration/comments.js
cypress/support/commands.js

Adding cypress test for the comment

---

src/components/manage/Form/Form.jsx

Eea dx fields validation

---

CHANGELOG.md
src/components/theme/View/DefaultView.jsx

fix: mailto replacing by regex

---

CHANGELOG.md
src/components/manage/Add/Add.jsx
src/components/manage/Add/Add.test.jsx
src/components/manage/Form/Form.jsx
src/helpers/Blocks/Blocks.js
src/helpers/Blocks/Blocks.test.js

expose blocks and blocks_layout properties only on add/edit content type

---

cypress/integration/createContent.js
cypress/support/commands.js

Set a default fallback to create any contenttypes, that do not require any special fields for the createContent function in Cypress.

Cy generic contentcreation

---

theme/themes/pastanaga/extras/react-dates-overrides.less

Removed debug rule

---

README.md

Added Nuova Voce Ecologista between live website running Volto

Added NVE Volto website in production

---

CHANGELOG.md
src/components/manage/Contents/ContentsUploadModal.jsx

I don't like this solution, it shouldn't be needed.
But this is the only way I get localized strings for last modified date there.

I18n contents upload modal

---

CHANGELOG.md
src/server.jsx

Right now tests are failing because of that broken formatted files.

Format serverjsx

---

CHANGELOG.md
theme/themes/pastanaga/extras/react-dates-overrides.less

Fix datepicker zindex

---

CHANGELOG.md
src/helpers/Blocks/Blocks.js
src/helpers/Blocks/Blocks.test.js
src/helpers/index.js

Fixes #1653 
I've changed the initial proposal to return pairs of `[blockid, blockvalue]`.

Add getBlocks helper method

---

CHANGELOG.md
src/components/theme/Pagination/Pagination.jsx
src/components/theme/Pagination/__snapshots__/Pagination.test.jsx.snap
theme/themes/pastanaga/collections/menu.overrides

#1690 
This is how it looks with the pastanaga icon.

fix: pagination-icon

---

CHANGELOG.md
src/actions/content/content.js
src/middleware/api.js

When batch uploading content, serialize those requests in createContent action

---

CHANGELOG.md
src/components/manage/Widgets/FileWidget.jsx

Fixing file-preview other than image

---

CHANGELOG.md
theme/themes/pastanaga/extras/toolbar.less

Fixing bug related to closing the more menu in toolbar

---

CHANGELOG.md
src/config/RichTextEditor/ToHTML.jsx

this resolves this issue: https://github.com/plone/volto/issues/1768

Fix bug for text block with new line and styles applyed to all text.

---

CHANGELOG.md
cypress/integration/listing-template.js

Related to #1750 
I have added the same step in cypress which you mention in issue.

Adding cypress test for image-gallery in edit-mode

---

CHANGELOG.md
src/components/manage/Widgets/NumberWidget.jsx
src/components/manage/Widgets/NumberWidget.test.jsx
src/components/manage/Widgets/__snapshots__/NumberWidget.test.jsx.snap
src/config/Widgets.jsx

A very basic implementation for a NumberWidget.
Do we want to specify limits? Min-max? I've included the "defaultValue" parameter, I think all widgets should have it.

Add number widget

---

CHANGELOG.md
src/components/manage/Preferences/__snapshots__/PersonalPreferences.test.jsx.snap
src/components/manage/Widgets/SelectWidget.jsx
src/components/manage/Widgets/__snapshots__/SelectWidget.test.jsx.snap

Fix console warning due to uncontrolled SelectWidget

---

CHANGELOG.md
theme/themes/pastanaga/collections/form.overrides

Fixes https://github.com/plone/volto/issues/1726

Hyphenate sidebar labels

---

CHANGELOG.md
src/components/manage/Controlpanels/UsersControlpanelUser.jsx

showing username when firstname attr is missing

---

CHANGELOG.md
razzle.config.js

razzle.config had some estlint disabling comments at the top. I've removed them and cleaned up the file.

Remove eslint instructions in razzle.config.js, cleanup file

---

CHANGELOG.md
theme/themes/pastanaga/extras/toolbar.less

Reverts plone/volto#1815 Issue was already fixed by @iFlameing in #1818. #1815 introduces some other problems.

Revert "Profile toolbar fix"

---

CHANGELOG.md
src/components/manage/Sidebar/ObjectBrowserBody.jsx

Fixing objectBrowser search reload

---

CHANGELOG.md
src/actions/querystringsearch/querystringsearch.js

Relative querystring

---

CHANGELOG.md
src/components/manage/Form/Form.jsx

Fixing bug for editing the table block

---

CHANGELOG.md
src/config/RichTextEditor/ToHTML.jsx

Fixes #1908. 
Please review it and make comment if I miss something :)

Adding softlinebreak for list tag

---

CHANGELOG.md
README.md

Just added our two new sites to the README File incl. Changelog Entry

Volto sites in production update

---

CHANGELOG.md
src/components/index.js
src/components/manage/ConditionalLink/ConditionalLink.jsx
src/components/manage/UniversalLink/UniversalLink.jsx
src/components/manage/UniversalLink/UniversalLink.test.jsx
src/components/manage/UniversalLink/__snapshots__/UniversalLink.test.jsx.snap
src/config/RichTextEditor/ToHTML.jsx

As ConditionalLink wraps links under conditions, this helps with URL handling for external, internal and Plone download links.

added UniversalLink component to handle internal/external/download links

---

CHANGELOG.md
src/components/manage/Blocks/Table/View.jsx
src/components/manage/Blocks/Table/__snapshots__/View.test.jsx.snap

the table block was wrapped in a `<p>` which is bad HTML.

Fix SSR rendering in table blocks

---

CHANGELOG.md
__tests__/create-addons-loader.test.js
create-addons-loader.js

path.sep is not slash on windows, it was wrong to rely on it

Fix addons loader compatibility with Windows

---

CHANGELOG.md
src/components/index.js
src/components/manage/Sidebar/ObjectBrowserBody.jsx
src/routes.js

Those are not certainly killers of the problem, but certainly helps.
Also, the tests seems to run faster. (55secs vs 85secs in a quad core machine)

Fix some key points to improve the circular imports problem

---

CHANGELOG.md
src/components/manage/Widgets/NumberWidget.jsx
src/components/manage/Widgets/SchemaWidget.jsx
src/components/manage/Widgets/__snapshots__/SchemaWidget.test.jsx.snap

https://github.com/plone/volto/issues/2059

Numeric Widget Schema fixes refs #2059

---

CHANGELOG.md
src/components/manage/Contents/Contents.jsx

Adding All button in folder content

---

CHANGELOG.md
docs/mkdocs.yml
docs/source/configuration/environmentvariables.md
src/server.jsx

Allow setting a custom robots.txt from an environment variable

---

CHANGELOG.md
cypress/integration/sharing.js
src/components/manage/Sharing/Sharing.jsx

Fix sharing page when using with Guillotina

---

CHANGELOG.md
cypress/integration/history.js
src/components/manage/Toolbar/More.jsx

Fix broken More menu when no history action

---

CHANGELOG.md
src/components/manage/Blocks/Text/Edit.jsx
src/components/manage/Form/Form.jsx

added support for allowedBlocks and showRestricted for BlockChooser in Form

AllowedBlocks and showRestricted in Form

---

CHANGELOG.md
src/components/manage/Blocks/Table/Edit.jsx

Added preventDefault and stopPropagation for toolbar buttons of Table block

Added preventDefault and stopPropagation for Table Block

---

CHANGELOG.md
src/components/manage/Widgets/SelectStyling.jsx

Nice to have styling for Group component used in `<Select/>` Widget.

custom group component for SelectStyling

---

CHANGELOG.md
src/components/manage/Blocks/Text/Edit.jsx

fixes https://github.com/plone/volto/issues/2190

fix view links and others styles of entities on editing Text Block

---

api/buildout.cfg

Test p.restapi 7.0.0 and 5.2.3

---

CHANGELOG.md
src/components/manage/UniversalLink/UniversalLink.jsx

added flattenToAppURL to download link

Fix UniversalLink for download link

---

packages/generator-volto/CHANGELOG.md
packages/generator-volto/generators/app/index.js

generator: default workspaces path

---

CHANGELOG.md
docs/source/contributing/guidelines.md
docs/source/contributing/index.md

Adjusting docs in the _contributing_ chapter
- One sentence per line
- Adding links
- Wording

Docs contributing

---

CHANGELOG.md
docs/source/blocks/editcomponent.md
src/components/index.js
src/components/manage/Sidebar/ObjectBrowser.jsx
src/components/manage/Sidebar/ObjectBrowserBody.jsx
src/components/manage/Sidebar/SidebarPopup.jsx
src/components/manage/Sidebar/SidebarPopup.stories.mdx
src/components/manage/Sidebar/SidebarPopup.test.jsx
src/components/manage/Sidebar/__snapshots__/SidebarPopup.test.jsx.snap

- Custom Generic Sidebar outside Blocks scope.
- Extra configuration for widgets within SidebarPortal.

Added SidebarPopup component for extra sidebar handling

---

CHANGELOG.md
src/components/manage/Blocks/Block/BlocksForm.jsx
src/components/manage/Blocks/Block/Edit.jsx
src/components/manage/Form/InlineForm.jsx
src/components/manage/Form/__snapshots__/InlineForm.test.jsx.snap

Fix multiselected includes

---

CHANGELOG.md
README.md
docker-compose.yml
entrypoint.sh

Add docker compose with both backend and frontend for quick demos

---

CHANGELOG.md
src/components/manage/Sidebar/SidebarPortal.jsx
src/components/manage/Sidebar/__snapshots__/SidebarPortal.test.jsx.snap

This reverts commit 32a5dfd99b24fe538faca61529802b3847471995.

Revert "Fix SidebarPortal min-height (#2292)"

---

CHANGELOG.md
src/components/manage/Form/Form.jsx

Fix Text Block placeholder regression refs #2322

---

CHANGELOG.md
src/components/theme/View/View.jsx
src/config/index.js

Add possibility to disable tags on default View via config.settings.showTags

Add showTags setting to be able to configure tags visibility

---

CHANGELOG.md
src/components/manage/BlockChooser/BlockChooser.jsx
src/components/manage/BlockChooser/BlockChooser.test.jsx
src/components/manage/BlockChooser/__snapshots__/BlockChooser.test.jsx.snap
src/components/manage/Blocks/Block/BlocksForm.jsx
src/components/manage/Blocks/Block/Edit.jsx
src/components/manage/Blocks/Table/Edit.jsx
src/components/manage/Blocks/Table/Edit.test.jsx
src/components/manage/Blocks/Text/Edit.jsx
src/components/manage/Blocks/Text/Edit.test.jsx
src/helpers/Blocks/Blocks.js
src/helpers/Blocks/Blocks.test.js
src/helpers/index.js

Use `onInsertBlock` callback when adding new blocks if available

---

.github/workflows/docs.yml
CHANGELOG.md

Create a new workflow to generate the documentation and then push it to the Documentation server of the Plone Foundation.

Move docs to plone infrastructure

---

CHANGELOG.md
src/components/manage/Widgets/SelectWidget.jsx

move isObject condition below isArray condition for a correct multi-select selected values rendering.
See: https://github.com/plone/volto/pull/1916#issuecomment-823415191

Correct the selected values rendering at isMulti SelectWidget

---

CHANGELOG.md
src/components/theme/View/RenderBlocks.jsx
src/components/theme/View/RenderBlocks.test.jsx
src/components/theme/View/__snapshots__/RenderBlocks.test.jsx.snap

fixes https://github.com/plone/volto/issues/2416

RenderBlocks with path

---

CHANGELOG.md
docs/source/configuration/settings-reference.md
src/components/manage/UniversalLink/UniversalLink.jsx
src/components/manage/UniversalLink/UniversalLink.test.jsx
src/config/NonContentRoutes.jsx
src/config/index.js
src/routes.js

Revert "Internal url blacklist"

---

CHANGELOG.md
src/components/manage/Blocks/Listing/View.jsx

Avoid sending undefined as path parameter at Blocks/Listing/View.jsx

---

CHANGELOG.md
cypress/tests/core/blocks-listing.js

Cypress test for listing block at root page.
Now gives an error, trying to fix it at #2451

add new cypress test for listing block

---

CHANGELOG.md
package.json

Support for  https://volta.sh/
Non intrusive change, enables correct  versioning for volta toolchain if used

Volta support

---

CHANGELOG.md
src/components/manage/Contents/ContentsItem.jsx

Improve folder_contents workflow state

---

CHANGELOG.md
src/config/RichTextEditor/ToHTML.jsx

Resolves https://github.com/plone/volto/issues/2494

Fix addBreaklinesInline when string ends with new line

---

CHANGELOG.md
docs/source/recipes/pluggables.md
src/components/manage/Pluggable/Pluggable.test.js
src/components/manage/Pluggable/__snapshots__/Pluggable.test.js.snap
src/components/manage/Pluggable/index.js

The code got a bit uglier... :(

Fix `Pluggable` when `Plug` is empty

---

CHANGELOG.md
src/components/manage/BlockChooser/BlockChooser.jsx
src/components/manage/BlockChooser/__snapshots__/BlockChooser.test.jsx.snap
src/components/manage/Edit/Edit.jsx
theme/themes/pastanaga/extras/blocks.less

Fix https://github.com/plone/volto/issues/2548

Hyphenation block chooser labels

---

CHANGELOG.md
src/components/manage/BlockChooser/BlockChooser.jsx
src/components/manage/BlockChooser/__snapshots__/BlockChooser.test.jsx.snap
theme/themes/pastanaga/extras/blocks.less

Revert introduced html change from https://github.com/plone/volto/pull/2549

Hyphenation of block chooser labels without html change

---

CHANGELOG.md
package.json
yarn.lock

Revert "Upgrade to Storybook 6.3, refresh deps for babel"

---

CHANGELOG.md
src/components/manage/Widgets/ObjectListWidget.jsx

Added intl to pass through schemaExtender in the ObjectListWidget component.
My first pull request to the world of open source.

#2536 passed intl to schemaExtender in ObjectListWidget

---

CHANGELOG.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/manage/Toolbar/More.jsx
src/components/manage/Toolbar/PersonalTools.jsx
src/components/manage/Toolbar/Toolbar.jsx
src/components/manage/Toolbar/__snapshots__/More.test.jsx.snap
src/components/manage/Toolbar/__snapshots__/PersonalTools.test.jsx.snap
src/components/manage/Toolbar/__snapshots__/Toolbar.test.jsx.snap
src/config/index.js

Add title/tooltip on Toolbar buttons

---

CHANGELOG.md
src/components/manage/Contents/Contents.jsx
src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap

The search filter when selecting content items via dropdown doesn't seems to be implemented. 
Just to be sure, I'm talking about this:

implement item selection search filter in folder contents

---

CHANGELOG.md
src/actions/blocksClipboard/blocksClipboard.js

This solves this ISSUE: https://github.com/plone/volto/issues/2448

Cut/Copy blocks: fixed cut/copy unselected blocks.

---

CHANGELOG.md
src/components/theme/SearchWidget/SearchWidget.jsx

Fix SearchWidget required pathname

---

CHANGELOG.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/manage/History/History.jsx
src/components/manage/History/__snapshots__/History.test.jsx.snap

@tisto screenshot of implementation

Showing version in History view

---

CHANGELOG.md
src/components/manage/Widgets/WysiwygWidget.jsx

Add placeholder prop (empty by default as it currently is) to WysiwygWidget

feat: add placeholder to wysiwyg widget

---

CHANGELOG.md
src/config/NonContentRoutes.jsx

Fix this issue for the isCmsUi fn:
https://github.com/plone/volto/issues/870

Fix /edit and /add nonContentRoutes to fix isCmsUi fn

---

CHANGELOG.md
src/server.jsx

Defer loading the dev proxy middleware until after the express middleware

---

CHANGELOG.md
src/helpers/Sitemap/Sitemap.js

use Plone site search settings when building the sitemap.xml.gz

---

CHANGELOG.md
src/components/manage/Blocks/Listing/ListingData.jsx
src/components/manage/Form/BlockDataForm.test.jsx
src/components/manage/Form/InlineForm.jsx
src/components/manage/Form/InlineForm.test.jsx
src/helpers/Extensions/withBlockSchemaEnhancer.js

Fix default in block variation select; avoid block API in InlineForm

---

CHANGELOG.md
src/components/manage/Blocks/Listing/withQuerystringResults.jsx
src/components/manage/Blocks/Search/SearchBlockView.jsx
src/helpers/Utils/usePagination.js
src/helpers/Utils/usePrevious.js
src/helpers/index.js

Also added usePrevious helper.

Fix pagination in search block when changing filters

---

CHANGELOG.md
theme/themes/pastanaga/extras/blocks.less

Not possible to drag a full-width image

---

CHANGELOG.md
locales/it/LC_MESSAGES/volto.po

Translated Search Block and Locking behavior.
Minor fixes.

Improve italian translation

---

CHANGELOG.md
src/components/manage/Blocks/Text/Edit.jsx

Removing the hardcoded default block type from text block

---

CHANGELOG.md
src/components/manage/Sidebar/ObjectBrowserBody.jsx

Issue here: https://github.com/plone/volto/issues/2812

Fix object browser multiple

---

CHANGELOG.md
package.json
yarn.lock

Reverts https://github.com/plone/volto/pull/828

Remove bundlesize dependency

---

CHANGELOG.md
src/config/index.js

fixed default value from 'Link' to 'File'.

fixed downloadableObjects default value

---

CHANGELOG.md
src/actions/schema/schema.js
src/actions/schema/schema.test.js
src/components/manage/Add/Add.jsx
src/components/manage/Edit/Edit.jsx

Get Add/Edit schema contextually

---

CHANGELOG.md
src/components/theme/Navigation/NavItem.jsx
src/components/theme/Navigation/NavItems.jsx
src/components/theme/Navigation/Navigation.test.jsx
src/components/theme/Navigation/__snapshots__/Navigation.test.jsx.snap

Fix external link not supported by Navigation component

---

CHANGELOG.md
src/components/theme/Login/Login.jsx

Remove getNavigation from Login.jsx

---

CHANGELOG.md
theme/themes/pastanaga/extras/sidebar.less
theme/themes/pastanaga/extras/toolbar.less
theme/themes/pastanaga/globals/site.variables

Fix typo toolbalWidth

---

.gitignore
CHANGELOG.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/theme/View/LinkView.jsx

Fix missing translation in link content type

---

CHANGELOG.md
cypress/tests/core-sandbox/listingblock.js
packages/core-sandbox/src/components/Blocks/Listing/ListingBlockVariationTeaserContent.jsx
packages/core-sandbox/src/index.js
src/components/manage/Blocks/Listing/withQuerystringResults.jsx

Listing block fullobjects option per variation

---

CHANGELOG.md
webpack-less-plugin.js

Allow loading less files in project

---

CHANGELOG.md
src/config/Views.jsx

Add a default view layout do document_view

---

CHANGELOG.md
api/buildout.cfg

fix: correctly checkout plone.volto in buildout

---

packages/scripts/CHANGELOG.md
packages/scripts/addon.js
packages/scripts/package.json
packages/scripts/yarn.lock

and this... : Merry Christmas!

Initial version of the CLI for addon testing

---

CHANGELOG.md
locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/theme/CorsError/CorsError.jsx

So I was having some issues routing the backend 🙈 and couldn't help notice the spelling mistake.

Fix spelling error on backend unreachable

---

CHANGELOG.md
docs/source/recipes/widget.md
src/components/manage/Widgets/VocabularyTermsWidget.jsx
src/components/manage/Widgets/VocabularyTermsWidget.stories.js
src/components/manage/Widgets/__snapshots__/VocabularyTermsWidget.test.jsx.snap

Check the storybook to see what the widget does.

VocabularyTermsWidget: Let token be editable on creation of term.

---

CHANGELOG.md
src/components/theme/Navigation/Navigation.jsx
src/components/theme/Navigation/__snapshots__/Navigation.Multilingual.test.jsx.snap
src/components/theme/Navigation/__snapshots__/Navigation.test.jsx.snap

Fix A11Y violations in Navigation

---

CHANGELOG.md
Makefile
docs/source/configuration/environmentvariables.md
docs/source/configuration/internalproxy.md
docs/source/recipes/environment-variables.md

@fredvd trying to improve a bit the situation with this. It would be great if we could have a feedback session with you, so we can know all the issues you've encountered with this. I'm aware it's not perfect yet, but trying to get there.
CORS is hard, and the concepts have to be quite in mind when dealing with it. So explaining all involving CORS concept and how we bypass/deal with it in Volto and document it properly is essential for Plone developers.
Maybe we have to improve too the console messages, which might mislead instead of help. Regarding naming, or change the intent of who does what is hard, if we don't want to face breaking changes. 
Let me know what's the outcome!

Improve docs on environment variables, add recipes

---

CHANGELOG.md
src/components/manage/Widgets/UrlWidget.jsx
src/components/manage/Widgets/__snapshots__/UrlWidget.test.jsx.snap

fix A11y Violations  in Button tag - 'aria-label'

Fix the a11y violation of UrlWidget

---

packages/generator-volto/CHANGELOG.md
packages/generator-volto/generators/app/templates/Makefile

Remove unused broken ADDON env.

Fix app template Makefile

---

CHANGELOG.md
src/components/manage/Toolbar/PersonalTools.jsx
src/components/manage/Toolbar/PersonalTools.test.jsx

Add Pluggable to toolbar user menu

---

CHANGELOG.md
src/components/theme/Component/Component.jsx
src/components/theme/Component/Component.test.jsx

Change prop `name` -> `componentName` in component `Component`

---

CHANGELOG.md
locales/eu/LC_MESSAGES/volto.po

Translating the recurrence widget is as hard as in mockup 😅😅

[i18n] complete basque translation

---

CHANGELOG.md
theme/themes/pastanaga/extras/sidebar.less

Fix overflow long filename filewidget

---

CHANGELOG.md
docs/source/conf.py
docs/source/recipes/environment-variables.md
docs/source/upgrade-guide/index.md

Fix links, add commits

---

CHANGELOG.md
src/reducers/content/content.js

Fix error when lock data is gone after an invariant error.

---

CHANGELOG.md
README.md
docs/source/getting-started/install.md

Revert "Fixed development environment setup commands"

---

CHANGELOG.md
src/components/index.js
src/components/manage/Blocks/Listing/SummaryTemplate.jsx
src/components/theme/PreviewImage/PreviewImage.jsx
src/components/theme/PreviewImage/PreviewImage.test.js
src/components/theme/PreviewImage/__snapshots__/PreviewImage.test.js.snap
src/config/Components.jsx
src/config/index.js

Related to this PR https://github.com/plone/volto/pull/2888. This removes the cover feature.
I've created a new branch because I messed up the 'rebasing to master' on 'preview_image' branch.

Add PreviewImage component

---

CHANGELOG.md
docs/source/addons/best-practices.md

s/addon/add-on
This should build on Netlify because there is a change in docs.

Add html_meta values

---

CHANGELOG.md
src/config/RichTextEditor/index.js
src/config/index.js

[Bug 3111] - Move customStyleMap to richtextEditorSettings

---

packages/generator-volto/CHANGELOG.md
packages/generator-volto/generators/app/templates/.storybook/main.js

fix: broken `webpack-plugins` import in storybook for projects

---

CHANGELOG.md
docs/source/getting-started/install.md
docs/source/upgrade-guide/index.md

See https://github.com/plone/training/issues/613 and https://github.com/plone/documentation/issues/1235
This PR must be merged before I can work on other repos that link to the main docs.

Add labels for Intersphinx

---

packages/generator-volto/CHANGELOG.md
packages/generator-volto/generators/app/templates/package.json.tpl

We need the "patcher" now, for existing installations... sprint anyone?

Fix omelette command

---

CHANGELOG.md
src/helpers/Cookies/cookies.js

Fixed calculation of secure cookie. Default was false and was not testing window.location

fixed secure cookie option

---

CHANGELOG.md
src/helpers/Cookies/cookies.js

Fixed secure cookie option.

---

CHANGELOG.md
cypress/tests/core/blocks-video.js
locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/manage/Blocks/Video/Body.jsx
src/components/manage/Blocks/Video/Edit.jsx
src/components/manage/Blocks/Video/View.jsx
src/components/manage/Blocks/Video/__snapshots__/Edit.test.jsx.snap
src/components/manage/Blocks/Video/__snapshots__/View.test.jsx.snap
theme/themes/pastanaga/extras/blocks.less

Backport for Volto 15 for https://github.com/plone/volto/pull/3261

Light embed video backport15

---

CHANGELOG.md
src/components/manage/Widgets/QueryWidget.jsx

Backport for Volto 15 for https://github.com/plone/volto/pull/3301

fixed missing criteria in QueryWidget

---

CHANGELOG.md
locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/theme/PasswordReset/PasswordReset.jsx
src/components/theme/PasswordReset/RequestPasswordReset.jsx
src/components/theme/PasswordReset/__snapshots__/RequestPasswordReset.test.jsx.snap
src/config/index.js

Backport for Volto 15 for https://github.com/plone/volto/pull/3299

Changed identifier field for password reset to 'username'

---

CHANGELOG.md
src/components/manage/Blocks/Video/Body.jsx
src/components/manage/Blocks/Video/Edit.jsx
src/components/manage/Blocks/Video/View.jsx

backport for https://github.com/plone/volto/pull/3354

Backport fix youtube list video

---

CHANGELOG.md
src/components/theme/View/RenderBlocks.jsx
src/components/theme/View/__snapshots__/RenderBlocks.test.jsx.snap

Bug fix Renderblocks path

---

CHANGELOG.md
src/components/manage/Blocks/Search/components/DateRangeFacet.jsx
src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
src/components/manage/Widgets/ArrayWidget.jsx
src/components/manage/Widgets/DatetimeWidget.jsx
src/components/manage/Widgets/RecurrenceWidget/ByDayField.jsx
src/components/manage/Widgets/RecurrenceWidget/MonthOfTheYearField.jsx
src/components/manage/Widgets/RecurrenceWidget/Occurences.jsx
src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
src/components/manage/Widgets/RecurrenceWidget/Utils.js
src/components/manage/Widgets/RecurrenceWidget/WeekdayOfTheMonthField.jsx
src/components/manage/Widgets/SelectAutoComplete.jsx
src/components/manage/Widgets/SelectWidget.jsx
src/components/manage/Widgets/TokenWidget.jsx
src/components/theme/View/EventDatesInfo.jsx

Locale from state

---

CHANGELOG.md
locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/manage/Toolbar/More.jsx
src/components/manage/Toolbar/__snapshots__/More.test.jsx.snap

Backport to Volto 15 for #3388

Working copy actions now render errors if they fail (Volto 15 version)

---

CHANGELOG.md
src/components/manage/Widgets/TokenWidget.jsx

fixes https://github.com/plone/volto/issues/3393

fix TokenWidget choices when editing a recently created content

---

CHANGELOG.md
src/helpers/Blocks/Blocks.js

BlockStyleWrapper: Cannot read properties of undefined

---

CHANGELOG.md
src/components/manage/Blocks/Search/SearchBlockEdit.jsx

search listing schema enhancer v15

---

CHANGELOG.md
cypress/tests/core/blocks/blocks-video.js
src/components/theme/View/DefaultView.jsx
src/components/theme/View/DefaultView.test.jsx
src/reducers/content/content.js

https://github.com/plone/volto/issues/3481

Improve the new DefaultView

---

CHANGELOG.md
locales/de/LC_MESSAGES/volto.po

Unanehmlichkeit -> Unannehmlichkeit

Fix typo in de locale

---

CHANGELOG.md
packages/generator-volto/generators/app/templates/yarn.lock
packages/generator-volto/yarn.lock
packages/scripts/yarn.lock
yarn.lock

Resolves https://github.com/advisories/GHSA-896r-f27r-55mw

Update json-schema including transitive dependencies

---

CHANGELOG.md
src/components/theme/Pagination/Pagination.jsx

fix propTypes warning for Pagination component

---

CHANGELOG.md
src/components/manage/Widgets/ArrayWidget.jsx

Reload vocab for ArrayWidget if vocabBaseUrl changed

---

CHANGELOG.md
src/components/theme/Login/Login.jsx

Fix login form redirect with trailing slash

---

CHANGELOG.md
locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/theme/RequestTimeout/RequestTimeout.jsx
src/components/theme/RequestTimeout/RequestTimeout.test.jsx
src/components/theme/RequestTimeout/__snapshots__/RequestTimeout.test.jsx.snap
src/config/Views.jsx
src/helpers/Api/Api.js
src/middleware/api.js

this solves https://github.com/plone/volto/issues/3576

Handle no connection available error (408 error)

---

CHANGELOG.md
src/components/manage/Widgets/ArrayWidget.jsx
src/components/manage/Widgets/ObjectBrowserWidget.jsx
src/components/manage/Widgets/ObjectBrowserWidget.stories.js
src/components/manage/Widgets/SelectAutoComplete.jsx
src/components/manage/Widgets/SelectWidget.jsx
src/components/manage/Widgets/TokenWidget.jsx

same pr for volto 15 from https://github.com/plone/volto/pull/2990#pullrequestreview-1084937493

Added placeholder param to widget, to change default placeholder

---

src/actions/users/users.js
src/actions/users/users.test.js

Would this work?
I am concerned about the treatment of default parameter in JS. I guess that if there is no parameter it should be treated like it was before do a plain call to `/@users` 
@sneridagh @ksuess

check for variable type not to introduce a breaking change

---

CHANGELOG.md
src/components/manage/Display/Display.jsx
src/components/manage/Display/__snapshots__/Display.test.jsx.snap
src/components/manage/Workflow/Workflow.jsx
src/components/manage/Workflow/__snapshots__/Workflow.test.jsx.snap
theme/themes/pastanaga/extras/toolbar.less

Improve `Display` and `Workflow` widgets in `More` menu. Fix alignments.

---

CHANGELOG.md
cypress/tests/core/basic/sharing.js
src/components/manage/Sharing/Sharing.jsx

Fix sharing page after using Pluggables

---

CHANGELOG.md
docs/source/configuration/volto-slate/writing-plugins.md
docs/source/getting-started/install.md

Needs to be merged at the same time as https://github.com/plone/documentation/pull/1295

Docs cleanup and linkcheck

---

CHANGELOG.md
packages/volto-slate/src/editor/extensions/normalizeNode.js

I come up with a solution regarding the issue: https://github.com/plone/volto/issues/3597

Fix: Slate Editor: can not delete bullet point after adding it by type - 

---

CHANGELOG.md
cypress/tests/core/basic/sharing.js
src/components/manage/Toolbar/Toolbar.jsx
theme/themes/pastanaga/extras/toolbar.less

specific menuStyle for 'more' menu

Fix types menu mobile

---

CHANGELOG.md
src/components/manage/Contents/Contents.jsx

Make sure react-dnd DragDropContext is a singleton

---

CHANGELOG.md
docs/source/conf.py
docs/source/getting-started/install.md
docs/source/releases.md
docs/source/upgrade-guide/index.md

After this is merged, approve and merge https://github.com/plone/documentation/pull/1321

Fix broken links to nvm releases.

---

CHANGELOG.md
src/components/manage/Widgets/NumberWidget.jsx

Add nulish coalescence operator in Number widget

---

CHANGELOG.md
src/components/manage/Form/BlockDataForm.jsx
src/components/manage/Form/BlockDataForm.test.jsx
src/components/manage/Form/__snapshots__/BlockDataForm.test.jsx.snap

Style extensions

---

CHANGELOG.md
yarn.lock

to avoid multiple copies of dependencies

Run yarn deduplicate

---

CHANGELOG.md
src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
src/components/theme/EventDetails/EventDetails.jsx
src/components/theme/View/EventDatesInfo.jsx
src/config/Loadables.jsx

remaining RRule constants in [Utils.js..](https://github.com/plone/volto/blob/master/src/components/manage/Widgets/RecurrenceWidget/Utils.js)
that i don't know what's the best solution to use RRule constants without injectLazyLib... it's a Utils..

lazyloading of rrule lib

---

CHANGELOG.md
cypress/tests/core/basic/groups-controlpanel.js

Under the heavy development happening to release V16 final we cannot afford this, they were failing 1/2 time.

More disable flaky test regarding many users/groups (related to #3705)

---

packages/generator-volto/CHANGELOG.md
packages/generator-volto/generators/app/templates/.gitignorefile

Restrict only to `/cache` in `.gitignore`

---

CHANGELOG.md
locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
src/components/theme/Logout/Logout.jsx
src/components/theme/Logout/Logout.test.jsx

Previous faulty behaviour: redirected to / on logout.

Fix logout to stay on the same page where the user was

---

CHANGELOG.md
package.json
yarn.lock

Upgrade dependency rrule (optional dependency luxon removed)

---

CHANGELOG.md
src/components/manage/Widgets/ArrayWidget.jsx
src/components/manage/Widgets/SelectAutoComplete.jsx
src/components/manage/Widgets/SelectStyling.jsx
src/components/manage/Widgets/SelectWidget.jsx
src/components/manage/Widgets/TokenWidget.jsx

Add a popup tooltip for tokenized options in Select widget values

---

CHANGELOG.md
addon-registry.js
create-addons-loader.js
docs/source/configuration/environmentvariables.md
razzle.config.js

Allow dumping addon dependency graph to a .dot file

---

CHANGELOG.md
docs/source/theming/theming-strategy.md

Docs theming strategy

---

CHANGELOG.md
src/components/manage/Contents/Contents.jsx
src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap

Add clear button in search field of Folder content view

---

CHANGELOG.md
cypress/tests/multilingual/basic-multilingual.js
cypress/tests/workingCopy/cancelling.js
src/components/theme/View/View.jsx
src/components/theme/View/View.test.jsx

Ensure the view component is always replaced after navigating

---

.husky/post-checkout
.husky/post-merge
.husky/post-rebase
.husky/pre-commit
CHANGELOG.md
docs/source/upgrade-guide/index.md
package.json
yarn.lock

piggybacking in https://github.com/plone/volto/pull/2394 but only for Volto. If someone wants to add it to their project, it's up to them.
Thanks @nileshgulia1 for pushing for it and the initial investigation!

Upgrade husky to the latest version

---

CHANGELOG.md
docs/source/getting-started/install.md

Added --canary flag in volto/install.md

---

CHANGELOG.md
__tests__/addon-registry.test.js
addon-registry.js
docs/source/recipes/customizing-components.md

Useful if you want to customize, say, `src/theme.js`  (because this: https://github.com/plone/volto/blob/94a0a5446fcd99bf6e32a6e4b64b79f67a1b6b98/src/start-client.jsx#L2 )

Allow addons to customize modules from a Volto project

---

CHANGELOG.md
src/components/manage/Blocks/Search/schema.js

Fixes: #3883 
See rationale there, we have to discuss this change in a Volto Team Meeting.

Revert #2828 PR change of the default `showSearchButton` Search block behavior

---

CHANGELOG.md
package.json
packages/generator-volto/CHANGELOG.md
packages/generator-volto/generators/app/templates/.yarnrc.yml

and Fix `package.json` `postinstall` in core

Missing `.yarnrc.yml` entry for the yarn 3 release

---

CHANGELOG.md
yarn.lock

These were submitted by dependabot in #3898 and #3906, but dependabot's PRs do not have permission to use the secret for cypress, so let's try here.

Minor dependency updates

---

.gitignore
CHANGELOG.md
package.json
razzle.config.js

Reverts plone/volto#3913
See https://github.com/plone/volto/pull/3913#issuecomment-1320087893

Revert "Configure Jest's moduleNameMapper with AddonConfigurationRegistry"

---

CHANGELOG.md
docs/source/configuration/settings-reference.md
docs/source/deploying/sentry.md
docs/source/upgrade-guide/index.md

* Update documentation of Sentry integration.
* Update docs/source/configuration/settings-reference.md
Co-authored-by: Steve Piercy <web@stevepiercy.com>
Co-authored-by: Steve Piercy <web@stevepiercy.com>

Update documentation of Sentry integration. (#3927)

---

CHANGELOG.md
src/helpers/Blocks/Blocks.test.js

@tiberiuichim cherry picked your last two commits. Let's use the "normal" flow too, then backport to 16.
Supersedes: #3931

More block defaults edge cases

---

CHANGELOG.md
packages/volto-slate/src/editor/plugins/Markdown/constants.js

Fix issue when using list markdown when list is already active. (#3946)

---

CHANGELOG.md
src/components/manage/Contents/Contents.jsx
src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap
theme/themes/pastanaga/extras/blocks.less
theme/themes/pastanaga/extras/contents.less

Backport of #3892
Is this the right thing to do with this?

Backport #3892 to 16.x.x branch

---

docs/source/configuration/experimental.md
docs/source/configuration/index.md

Add docs page about experimental features

---

docs/source/configuration/experimental.md
docs/source/configuration/index.md

Co-authored-by: Steve Piercy <web@stevepiercy.com>

Add docs page about experimental features (#3942)

---

CHANGELOG.md
__tests__/create-addons-loader.test.js
package.json

Fix addons loader test (#3961)

---

CHANGELOG.md
src/components/manage/Controlpanels/Users/UsersControlpanel.jsx

Fix user search by full name in users control panel (#3962)

---

CHANGELOG.md
packages/volto-slate/src/editor/ui/Toolbar.jsx

Fix crash in slate toolbar on html richtext field

---

CHANGELOG.md
src/components/manage/Blocks/Search/components/SelectFacet.jsx

Add tooltip to multivalue labels in select facet (#3976)

---

CHANGELOG.md
docs/source/upgrade-guide/index.md

Fixes https://github.com/plone/volto/issues/3979

Rewrite "Upgraded core to use Cypress 11" section

---

CHANGELOG.md
README.md
RELEASING.md
docs/source/developer-guidelines/contributing.md
news/3985.feature
package.json
packages/scripts/templates/towncrier_template.jinja
towncrier.toml

If this turns out well, I will also migrate the Volto core packages.
Fixes: https://github.com/plone/volto/issues/3953

Towncrier support in Volto

---

CHANGELOG.md
README.md
RELEASING.md
docs/source/developer-guidelines/contributing.md
news/3985.feature
package.json
packages/scripts/templates/towncrier_template.jinja
towncrier.toml

Co-authored-by: Steve Piercy <web@stevepiercy.com>

Towncrier support in Volto (#3985)

---

docs/source/configuration/settings-reference.md
news/3995.documentation

Fixes https://github.com/plone/volto/issues/3995

Close the open glossary list

---

news/4024.internal
src/config/index.js
src/registry.js

closes: https://github.com/plone/volto/issues/4019

Remove appExtras dangling in configuration registry

---

news/4011.bugfix
packages/volto-slate/src/editor/config.jsx
packages/volto-slate/src/utils/blocks.js

@tiberiuichim I don't know is it correct but it works. 
screencast
https://user-images.githubusercontent.com/33936987/205070416-40aa58ba-f06b-485f-bfd9-f615c074eaba.mov

Fix subscript and supscript active at same time.

---

news/4006.bugfix
src/components/manage/Controlpanels/Users/UsersControlpanel.jsx

Clear error message when canceling user add

---

news/4002.feature
src/components/manage/Controlpanels/Groups/GroupsControlpanel.jsx
src/components/manage/Controlpanels/Users/UsersControlpanel.jsx

Translation of roles in users and groups control panel

---

docs/source/developer-guidelines/branch-policy.md

According to what we discussed in Slack and #4015

contribute i18n branch policy docs

---

CHANGELOG.md
locales/de/LC_MESSAGES/volto.po

Co-authored-by: Katja Süss <k.suess@rohberg.ch>

add missing german translations. all of them. (#4080)

---

cypress/support/commands.js
cypress/tests/core/blocks/blocks.js
news/4070.bugfix
src/components/manage/Blocks/Block/DefaultView.jsx

Co-authored-by: David Glick <david@glicksoftware.com>

Don't crash on unknown blocks (#4070)

---

Makefile
api/buildout.cfg
news/4071.bugfix

Co-authored-by: David Glick <david@glicksoftware.com>

Bump version for plone-backend (#4071)

---

news/4051.bug
package.json
yarn.lock

Co-authored-by: David Glick <david@glicksoftware.com>
Co-authored-by: Tiberiu Ichim <tiberiuichim@users.noreply.github.com>

Fix space in pseudo selector (#4051) (#4052)

---

CHANGELOG.md
src/components/manage/Form/Form.jsx
src/components/manage/Widgets/ArrayWidget.jsx

Fix select widget loosing focus when the value has changed (#4003)

---

cypress/tests/core/volto-slate/09-block-slate-slashmenu.js
news/4116.bugfix
packages/volto-slate/src/blocks/Text/SlashMenu.jsx
packages/volto-slate/src/blocks/Text/keyboard/slashMenu.js

Fixes https://github.com/plone/volto/issues/3960

Change SlashMenu to include block title in shortcut search

---

cypress/tests/core/volto-slate/09-block-slate-slashmenu.js
news/4116.bugfix
packages/volto-slate/src/blocks/Text/SlashMenu.jsx
packages/volto-slate/src/blocks/Text/keyboard/slashMenu.js

Co-authored-by: David Glick <david@glicksoftware.com>

Change SlashMenu to include block title in shortcut search (#4116)

---

docs/source/conf.py
news/4143.documentation

See https://github.com/plone/documentation/pull/1385

Fix URLs to Plone 6 docs

---

docs/source/developer-guidelines/index.md
docs/source/getting-started/install.md
news/4198.documentation

Refs: https://github.com/plone/volto/issues/4195

Add todo regarding management of Plone's backend. Update versions.

---

news/4242.bugfix
package.json
yarn.lock

In devmode, nothing is clickable on the site. This occurs due to a bug in react-error-overlay that displays an iframe that covers the whole page and steals the focus. At the same time, there is an error appearing in the console:
`ReferenceError: process is not defined`
The solution is to upgrade react-error-overlay.
This issue is [referenced here]
(https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined). Also described in details
[here](https://github.com/facebook/create-react-app/issues/11773).

fix iframe covering the page due to a react-error-overlay bug (#4242)

---

news/4176.feature
src/components/manage/Controlpanels/VersionOverview.jsx

We find this useful in our projects.

Show project name and version in control panel

---

CHANGELOG.md
src/components/manage/Blocks/Search/widgets/SelectMetadataField.jsx

Fix bug where label of search facet wasn't translated when the content object is being translated

Facet search label translation

---

news/4165.feature
package.json
src/components/manage/UniversalLink/UniversalLink.jsx
src/config/index.js
src/helpers/ScrollToTop/ScrollToTop.jsx
yarn.lock

Co-authored-by: Alin Voinea <contact@avoinea.com>

React router hash link (#4165)

---

packages/generator-volto/generators/app/templates/razzle.config.js
packages/generator-volto/news/3424.internal

Co-authored-by: Tiberiu Ichim <tiberiuichim@users.noreply.github.com>

made razzle.config.js in project template easier to extend (#4262)

---

news/4231.feature
src/components/manage/Blocks/Listing/ListingData.jsx
test-setup-config.js

Co-authored-by: Tiberiu Ichim <tiberiuichim@users.noreply.github.com>

Read listing block schema from configuration registry (#4231)

---

docs/source/configuration/settings-reference.md
news/4333.feature
src/components/manage/Toolbar/Toolbar.jsx

Fix https://github.com/plone/volto/issues/4333

Toolbar extendable by button in top and menu in bottom

---

docs/source/configuration/settings-reference.md
news/4272.documentation

Fixed grammar Error Closes #4272

Fixed grammar Error Closes #4272

---

news/4368.feature
src/components/manage/Controlpanels/Rules/components/VariableModal.jsx

Support server-provided schema for condition and action

---

docs/source/user-manual/copy-paste-blocks.md
news/4376.documentation

See https://github.com/plone/documentation/pull/1438

Use a universal path for both documentation and volto repos

---

news/4399.bugfix
src/components/manage/Contents/Contents.jsx

Fixes #4399 
@tisto  screenshot

Change the width of overlay

---

news/4425.bugfix
src/server.jsx

Solves https://github.com/plone/volto/issues/4424

On error pages, don't switch to default site language

---

docs/source/backend/index.md
news/4431.documentation

- Reformat features as definition list
- Update links
- Add link to issue for TODO

Tidy up backend/index.md

---

news/4393.feature
src/components/manage/Blocks/Listing/Edit.jsx
src/components/manage/Blocks/Listing/ListingBody.jsx
src/components/manage/Blocks/Listing/View.jsx
src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap

Add class name 'emptyListing' to listing body content and listing body header if no results.

Mark empty listings for optional hiding, per variation or globally

---

news/4526.bugfix
src/components/manage/BlockChooser/BlockChooser.jsx

Fix Search is case sensitive in Block chooser

---

news/3092.documentation
styles/Vocab/Plone/accept.txt
styles/Vocab/Plone/reject.txt

improved spellcheck and consistency for spelling by adding "NodeJS and JavaScript" to "accept.txt" and others in "reject.txt"

3092 improve spellcheck

---

locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
locales/zh_CN/LC_MESSAGES/volto.po
news/4656.bugfix
src/components/theme/PasswordReset/PasswordReset.jsx
src/components/theme/PasswordReset/RequestPasswordReset.jsx
src/components/theme/PasswordReset/__snapshots__/RequestPasswordReset.test.jsx.snap

Fixed wrong localization on password reset page(#4656)

---

news/4716.internal
package.json
yarn.lock

See https://security.snyk.io/package/npm/moment/2.24.0

Security upgrade for momentjs (v16)

---

news/4715.internal
package.json
yarn.lock

See https://security.snyk.io/package/npm/moment/2.24.0

Security upgrade for momentjs

---

news/3990.bugfix
src/components/theme/Login/Login.jsx
src/components/theme/Login/__snapshots__/Login.test.jsx.snap

Apply suggestion from browser for password field

---

news/4760.bugfix
src/reducers/actions/actions.js
src/reducers/breadcrumbs/breadcrumbs.js
src/reducers/navigation/navigation.js
src/reducers/types/types.js

Fix reducing expanders loaded in a subrequest

---

locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
locales/zh_CN/LC_MESSAGES/volto.po
news/4794.bugfix
src/components/manage/Controlpanels/Relations/RelationsListing.jsx
src/components/manage/Controlpanels/Relations/RelationsMatrix.jsx
src/helpers/MessageLabels/MessageLabels.js
theme/themes/pastanaga/extras/userscontrolpanel.less

Regarding https://github.com/plone/volto/issues/4789

update control panel layout

---

news/4825.bugfix
src/helpers/Api/Api.js

fix special characters in request urls

---

news/4826.bugfix
src/helpers/Api/Api.js

fix special characters in request urls (volto 16)

---

news/4838.feature
src/components/manage/Widgets/ColorPickerWidget.jsx

Allow to deselect color in ColorPickerWidget. (#4839)

---

locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fi/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
locales/zh_CN/LC_MESSAGES/volto.po
src/components/manage/LinksToItem/LinksToItem.jsx

only for those users who have access to control panels.
Addition to https://github.com/plone/volto/pull/4787

Toolbar: Link to relations control panel

---

cypress/support/commands.js
cypress/tests/core/blocks/blocks-listing.js
news/4159.bugfix
src/components/manage/Blocks/Listing/ListingBody.test.jsx
src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
src/components/manage/Blocks/Listing/withQuerystringResults.jsx
src/components/manage/Blocks/Search/hocs/withSearch.jsx
src/helpers/Utils/usePagination.js
src/helpers/Utils/usePagination.test.js

@erral please a last look before backporting.

Pagination with router params (#4698)

---

.github/workflows/acceptance.yml
.github/workflows/unit.yml
README.md
docs/source/getting-started/install.md
news/4901.bugfix
packages/generator-volto/generators/app/index.js
packages/generator-volto/generators/app/templates/package.json.tpl
packages/generator-volto/package.json
razzle.config.js
src/components/manage/Diff/DiffField.jsx
src/components/theme/FormattedDate/FormattedDate.jsx
src/helpers/Utils/Date.js
src/helpers/Utils/Date.test.js

Here's a workaround for the hash function issue with webpack 4 on Node 17+ (https://github.com/webpack/webpack/issues/14532). Let's see if the tests say...
If the tests are good, this also still needs a few small updates to docs.

Support volto 16 on Node 18

---

news/4924.bugfix
theme/themes/pastanaga/extras/blocks.less

Fix the experimental add new block button position, compensate the icon width (#4924)

---

news/4976.bugfix
src/components/theme/Login/Login.jsx
src/components/theme/Login/__snapshots__/Login.test.jsx.snap

(there was a React warning because of using the wrong case)

Fix password autocomplete hint on login form

---

news/4851.bugfix
packages/volto-slate/src/editor/plugins/StyleMenu/utils.js

fix(styleMenu): highlight selected block styles

---

news/5021.bugfix
src/reducers/actions/actions.js
src/reducers/actions/actions.test.js

Based on the work in #4946, this is a fix for 16 too.

Fix actions reducers for expanders in 16

---

news/5025.bugfix
src/components/manage/Controlpanels/Groups/RenderGroups.jsx
src/components/manage/Controlpanels/Groups/__snapshots__/RenderGroups.test.jsx.snap
src/components/manage/Controlpanels/Users/RenderUsers.jsx
src/components/manage/Controlpanels/Users/__snapshots__/RenderUsers.test.jsx.snap

fix: roles updation when username contains [dot] or email

---

news/5022.bugfix
src/components/manage/Widgets/SelectUtils.js

Fix: added fix for 'no value' entry select in table of content field

---

locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fi/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
locales/zh_CN/LC_MESSAGES/volto.po
news/5033.bugfix
src/actions/relations/rebuild.js
src/components/manage/Controlpanels/Relations/BrokenRelations.jsx
src/components/manage/Controlpanels/Relations/Relations.jsx
src/components/manage/Controlpanels/Relations/RelationsMatrix.jsx
src/helpers/MessageLabels/MessageLabels.js
src/reducers/relations/relations.js

Enhance display and repairing broken relations

---

news/5036.bugfix
src/components/manage/Blocks/Container/Edit.jsx
src/components/manage/Blocks/Container/EditBlockWrapper.jsx
src/components/manage/Blocks/Grid/Edit.jsx

Fix selecting the grid block when it contains other blocks

---

CHANGELOG.md
news/5068.documentation

Remove 302 redirect
See https://github.com/plone/documentation/pull/1522.

Fix linkcheck

---

news/5076.bugfix
src/server.jsx

Prevent caching the outdated browser message in a shared cache

---

locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fi/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
locales/zh_CN/LC_MESSAGES/volto.po
news/4855.bugfix
src/components/manage/Contents/ContentsPropertiesModal.jsx

Backport of https://github.com/plone/volto/pull/4857

Set contents property Exclude from navigation (16.x)

---

news/4984.bugfix
src/express-middleware/files.js
src/express-middleware/images.js

Add XSendfile headers to files and images middleware (16.x)

---

.github/workflows/docs.yml
news/5095.documentation
styles/Vocab/Plone/accept.txt

Before:
```
✖ 602 errors, 380 warnings and 1219 suggestions in 94 files.
```
After:
```
✖ 574 errors, 380 warnings and 1219 suggestions in 94 files.
```

Accept plone and volto in labels with janky regex

---

news/5101.bugfix
src/components/manage/Contents/Contents.jsx
src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap

Fix accessibility of the content folder buttons

---

news/5132.bugfix
packages/generator-volto/generators/app/templates/.storybook/main.js
packages/generator-volto/generators/app/templates/package.json.tpl

Fix storybook config for project generator. Add support for SCSS, upgrade to webpack 5 in there as well.

---

news/5018.bugfix
src/components/manage/Blocks/Image/View.jsx

This is the only PR that I think this is worth to backport from the list of remaining ones.

Add image block className support (Style wrapper). (#5018)

---

news/5151.bugfix
src/components/manage/Widgets/ArrayWidget.jsx
src/components/manage/Widgets/ArrayWidget.test.jsx
src/components/manage/Widgets/SelectWidget.jsx
src/components/manage/Widgets/SelectWidget.test.jsx
src/components/manage/Widgets/__snapshots__/ArrayWidget.test.jsx.snap
src/components/manage/Widgets/__snapshots__/SelectWidget.test.jsx.snap

Don't show ``No value`` option in SelectWidget and ArrayWidget if default value is 0

---

news/5161.bugfix
src/components/manage/Controlpanels/Rules/AddRule.jsx
src/components/manage/Controlpanels/Rules/EditRule.jsx

ContentRules add and edit forms for languages other than English

---

cypress/tests/core/blocks/blocks-search.js
news/5171.bugfix
news/5171.feature
src/components/manage/Blocks/Listing/withQuerystringResults.jsx

fix search block search results number

---

cypress/tests/core/basic/view.js
news/5149.feature

view cypress test

---

cypress/tests/core/blocks/blocks-listing.js
news/5173.bugfix

fixes https://github.com/plone/volto/issues/5173

Fix flaky cypress

---

locales/es/LC_MESSAGES/volto.po
news/5200.feature

maintenance: Updated Spanish translation

---

news/5264.bugfix
src/components/theme/Login/Login.jsx
src/components/theme/Login/Login.stories.jsx
src/components/theme/Logo/Logo.stories.jsx

fixes https://github.com/plone/volto/issues/5264

fix: logo and login storybook

---

news/5317.bugfix
src/components/manage/Widgets/QueryWidget.jsx

Allow multiple path criteria

---

addon-registry.js
news/5354.bugfix

Add support for TS files in add-on registry shadowing system

---

docs/source/conf.py
news/5378.documentation

Simplify linkcheck configuration with a regex

---

docs/source/contributing/version-policy.md
news/5404.documentation

Include mention of feature flag for UI changes

---

docs/source/blocks/settings.md
news/5410.documentation

This fixes a reference link to configuration/settings

Fix reference link to configuration/settings

---

news/5418.feature
src/components/theme/Sitemap/Sitemap.jsx

Use container from component registry in sitemap component and also refactor the class to functional component(#5418)

---

news/5433.feature
src/components/theme/ContentMetadataTags/ContentMetadataTags.jsx

Improvements and completeness of the ContentMetadataTags component

---

news/5444.internal
package.json
yarn.lock

See https://github.com/plone/volto/pull/5409#pullrequestreview-1749503196

Update yarnhook to 0.6.1 in order to support pnpm 8

---

src/components/theme/ContentMetadataTags/ContentMetadataTags.jsx

This reverts commit b3c6dd3bd336d6503561acdbe2de21674cca6379.

Revert "Improvements and completeness of the ContentMetadataTags component (#5433)"

---

docs/source/configuration/environmentvariables.md

Corrected the word deployments (was depoloyments) on line 52, file docs/source/configuration/environmentvariables.md.

Corrected the word deployments (was depoloyments) on line 52.

---

packages/generator-volto/README.md
packages/generator-volto/news/5480.documentation

See
- https://github.com/plone/volto/pull/5468#pullrequestreview-1759532550
- https://github.com/collective/cookiecutter-plone-starter/issues/111#issuecomment-1836828310
- https://github.com/plone/volto/pull/5465#pullrequestreview-1759199816

Replace table with link to documentation for compatibility

---

docs/source/addons/theme.md
packages/volto/news/5500.documentation
packages/volto/news/5504.documentation

Revert #5500. Sorry for the earlier false PR.

Revert #5500

---

news/5519.bugfix
src/components/manage/Sidebar/SidebarPopup.jsx

Fix this https://github.com/plone/volto/issues/5519

Fix sidebar popup click outside

---

news/5002.bugfix
src/components/manage/Widgets/RecurrenceWidget/EndField.jsx
src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx

Backport for Volto 17.x.x of https://github.com/plone/volto/pull/5002

fix: fixed utc problems in RecurrenceWidget

---

packages/volto/news/5501.bugfix
packages/volto/src/components/theme/Sitemap/Sitemap.jsx
packages/volto/src/components/theme/Sitemap/Sitemap.test.jsx
packages/volto/src/components/theme/Sitemap/__snapshots__/Sitemap.test.jsx.snap
packages/volto/src/config/index.js

Fixes #5501 
I also add a test for a sitemap in a multilingual site.

Fix sitemap for multilingual site

---

docs/source/blocks/block-style-wrapper.md
packages/volto/news/5591.documentation

Clarify how CSS properties work

---

Makefile
packages/volto/news/5596.documentation

Revert "Added Storybook to Netlify build to allow relative links from documen…"

---

Makefile
packages/volto/Makefile
packages/volto/news/5637.internal
variables.mk

I've been bitten by this today. Unifying.

Unify variables in Makefile

---

packages/volto/news/5655.documentation
requirements-docs.txt

After merging this PR, merge https://github.com/plone/volto/pull/5654

Temporarily pin `sphinxcontrib-*help` dependencies so docs can build

---

docs/source/index.md
packages/volto/news/5654.documentation

Before merging this PR, merge https://github.com/plone/volto/pull/5655 and update this PR against `main`.

Update ref from install-from-packages to create-project

---

packages/volto/news/5666.bugfix
packages/volto/src/components/manage/LinksToItem/LinksToItem.jsx
packages/volto/src/components/manage/LinksToItem/LinksToItem.test.jsx

Fix `/links-to-item` should be a protected route

---

locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
news/5682.bugfix

Not a backport directly since 16.x.x has problems that weren't found on main and 17.x.x branch

Removed git merge conflicts from french, english and brazilian volto po locale files

---

docs/source/robots.txt
netlify.toml
packages/volto/news/5725.documentation

See https://github.com/plone/documentation/issues/1619

Block search engines from indexing content on Netlify preview builds

---

docs/source/blocks/settings.md
packages/types/news/5718.bugfix
packages/types/src/config/Blocks.d.ts
packages/volto/news/5718.feature
packages/volto/package.json
packages/volto/src/components/manage/Add/Add.jsx
packages/volto/src/helpers/Blocks/defaultBlocks.test.js
packages/volto/src/helpers/Blocks/defaultBlocks.ts
packages/volto/src/helpers/index.js
pnpm-lock.yaml

Initial implementation, let's talk about your idea yesterday.

Support for passing whole data object in the initial block config

---

packages/registry/news/5726.bugfix
packages/registry/package.json
packages/registry/src/addon-registry.js
packages/registry/src/index.ts
pnpm-lock.yaml

Should fix: #5672
and superseed: https://github.com/plone/volto/pull/5712

Remove lodash as a dependency from @plone/registry

---

.eslintrc
news/5785.bugfix
package.json
packages/generator-volto/generators/addon/templates/.eslintrc
packages/generator-volto/generators/addon/templates/package.json
packages/generator-volto/news/5785.bugfix
yarn.lock

to fix ESLint couldn't determine the plugin "jsx-a11y"

Pin `eslint-plugin-jsx-a11y` to version `^6.7.0`

---

packages/volto/news/5796.bugfix
packages/volto/src/helpers/Blocks/Blocks.js

Enhance findBlocks to check for blocks in data for add-ons

---

docs/source/contributing/install-docker.md
packages/volto/news/5861.documentation

Supersedes and closes https://github.com/plone/volto/pull/5773.

Add reference to Docker installation for some Linux distributions

---

docs/source/blocks/settings.md
docs/source/configuration/settings-reference.md
packages/volto/news/5854.documentation

Update docs for defaultBlockType setting

---

locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fi/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
locales/zh_CN/LC_MESSAGES/volto.po
news/1868.bugfix
src/components/manage/Add/Add.jsx
src/components/manage/Edit/Edit.jsx
src/helpers/FormValidation/FormValidation.js
src/helpers/index.js

Show validation error message as string instead of list

---

docs/source/upgrade-guide/index.md
packages/volto/cypress/support/commands.js
packages/volto/cypress/support/helpers.js
packages/volto/cypress/tests/core/volto-slate/01-block-slate-title-description.js
packages/volto/cypress/tests/core/volto-slate/02-block-slate.js
packages/volto/cypress/tests/core/volto-slate/03-block-slate.js
packages/volto/cypress/tests/core/volto-slate/04-block-focus.js
packages/volto/cypress/tests/core/volto-slate/05-block-slate-format-basics.js
packages/volto/cypress/tests/core/volto-slate/06-block-slate-format-link.js
packages/volto/cypress/tests/core/volto-slate/07-block-slate-format-ulist.js
packages/volto/cypress/tests/core/volto-slate/08-block-slate-format-olist.js
packages/volto/cypress/tests/core/volto-slate/09-block-slate-slashmenu.js
packages/volto/cypress/tests/core/volto-slate/24-block-slate-format-boldlists.js
packages/volto/cypress/tests/core/volto-slate/25-block-slate-paste-images.js
packages/volto/cypress/tests/core/volto-slate/27-block-slate-paste-html.js
packages/volto/cypress/tests/core/volto-slate/28-table-block-slate-paste.js
packages/volto/news/5906.internal

I need this for the project-less setup.

Move testing-library cypress commands import to inner commands so it can be imported

---

packages/volto/news/5904.feature
packages/volto/src/components/theme/Comments/Comments.jsx
packages/volto/src/components/theme/Comments/__snapshots__/Comments.test.jsx.snap

Add id attributes to discussions container and individual comments

---

docs/source/contributing/style-guide.md
packages/volto/news/5903.documentation

After a chat with @sneridagh about Quanta, I took the information and updated the outdated page .

Update Docs: Pastanaga UI and Quanta

---

packages/volto/news/2927.bugfix
packages/volto/src/components/manage/Toolbar/PersonalTools.jsx
packages/volto/src/components/manage/Toolbar/__snapshots__/PersonalTools.test.jsx.snap

Fix broken link to portrait

---

packages/volto/news/5994.internal
packages/volto/src/components/theme/View/DefaultView.jsx

afaict it had translated messages in the past but now it doesn't

Cleaned up useless injectIntl in DefaultView

---

news/5994.internal
src/components/theme/View/DefaultView.jsx

afaict it had translated messages in the past but now it doesn't

Cleaned up useless injectIntl in DefaultView (v17)

---

news/6009.bugfix
src/components/theme/View/View.jsx
src/helpers/Api/Api.js
src/helpers/Api/Api.plone.rest.test.js
src/helpers/Api/Api.test.js

This reverts commit 15f342e92c10d9557296c7c468a09afd95924725.

Revert "Fix 301 and 302 redirects. (#6001)"

---

.readthedocs.yaml
packages/volto/news/6037.documentation

----
📚 Documentation preview 📚: https://volto--6037.org.readthedocs.build/

Build documentation and Storybook only when their files change

---

packages/volto/news/6040.bugfix
packages/volto/src/components/manage/Form/Form.jsx

Fixes #6040 
cc: @JeffersonBledsoe 
----
📚 Documentation preview 📚: https://volto--6041.org.readthedocs.build/

change relative import to alias import

---

packages/types/news/6049.bugfix
packages/types/src/config/Blocks.d.ts

----
📚 Documentation preview 📚: https://volto--6049.org.readthedocs.build/

[@plone/types] BlockExtension as Interface types

---

packages/types/news/6064.bugfix
packages/types/src/content/common.d.ts
packages/types/src/content/index.d.ts
packages/types/src/services/common.d.ts

----
📚 Documentation preview 📚: https://volto--6064.org.readthedocs.build/

Improved image typings

---

packages/scripts/i18n.cjs
packages/scripts/news/6073.bugfix

----
📚 Documentation preview 📚: https://volto--6073.org.readthedocs.build/

Fix `poToJson` script, making it support `volto.config.js`

---

packages/volto-slate/news/6080.bugfix
packages/volto-slate/src/utils/blocks.js

----
📚 Documentation preview 📚: https://volto--6080.org.readthedocs.build/

Fix deselecting lists.

---

docs/source/client/quick-start.md
packages/client/news/6076.documentation

Fixes #6076 
----
📚 Documentation preview 📚: https://volto--6077.org.readthedocs.build/

Add optional `token` parameter to ploneClient initialization

---

news/6101.bugfix
src/helpers/index.js

backport for volto 17 of #6100

backport #6100

---

packages/volto/Makefile

Descriptions and a thing for Windows. This is my review of the related PR #6104.
----
📚 Documentation preview 📚: https://volto--6107.org.readthedocs.build/

Renamemakefiletargets stevepiercy

---

.github/ISSUE_TEMPLATE/PLIP.md
packages/volto/news/6122.internal

----
📚 Documentation preview 📚: https://volto--6122.org.readthedocs.build/

Automatically set the label to `03 type: feature (plip)` for PLIPs

---

docs/source/upgrade-guide/index.md
packages/volto/news/5607.breaking
packages/volto/news/5607.feature

----
📚 Documentation preview 📚: https://volto--6125.org.readthedocs.build/

Image widget PR as breaking

---

.github/ISSUE_TEMPLATE/PLIP.md
packages/volto/news/6134.internal

See https://github.com/plone/Products.CMFPlone/pull/3984 and https://community.plone.org/t/plips-documentation/19609/15?u=stevepiercy
----
📚 Documentation preview 📚: https://volto--6134.org.readthedocs.build/

Automatically add the PLIP to the PLIP project board

---

news/4854.bugfix
src/components/theme/View/View.jsx
src/components/theme/View/View.test.jsx
src/helpers/Api/Api.js
src/helpers/Api/Api.plone.rest.test.js
src/helpers/Api/Api.test.js

Server-side redirects for plone.app.redirector aliases (v17)

---

.github/ISSUE_TEMPLATE/PLIP.md
packages/volto/news/6175.internal

See https://github.com/plone/documentation/pull/1671

Update the link to the new PLIP page

---

docs/source/development/i18n.md
packages/volto/news/6192.documentation

See #6188
----
📚 Documentation preview 📚: https://volto--6192.org.readthedocs.build/

Add a label and minor grammar fixes to i18n

---

docs/source/upgrade-guide/index.md
packages/volto/news/6189.breaking
packages/volto/news/6189.bugfix
packages/volto/news/6193.documentation

See #6189
----
📚 Documentation preview 📚: https://volto--6193.org.readthedocs.build/

Polish upgrade docs and news items for `SchemaWidget`

---

packages/coresandbox/src/components/Blocks/FormBlock/Data.tsx
packages/coresandbox/src/components/Blocks/FormBlock/Edit.tsx
packages/coresandbox/src/components/Blocks/FormBlock/View.tsx
packages/coresandbox/src/components/Blocks/FormBlock/schema.ts
packages/coresandbox/src/components/TestForm.jsx
packages/coresandbox/src/index.ts
packages/volto/cypress/tests/coresandbox/fieldTypeValidation.js
packages/volto/cypress/tests/coresandbox/formBlockValidation.js
packages/volto/cypress/tests/coresandbox/formFieldTypeValidation.js
packages/volto/news/6217.internal
packages/volto/src/helpers/FormValidation/FormValidation.test.js
packages/volto/src/helpers/FormValidation/validators.ts

Cypress test  for field types in :
----
📚 Documentation preview 📚: https://volto--6217.org.readthedocs.build/

Cypress Test for Validation of Field Types in CoreSandBox

---

packages/volto/cypress/tests/core/blocks/blocks-search.js
packages/volto/news/6226.bugfix

Add Cypress test for search block sort on property

---

packages/volto/news/6235.bugfix
packages/volto/src/components/theme/View/LinkView.jsx
packages/volto/src/components/theme/View/LinkView.test.jsx

Return 302 response from SSR link view for logged out users

---

docs/source/contributing/acceptance-tests.md
packages/volto/news/6239.documentation

----
📚 Documentation preview 📚: https://volto--6239.org.readthedocs.build/

Fix linkcheckbroken in docs

---

packages/volto-testing/package.json
packages/volto/news/6241.internal
packages/volto/package.json
pnpm-lock.yaml

Try to reduce the number of intermittent errors.

Upgrade Cypress to 13.13.2

---

docs/source/contributing/install-docker.md
packages/volto/news/6262.documentation

----
📚 Documentation preview 📚: https://volto--6262.org.readthedocs.build/

Fix redirect

---

packages/volto/news/5047.feature
packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx
packages/volto/src/components/manage/Contents/ContentsUploadModal.stories.jsx

Refactor Content upload modal 

---

packages/volto/locales/it/LC_MESSAGES/volto.po
packages/volto/news/ 6342.feature
packages/volto/news/+update_it.feature

https://github.com/plone/volto/pull/6340#discussion_r1777333114

Update Italian Italian translations. @gianniftp

---

docs/source/development/how-to-restrict-blocks.md

This is a follow up to my oversight in #6271, and as such does not need a changelog note or review.
----
📚 Documentation preview 📚: https://volto--6378.org.readthedocs.build/

Change formatting from blob of text to definition list.

---

docs/source/upgrade-guide/index.md
packages/volto/.eslintrc
packages/volto/news/6387.breaking
packages/volto/src/components/manage/Contents/Contents.jsx
packages/volto/src/components/manage/Controlpanels/DatabaseInformation.jsx
packages/volto/src/components/manage/Controlpanels/UpgradeControlPanel.jsx
packages/volto/src/components/manage/Controlpanels/Users/UserGroupMembershipMatrix.jsx
packages/volto/src/components/manage/Pluggable/Pluggable.test.js
packages/volto/src/components/manage/Sidebar/ObjectBrowserNav.jsx
packages/volto/src/components/manage/Toolbar/More.jsx
packages/volto/src/components/theme/Icon/Icon.stories.jsx
packages/volto/src/components/theme/Widgets/ArrayWidget.jsx
packages/volto/src/helpers/Html/Html.jsx

Added rule for ESlint to detect missing key property in iterators.

---

packages/volto/Makefile
packages/volto/news/6383.internal

Added missing improvement to the build-deps Makefile command

---

docs/source/development/i18n.md
packages/volto/news/6386.documentation

Closes https://github.com/eea/volto-accordion-block/issues/111#issuecomment-2319998378
----
📚 Documentation preview 📚: https://volto--6386.org.readthedocs.build/

Replace unhelpful words with helpful ones

---

.github/workflows/acceptance.yml
packages/volto/news/6418.internal

Remove last CI tests still in 18

---

packages/volto/news/6424.internal
packages/volto/src/start-server.js

Remove SEAMLESS mention in bootstrap

---

packages/volto/locales/de/LC_MESSAGES/volto.po

Add German translations for URL management control panel

---

packages/volto/news/6414.feature
packages/volto/news/6421.feature.1
variables.mk

Test with plone.restapi 9.8.0

---

.github/workflows/acceptance.yml
news/6432.internal

Volto 16: Update upload-artifact action to fix CI

---

docs/source/contributing/acceptance-tests.md
docs/source/development/i18n.md
docs/source/upgrade-guide/index.md

----
📚 Documentation preview 📚: https://volto--6439.org.readthedocs.build/

Fix broken links

---

docs/source/index.md
packages/volto/news/6438.documentation

See https://github.com/plone/documentation/issues/1740.
----
📚 Documentation preview 📚: https://volto--6438.org.readthedocs.build/

Rename page title from Frontend to Volto UI

---

packages/volto-slate/news/6444.bugfix
packages/volto-slate/src/editor/less/editor.less

Fix CSS lint in Volto Slate

---

packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
packages/volto/news/+update_pt_br.feature

Update pt_BR translation

---

packages/volto/locales/ro/LC_MESSAGES/volto.po
packages/volto/news/6454.feature
packages/volto/news/update_ro.feature

Update Romanian translation

---

packages/registry/docs/conceptual-guides/add-on-registry.md

This is a minor PR that is just housekeeping and not worth a change log entry. Will merge as soon as it's green.
----
📚 Documentation preview 📚: https://volto--6456.org.readthedocs.build/

Clean up add-on-registry.md docs

---

docs/source/tutorials/index.md

Another maintenance thing for YouTube redirects, which for some unknown reason started to 💩 the 🛏️ .
No changelog needed. Merge when green.

Fix redirects

---

docs/source/tutorials/index.md
packages/volto/news/6499.documentation

----
📚 Documentation preview 📚: https://volto--6499.org.readthedocs.build/

Add new Volto trainings to tutorials

---

locales/ca/LC_MESSAGES/volto.po
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/eu/LC_MESSAGES/volto.po
locales/fi/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/pt/LC_MESSAGES/volto.po
locales/pt_BR/LC_MESSAGES/volto.po
locales/ro/LC_MESSAGES/volto.po
locales/volto.pot
locales/zh_CN/LC_MESSAGES/volto.po
news/6533.bugfix
src/components/manage/Blocks/ToC/View.jsx
src/components/manage/Controlpanels/Controlpanels.jsx

Added missing translation string in table of contents block.
Added missing italian translations for volto 17.
PR for main branch coming asap.

Fixed italian i18n

---

docs/source/development/images.md
packages/volto/news/6552.documentation

----
📚 Documentation preview 📚: https://volto--6552.org.readthedocs.build/

Fix redirects to MDN responsive images

---

packages/volto/news/6572.bugfix
packages/volto/src/helpers/Robots/Robots.js

Fix robots.txt in devmode

---

.readthedocs.yaml
packages/volto/news/6612.internal

----
📚 Documentation preview 📚: https://volto--6612.org.readthedocs.build/

Restore pull request previews on Read the Docs

---

news/6616.feature
src/components/theme/AlternateHrefLangs/AlternateHrefLangs.jsx
src/components/theme/AlternateHrefLangs/AlternateHrefLangs.test.jsx
src/components/theme/View/View.jsx

-----
Same as #6603 for Volto 17.x

Alternate language links for Volto 17.x

---

.readthedocs.yaml
packages/registry/.readthedocs.yaml

This is a simple routine maintenance task that is not worthy of a changelog. Merging.

Linkcheck fixes

---

packages/volto/news/6631.bugfix
packages/volto/src/helpers/FormValidation/validators.ts

> [!CAUTION]
-----
-----
Fixes #6631

Ionlizarazu pattern validation message

---

.github/ISSUE_TEMPLATE/1_bug_report.md
.github/ISSUE_TEMPLATE/2_feature_request.md
.github/ISSUE_TEMPLATE/3_PLIP.md
.github/ISSUE_TEMPLATE/4_PLIP_task.md
packages/volto/news/6683.internal

We'll need to try each of them out after merge, and possibly revise.

Revise the existing issue templates and create a new one for PLIP tasks

---

.readthedocs.yaml
packages/volto/news/6684.internal

----
📚 Documentation preview 📚: https://volto--6684.org.readthedocs.build/
----
📚 Documentation preview 📚: https://plone-registry--6684.org.readthedocs.build/

Fix docs build in readthedocs

---

cypress/tests/coresandbox/fields.js
news/6570.bugfix
packages/volto-slate/src/blocks/Text/extensions/breakListInWidget.js
packages/volto-slate/src/blocks/Text/extensions/index.js
packages/volto-slate/src/blocks/Text/index.js
packages/volto-slate/src/widgets/HtmlSlateWidget.jsx
packages/volto-slate/src/widgets/RichTextWidget.jsx

> [!CAUTION]
-----
-----
Closes #

Volto 17 - fix add extensions in RichtextWidget refs#6570

---

.github/boring-cyborg.yml

- See broken example at https://github.com/plone/volto/pull/6748#issuecomment-2652342893
This PR does not need a changelog, as it's a follow up to #6613.

Attempt to fix PR admonition comment syntax

---

docs/source/blocks/block-style-wrapper.md

@sneridagh is it OK with you if I no longer include change log notes for linkcheck fixes? It would save me a good amount of time going forward, and I don't think anyone wants to read about them in the change log.
----
📚 Documentation preview 📚: https://volto--6758.org.readthedocs.build/

Fix redirect for MDN's Using CSS custom properties (variables)

---

packages/volto/news/6799.bugfix
packages/volto/src/components/theme/AlternateHrefLangs/AlternateHrefLangs.jsx
packages/volto/src/components/theme/AlternateHrefLangs/AlternateHrefLangs.test.jsx

Closes: https://github.com/plone/volto/issues/6602
PD: In Seven we won't have this any more (hopefully). We could backport the general solution in there to Volto as well.

Fix deployment issue, flattenToAppURL needed

---

Makefile
docs/source/conf.py
docs/source/configuration/internalproxy.md
docs/source/deploying/simple.md

----
📚 Documentation preview 📚: https://volto--6835.org.readthedocs.build/

Fix redirects and 404s

---

packages/volto/news/6845.bugfix
packages/volto/src/components/manage/Sidebar/ObjectBrowserNav.jsx
packages/volto/src/components/manage/Sidebar/ObjectBrowserNav.test.jsx
packages/volto/src/components/manage/Sidebar/__snapshots__/ObjectBrowserNav.test.jsx.snap

> [!CAUTION]
-----
-----
Closes #6845
Closes #5956

Fix error when saving content with ObjectBrowserNav open

---

packages/volto/locales/ca/LC_MESSAGES/volto.po
packages/volto/locales/de/LC_MESSAGES/volto.po
packages/volto/locales/en/LC_MESSAGES/volto.po
packages/volto/locales/es/LC_MESSAGES/volto.po
packages/volto/locales/eu/LC_MESSAGES/volto.po
packages/volto/locales/fi/LC_MESSAGES/volto.po
packages/volto/locales/fr/LC_MESSAGES/volto.po
packages/volto/locales/hi/LC_MESSAGES/volto.po
packages/volto/locales/it/LC_MESSAGES/volto.po
packages/volto/locales/ja/LC_MESSAGES/volto.po
packages/volto/locales/nl/LC_MESSAGES/volto.po
packages/volto/locales/pt/LC_MESSAGES/volto.po
packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
packages/volto/locales/ro/LC_MESSAGES/volto.po
packages/volto/locales/volto.pot
packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
packages/volto/news/6859.bugfix
packages/volto/src/components/manage/Blocks/Search/components/SearchInput.jsx
packages/volto/src/components/manage/Blocks/Search/components/__snapshots__/SearchInput.test.jsx.snap

Improved accessibility of the search button for the block input. An aria-label was added to the search button with the magnifying glass, and an aria-label was added to the cancel button with a new translation.

Aria label for search and cancel button for the input on search block

---

.github/workflows/docs-rtd-pr-preview-registry.yml
.github/workflows/docs-rtd-pr-preview-volto.yml
.readthedocs.yaml
README.md
packages/volto/news/6876.internal

@sneridagh @pnicolli let's see if this fixes it.

Enabled docs builds on 18.x.x

---

.github/workflows/stale-items.yml
packages/volto/news/6875.internal

Copy pasted from the wrong example, put the action file in the wrong place :)
Also changed from 1000 items to 50 in order to avoid spamming too many people in the first runs when it checks a lot of items.

Moved new workflow action to the correct folder

---

packages/volto/news/6879.bugfix
packages/volto/src/components/manage/Widgets/ImageWidget.jsx

prevent submit form from ImageWidget buttons

prevent submit form from ImageWidget

---

docs/source/contributing/developing-core.md
packages/client/README.md
packages/client/news/6894.documentation
packages/volto/news/6894.documentation

----
📚 Documentation preview 📚: https://volto--6894.org.readthedocs.build/

Revert reformating and clean up client README.md #6889

---

packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
packages/volto/news/6833.bugfix
packages/volto/src/components/manage/Form/Form.jsx
packages/volto/src/helpers/FormValidation/FormValidation.jsx
packages/volto/src/helpers/FormValidation/FormValidation.test.js

Backport (#6834)

---

packages/client/news/+fix_client_test.bugfix
packages/client/src/restapi/types/get.test.ts
packages/client/src/restapi/types/update_type_field.test.ts

No clue why this was broken...

Fix client test in types endpoint

---

PACKAGES.md
apps/seven/news/+fewdocs_amendment.documentation
docs/source/contributing/developing-core.md

@stevepiercy not a big deal, I merged the changes from `main` and amended some things for Seven.

Amend a few docs

---

docs/source/_inc/_hardware-requirements.md

This is a follow up to https://github.com/plone/volto/pull/6918#pullrequestreview-2728646024, so no change log entry is needed.
----
📚 Documentation preview 📚: https://volto--6925.org.readthedocs.build/

s/Seven/Volto on `main`

---

packages/volto/news/6930.bugfix
packages/volto/package.json
pnpm-lock.yaml

See: https://github.com/storybookjs/storybook/issues/31026

Fixed regression on brown bag minor version of `@storybook/addon-webpack5-compiler-babel`

---

packages/components/news/6928.documentation
packages/components/src/stories/TailwindComponents.mdx
packages/components/src/tailwind/Container/Container.stories.tsx

Storybook for `Container` component

---

docs/source/backend/index.md
docs/source/development/overview.md
docs/source/tutorials/index.md
docs/source/user-manual/index.md
packages/components/README.md

No change log entry needed, as this is routine maintenance.
----
📚 Documentation preview 📚: https://volto--6953.org.readthedocs.build/

Update or remove broken links

---

packages/volto/cypress/tests/core/basic/recurrence-widget.js
packages/volto/news/6971.internal

Backport of #6971 to Volto 18
> [!CAUTION]
-----
-----
Closes #

Fix Cypress "Test Yearly recurrence" test

---

Makefile
packages/volto/news/6975.internal

> [!CAUTION]
-----
-----
Closes #

Remove make command whose packages no longer exist

---

Makefile
packages/volto/news/6975.internal

Backport of #6975 to Volto 18
> [!CAUTION]
-----
-----
Closes #

Remove make command whose packages no longer exist (#6975)

---

apps/nextjs/README.md
docs/source/conf.py
docs/source/development/add-ons/test-add-ons-18.md
docs/source/development/i18n.md
docs/source/development/images.md
docs/source/release-notes/index.md
packages/volto/CHANGELOG.md

I'll merge this as soon as it's green. It doesn't need a change log entry because it's just fixing redirecting links.

Linkcheck 2025 04 22

---

packages/volto/news/7015.documentation
requirements-docs.txt

See https://github.com/plone/Products.CMFPlone/issues/4097
----
📚 Documentation preview 📚: https://volto--7015.org.readthedocs.build/
----
📚 Documentation preview 📚: https://plone-registry--7015.org.readthedocs.build/

Pin plone-sphinx-theme to prepare for PLIP 4097

---

docs/source/contributing/redux.md
packages/volto/news/7023.documentation

----
📚 Documentation preview 📚: https://volto--7023.org.readthedocs.build/

Better Redux-related docs, word wrapping

---

docs/source/upgrade-guide/index.md
packages/volto/news/7027.documentation

> [!CAUTION]
-----
-----
Closes https://github.com/plone/documentation/issues/1947
----
📚 Documentation preview 📚: https://volto--7027.org.readthedocs.build/

documentation for gridBlock upgrade guide

---

packages/volto/locales/ca/LC_MESSAGES/volto.po
packages/volto/locales/de/LC_MESSAGES/volto.po
packages/volto/locales/en/LC_MESSAGES/volto.po
packages/volto/locales/es/LC_MESSAGES/volto.po
packages/volto/locales/eu/LC_MESSAGES/volto.po
packages/volto/locales/fi/LC_MESSAGES/volto.po
packages/volto/locales/fr/LC_MESSAGES/volto.po
packages/volto/locales/hi/LC_MESSAGES/volto.po
packages/volto/locales/it/LC_MESSAGES/volto.po
packages/volto/locales/ja/LC_MESSAGES/volto.po
packages/volto/locales/nl/LC_MESSAGES/volto.po
packages/volto/locales/pt/LC_MESSAGES/volto.po
packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
packages/volto/locales/ro/LC_MESSAGES/volto.po
packages/volto/locales/ru/LC_MESSAGES/volto.po
packages/volto/locales/volto.pot
packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
packages/volto/news/6964.feature
packages/volto/src/components/manage/Contents/ContentsDeleteModal.jsx

Backport 6964

---

.pnpmfile.cjs
apps/seven/news/7065.internal.1
apps/seven/news/7065.internal.2
catalog.json
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Eventually people implement things that we need :) 
Simple and harmless :) This one will be paired with a config in CookieSeven template

Load catalog versions from `catalog.json`

---

packages/scripts/news/7068.feature
packages/scripts/prepublish.js

Support not publishing a package on NPM if plonePrePublish.publish is set to false

---

packages/volto/news/7073.feature
packages/volto/src/components/manage/Add/Add.jsx

> [!CAUTION]
-----
-----
Closes #

Add component accept an optional initialFormData prop

---

packages/volto/news/7083.feature
packages/volto/src/components/manage/Widgets/SelectWidget.jsx

Backport #7084

---

packages/volto-slate/news/7090.feature
packages/volto-slate/src/blocks/Table/TableBlockView.jsx
packages/volto/news/7090.bugfix
packages/volto/theme/themes/pastanaga/collections/table.overrides

Backport  of https://github.com/plone/volto/pull/6358

Backport 6358 to Volto 18

---

packages/cmsui/components/Sidebar/Sidebar.tsx
packages/cmsui/news/7126.bugfix
packages/cmsui/routes/layout.tsx

> [!CAUTION]
-----
-----
Closes #
----
📚 Documentation preview 📚: https://volto--7126.org.readthedocs.build/
----
📚 Documentation preview 📚: https://plone-registry--7126.org.readthedocs.build/

fix: seven sidebar

---

apps/seven/app/root.tsx
apps/seven/news/7140.bugfix
packages/helpers/news/7140.bugfix
packages/helpers/package.json
packages/helpers/src/flattenToAppURL.test.ts
packages/helpers/src/flattenToAppURL.ts
pnpm-lock.yaml

----
📚 Documentation preview 📚: https://plone-registry--7140.org.readthedocs.build/

[Seven] Fix flattenToAppURL

---

packages/volto/locales/ca/LC_MESSAGES/volto.po
packages/volto/locales/de/LC_MESSAGES/volto.po
packages/volto/locales/en/LC_MESSAGES/volto.po
packages/volto/locales/es/LC_MESSAGES/volto.po
packages/volto/locales/eu/LC_MESSAGES/volto.po
packages/volto/locales/fi/LC_MESSAGES/volto.po
packages/volto/locales/fr/LC_MESSAGES/volto.po
packages/volto/locales/hi/LC_MESSAGES/volto.po
packages/volto/locales/it/LC_MESSAGES/volto.po
packages/volto/locales/ja/LC_MESSAGES/volto.po
packages/volto/locales/nl/LC_MESSAGES/volto.po
packages/volto/locales/pt/LC_MESSAGES/volto.po
packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
packages/volto/locales/ro/LC_MESSAGES/volto.po
packages/volto/locales/ru/LC_MESSAGES/volto.po
packages/volto/locales/volto.pot
packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
packages/volto/news/7174.bugfix
packages/volto/src/components/theme/View/FileView.jsx

Add a default if there is an empty filename string.
Closes #7174

add default if no filename is supplied in FileView

---

packages/volto/news/7184.feature
packages/volto/package.json
packages/volto/src/actions/users/users.js
pnpm-lock.yaml

> [!CAUTION]
-----
-----
Closes plone/cookieplone-templates#236
-----
If your pull request includes changes to the documentation—either in narrative documentation, Storybook, or configuration—then a pull request preview will be generated and a link will populate in the description of your pull …

Synchronizes versions of Volto dependencies with other packages in the monorepo

---

packages/volto/locales/ca/LC_MESSAGES/volto.po
packages/volto/news/7209.feature

> [!CAUTION]
-----
-----
Closes #
-----
If your pull request includes changes to the documentation—either in narrative documentation, Storybook, or configuration—then a pull request preview will be generated and a link will populate in the description of your pull request below.
By clicking that …

Update Catalan translations in volto.po for various components and messages

---

docs/source/configuration/settings-reference.md
packages/components/.readthedocs.yaml
packages/layout/.readthedocs.yaml
packages/volto/news/6549.breaking
packages/volto/src/config/index.js

Fixes #6549
----
📚 Documentation preview 📚: https://volto--7212.org.readthedocs.build/

Enable showRelatedItems by default in Volto 19

---

packages/components/src/index.ts
packages/components/src/styles/basic/Sitemap.css
packages/layout/.storybook/preview.ts
packages/layout/components/Sitemap/Sitemap.stories.tsx
packages/layout/components/Sitemap/Sitemap.test.tsx
packages/layout/components/Sitemap/Sitemap.tsx
packages/layout/styles/main.css
packages/publicui/index.ts
packages/publicui/package.json
packages/publicui/routes/index.tsx
packages/publicui/routes/sitemap.tsx
packages/theming/styles/main.css
packages/theming/styles/typography.css
pnpm-lock.yaml

Sneridagh seven sitemap

---

packages/components/news/7236.feature
packages/components/src/components/Container/Container.quanta.tsx
packages/components/src/components/Container/Container.stories.tsx
packages/components/src/components/Container/Container.tsx
packages/components/src/styles/basic/Container.css
packages/theming/news/7236.feature
packages/theming/styles/main.css

@pnicolli heads up, I changed the order of the utilities layer, to be behind the plone-components one.

Unify Container props

---

packages/volto/news/7240.bugfix
packages/volto/src/components/manage/UniversalLink/UniversalLink.tsx

Regression since Volto 18.19.0

Pass on onClick to Link component in UniversalLink

---

packages/volto/news/7240.bugfix
packages/volto/src/components/manage/UniversalLink/UniversalLink.tsx

forward Port for #7242 done for 18.x.x branch

Pass on onClick to Link component in UniversalLink (#7240)

---

docs/source/development/widget.md
packages/volto/news/7261.documentation

----
📚 Documentation preview 📚: https://volto--7261.org.readthedocs.build/

Fix widget reference in schema for boolean fields toggle_widget

---

packages/volto/news/7244.bugfix
packages/volto/src/config/ControlPanels.js

> [!CAUTION]
-----
-----
Closes #7244 
-----
If your pull request includes changes to the documentation—either in narrative documentation, Storybook, or configuration—then a pull request preview will be generated and a link will populate in the description of your pull request below.
By clicking …

Hide the webstats_head_js in site control panel (18.x.x)

---

packages/volto/news/7254.internal
packages/volto/package.json
pnpm-lock.yaml

(Backport 18.x.x) update eslint-config-version

---

packages/volto/cypress/tests/core/blocks/listing/blocks-listing.js
packages/volto/news/7286.internal

Fixes random error in Listing Block tests

---

packages/volto/cypress/tests/core/blocks/blocks-indexing.js
packages/volto/news/7304.internal

Fixed random failure in Cypress 'Index Text Block' test

---

packages/volto/news/7271.bugfix.md
packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx

This is a forward port from my PR #7272 (18.x.x) to the main branch.  All commits squashed into one. This fixes issue #7271 for the main branch.

Search block: fix 'Clear filters' overriding the base query. [main]

---

packages/volto/news/7271.bugfix.md
packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx

Search block: fix 'Clear filters' overriding the base query.

---

.github/workflows/readme-link-check.yml
apps/rr7/README.md
packages/volto/README.md
packages/volto/news/7378.internal

See https://github.com/collective/awesome-volto/pull/42.
Will back and forward port to `18.x.x` and `seven` after this is merged.

Replace readme link checker of awesome_bot with Lychee

---

packages/volto/news/7396.bugfix
packages/volto/src/components/manage/Controlpanels/ContentType.jsx

Check if we are editing a content type before rendering the Content Type control panel form

---

docs/source/upgrade-guide/index.md
packages/volto/news/7402.breaking

----
📚 Documentation preview 📚: https://volto--7402.org.readthedocs.build/

Upgrade note to replace `<img>` tags with `Image` component and introduce ESLint rule

---

.github/workflows/acceptance.yml
news/7421.bugfix

Fix project generator test on Node 16

---

packages/volto/news/+button.bugfix
packages/volto/src/components/manage/Widgets/InternalUrlWidget.jsx
packages/volto/src/components/manage/Widgets/ObjectBrowserWidget.jsx
packages/volto/src/components/manage/Widgets/UrlWidget.jsx
packages/volto/src/components/manage/Widgets/__snapshots__/ObjectBrowserWidget.test.jsx.snap
packages/volto/src/components/manage/Widgets/__snapshots__/UrlWidget.test.jsx.snap

Similar to https://github.com/plone/volto/pull/6791

Add type=button to more widget buttons

---

apps/seven/news/+monorepodocs.documentation
docs/conceptual-guides/add-on-driven-configuration.md
docs/conceptual-guides/add-on-registry.md
docs/conceptual-guides/cookieplone-frontend-add-on.md
docs/conceptual-guides/cookieplone-frontend-addon.md
docs/conceptual-guides/index.md
docs/reference/conventions.md

----
📚 Documentation preview 📚: https://volto--7441.org.readthedocs.build/

Monorepodocs

---

packages/layout/components/Image/Image.tsx
packages/layout/news/+imagetypes.bugfix

----
📚 Documentation preview 📚: https://volto--7459.org.readthedocs.build/

[Seven] Fixed image component types

---

packages/scripts/lockhook.js
packages/scripts/news/7462.internal
packages/scripts/package.json
pnpm-lock.yaml

Backport of https://github.com/plone/volto/pull/7435

[18]chore(@plone/scripts): upgrade execa to avoid security vulnerability

---

packages/volto/theme/themes/pastanaga/extras/main.less

Reverts plone/volto#7456 See #7419

Revert "Add underline to formtabs items for proper link identification (#7419)"
