plone/volto

src/components/manage/Widgets/TextWidget.jsx
Looks like that this component sometimes receive a string (for title field for example), and sometimes an object (for rich text field)
=> fix widget proptypes for value

docs/create_example.txt, docs/introduction.md, docs/manage.md, docs/mosaic.md, docs/theme.md, package.json, src/components/manage/Widgets/WysiwygWidget.jsx, src/components/theme/Footer/Footer.md, src/components/theme/Header/Header.md, src/components/theme/Login/Login.md, src/components/theme/Logo/Logo.md, src/components/theme/Search/Search.md, src/components/theme/SearchWidget/SearchWidget.md, src/components/theme/Title/Title.md, styleguide.config.js
I've added one main file in markdown for each group, some examples (code showcase and live example) for some of theme's components.
Some live examples doesn't work yet, for some obscure reason related to `reduxAsyncConnect`.
The file `docs/create_example.txt` is kind of a _how to_ file about example.
=> Component documentation with examples

api/buildout.cfg, api/requirements.txt
Pin Plone version and use plone.restapi release. Pin plone.app.event and plone.namedfile to make buildout work.
=> CI needs to be stable. 

src/routes.jsx
I had to do that in the other project as well. The route for the root didn't match the root views.
=> Fix contents/add/sharing at Plone site root.

api/buildout.cfg, api/docker/requirements.txt
It seems that we don't have to override so many pins from Plone.
This also fixes the double buildout `extensions` so that mr.developer works.
=> Fix mr.developer, remove unnecessary pins

.gitattributes, CHANGELOG.md
I've seen merge conflicts in Changelog files in pull requests and I figured we might as well use the same strategy we use with plone packages: setting gitattributes to use the `union` style for merging the Changelog file. What do you think about it?
Quick article for reference: http://krlmlr.github.io/using-gitattributes-to-avoid-merge-conflicts/
=> Add .gitattributes file to avoid most Changelog merge conflicts

.eslintrc, CHANGELOG.md, razzle.config.js, src/components/theme/View/View.jsx, src/config/Views.jsx, src/config/index.js, src/helpers/Api/Api.js, tsconfig.json
- work with mr.developer
- add alias to `@plone/volto-original` to be able to reimport overridden components
- add alias to `@package` for current dev package to be able to import modules in the current project from customizations folder
- be able to override error views based on status code of error message(previously only had 404 view)
=> Integration improvements

CHANGELOG.md, theme/themes/pastanaga/globals/site.overrides
=> Set image width in Volto editor to 50% for images that float left/right.

CHANGELOG.md, theme/themes/pastanaga/extras/main.less
Fix for this issue: https://github.com/plone/volto/issues/703
=> fix: first characters in title tile are not clickable

CHANGELOG.md, src/helpers/Api/Api.js
This exposes the superagent request on the promise returned by the api helper/actions.
When you use a action that sends many requests in order and expects the result of the latest request that has a successful response in the redux store this is not guaranteed. 
An example is a type ahead search. The @search requests take various amounts of time and don't come back in order. If you type a search for "foo bar" the response for "foo bar" might be earlier than the response for "foo". So you might up with having the results for foo in the store while the frontend input contains "foo bar".
With this change a component that calls an action like searchContent repeatedly can abort every previous search request before it sends a new one to make sure the result for the latest action will end up in …
=> Attach request to api promise

CHANGELOG.md, src/components/theme/ContactForm/ContactForm.jsx
ContactForm.onSubmit() passed the data to emailNotification() in the wrong order.
=> Fix order of arguments when calling the emailNotification action

CHANGELOG.md, src/components/manage/Tiles/Tile/Edit.jsx, src/config/Tiles.jsx, src/config/index.js
Fixes #205 
Added a `requiredTiles` global configuration.
The delete button will not be shown if the current tile is in that list of required tiles.
I could have just checked for the `title` tile instead of creating a configuration option, I can change it to that if you prefer.
I created this because in #205 one idea for the future was "what if we had required tiles based on the content type?". The implementation I propose here allows for that by simply changing the `requiredTiles` array to a function returning an array, for example, or a simple object or whatever will be the best way to represent required tiles.
=> Removed the delete button from the title tile

.travis.yml
do not double up builds on every change
=> be nice to travis

CHANGELOG.md, theme/themes/pastanaga/extras/tiles.less
Tiles in the Pastanaga Editor have a light blue outline placed on an `::after` pseudo-element. This actually creates an element floating above the tile, not allowing clicks on the tile content unless we place the tile above this element with CSS tricks (`position: relative` and/or `z-index`).
This small fix aims to place the outline below the tile content, while keeping its aspect unchanged.
I have tested it with the following tiles:
- Title
- Summary
- Text
- HTML
- Map
- Image
- Video
- Hero
=> Fixed tiles outline in pastanaga editor

CHANGELOG.md, src/components/theme/Search/Search.jsx, src/components/theme/Search/SearchTags.jsx
* Fix parameter handling in Search view #845 
* Fix keywords vocabulary condition in SearchTags
Still does double @search requests when you type in another search term after the Search view was mounted.
=> Fix searching for tags

CHANGELOG.md, src/components/manage/Form/Form.jsx
As shown in https://github.com/plone/volto/issues/933, it's currently possible to submit a required form field with just whitespace as the data, causing the front-end to crash. While there probably should be a way to fail more gracefully if a form was submitted with erroneous data, this PR should at least solve this situation.
As an aside, it would be great to have a method of failing gracefully when running Volto in develop mode, such as showing the backend error message to the developer, rather than just showing where React crashed.
=> Trim whitespace of form fields on form submission

CHANGELOG.md, src/components/manage/Widgets/QuerystringWidget.jsx
Small fix to add a missing map() key.
=> Avoid console warnings in QuerystringWidget

CHANGELOG.md, package.json, src/components/manage/Blocks/Text/Edit.jsx, yarn.lock
This makes it possible to paste links into the normal text-blocks. All other styling is still stripped.
=> enable to paste links into textfields

CHANGELOG.md, src/components/manage/Blocks/Text/Edit.jsx
b,i,ul and ol Elements are maintained when pasted into normal textblocks. Headings and most stuff is disabled due to very inconsistent behaviours.
=> maintain some styling when pasting

CHANGELOG.md, src/components/manage/Form/Form.jsx
The ``blocks`` and ``blocks_layout`` fields are visible in the Add/Edit form of content that has the Pastanaga editor enabled. These fields should not be visible there, because they are used and modified by the Pastanaga editor itself.
=> Hide Blocks fields in Layout fieldset in Add/Edit form

CHANGELOG.md, README.md
I've added the newly published forest.eea.europa.eu/ to Volto production websites.
=> Added FISE website as deployed Volto in production

CHANGELOG.md, src/components/manage/Display/Display.jsx, src/components/manage/Toolbar/More.jsx, src/components/manage/Toolbar/Toolbar.jsx, src/components/theme/View/View.jsx
This way we are offering a better user experience, imho.
Is this something you would be interested into?
The way it's implemented, they automatically show up when you configure a component to render that view. Also tested with sites created with ``create-volto-app``.
=> In the Display menu, only show views that are implemented

.travis.yml
The Guillotina tests started to fail on Travis without any change in the repository. I have no idea what's wrong or how to fix it. In order to being able to move on we have to disable the Guillotina tests for now.
I re-ran the last master build that was green to prove something outside the code repo must have changed to make the build fail.
After re-running
https://travis-ci.org/plone/volto/jobs/650499720
the build was red.
=> Disable Guillotina tests on Travis.

.travis.yml, CHANGELOG.md, g-api/config.yml, g-api/docker-compose.yml
The problem was that postgres docker maintainers decided to change the image forcing that now a password is needed. Just forced an old version of postgres makes it work again.
=> fix(Guillotina) Fixing travis tests on Guillotina backend

CHANGELOG.md, theme/themes/pastanaga/collections/table.overrides
Reverts plone/volto#1216 because it breaks the layout for table blocks.
=> Revert "Table Content: Fix content overflow"

CHANGELOG.md, src/components/theme/OutdatedBrowser/OutdatedBrowser.jsx
Fixes issue were SSR rendered page version could not be loaded with `curl`, `lynx`, `elinks`, because browser detect returned null.
=> Fix SSR for "undetected" browsers [fixes #1262]

CHANGELOG.md, src/components/theme/View/EventView.jsx, src/components/theme/View/EventView.test.jsx, src/components/theme/View/NewsItemView.jsx, src/components/theme/View/NewsItemView.test.jsx, src/components/theme/View/__snapshots__/EventView.test.jsx.snap, src/components/theme/View/__snapshots__/NewsItemView.test.jsx.snap, src/helpers/Url/Url.js, src/helpers/Url/Url.test.js, src/helpers/index.js
Internal links in rich text fields are converted by restapi with the backend url.
This means that Volto then expose links to the backend Plone site.
With this change all references to api url are cleaned.
I didn't find a better way to do this in general and not in every single view.
=> Convert api url in rich text

CHANGELOG.md, package.json
This fixes tests fail when it found the Plone JS resources in `api` folder.
=> Make Jest only looks up in `src` folder

CHANGELOG.md, src/components/manage/Form/Form.jsx, src/components/theme/ContactForm/ContactForm.jsx
Submitting the contact form I had errors in the frontend and the form went broken.
I resolved the issue with an error boundary that is the `?` in ```formData[blocksLayoutFieldname]?.items```
I also saw that the success toast for the form was broken due to an incorrect id for the translation, so I picked up the correct one.
=> Fixes for contact form

CHANGELOG.md, src/components/manage/Widgets/DatetimeWidget.jsx, theme/themes/pastanaga/extras/react-dates-overrides.less, theme/themes/pastanaga/extras/time-picker-overrides.less
Fixes #1391 .
Shown past dates in calendar and added a prop to hide past dates in calendar (false as default).
I also marked default date vs edited because in CT dates like expire date should be visible as non saved value (so now it's grey).
=> Dates widget: show past dates and mark differently default value

CHANGELOG.md, src/components/manage/Blocks/Listing/ListingBody.jsx, src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
Removed message for 'no results found' in view component of ListingBody for Listing block. 
On the public site it's not always nice to see the message 'no results found'.
=> No listing results

CHANGELOG.md, src/config/RichTextEditor/ToHTML.jsx
Fixes #1440 .
Now with '_blank' as default value for `target` attribute, external links are opening in a new tab, while internal ones are rendered by Link component as before.
=> fix: handling target for external links

CHANGELOG.md, razzle.config.js
So this is it.
I couldn't made it work with bare Volto, I have no clue why... but it works in a standard Volto project... I guess that's where it counts 😀😀
package.json
```json
...
"addons": [
"volto-myaddon"
]
...
```
So it's left the config aggregator and what else?
=> Add babel and externals support in Webpack for add-on infrastructure

CHANGELOG.md, theme/themes/pastanaga/extras/contents.less
=> fix overflow in contents with long titles

CHANGELOG.md, src/components/manage/Sidebar/ObjectBrowser.jsx, src/components/manage/Sidebar/ObjectBrowserBody.jsx, src/components/manage/Sidebar/ObjectBrowserNav.jsx, src/components/manage/Sidebar/ObjectBrowserNav.test.jsx, src/components/manage/Sidebar/__snapshots__/ObjectBrowserNav.test.jsx.snap, src/components/manage/Widgets/ObjectBrowserWidget.jsx
if in content schema are defined some selectableTypes for a specific field (in widgetOptions.patterns_options), the objectBrowser allows to select only elements of those types
=> selectableTypes in ObjectBrowserWidget

CHANGELOG.md, src/components/manage/Toolbar/Types.jsx
If the config setting isMultilingual is true it does not mean all content types are marked as translatable. In those case the resonse lacks the component "translations".
=> Fix add content dropdown if a type is not translatable

CHANGELOG.md, docs/mkdocs.yml, docs/source/customizing/express.md, src/config/index.js, src/server.jsx
Simple server.use() call for custom middleware. I've also added a doc.
@tisto fortunately no dedicated server module is needed, I was able to use ``__SERVER__`` to conditionally load the server code. All explained in the new doc.
=> Load custom express middleware

CHANGELOG.md, package.json, yarn.lock
I've used `yarn audit --level high` and it complained about a couple of packages. I know that we use http-proxy-middleware, but what do we need handlebars as dependency?
=> Upgraded unsecure packages to pass yarn audit --level high

CHANGELOG.md, theme/themes/pastanaga/extras/toolbar.less
If page title was too long, it overflowed from the menu.
Fixed:
=> fix text overflow in pastanaga-menu header if title is too long

CHANGELOG.md, src/components/manage/Form/Field.jsx
if field has property mode setted to 'hidden' (from plone), the field is not rendered.
=> managed hidden fields

CHANGELOG.md, __tests__/create-addons-loader.test.js, addon-registry.js, create-addons-loader.js
Fixed a bug with @ in package name. Now you can use namespace packages.
The configuration is like this:
- in `package.json` use the package name in the 'addons' key. So, `addons: ['@kitconcept/volto-form-builder']`
- in `mrs.developer.json` need to add the `package` property, like:
```
{
"volto-form-builder": {
"package": "@kitconcept/volto-form-builder",
"local": "../../"
}
}
```
Beware, the `local` path, if testing with local checkouts, needs to be relative to the `src` folder in the Volto project. And right now only `src` is supported, as this error I got from razzle tells us:
```
ERROR  Your project's `baseUrl` can only be set to `src` or `node_modules`. Razzle does not support other values at this time.
```
=> Fix bug with namespace packages; cleanup some code

CHANGELOG.md, package.json, yarn.lock
Just a bump, minor fixes.
I've pinned razzle to `^3.1.5`, from `3.1.2`. It's not clear to me if Volto's dependencies should be pinned to absolute versions or we can use semantic versioning. See also https://github.com/plone/volto/pull/1444
=> Upgrade razzle to latest release

CHANGELOG.md, docs/source/upgrade-guide/index.md, razzle.config.js
This is just a convenience alias to make some bits nicer in `theme.config`.
So instead of having:
```
/* Path to theme packages */
@themesFolder : '../../node_modules/@plone/volto/theme/themes';
/* Path to site override folder */
@siteFolder  : "../../theme";
```
We can have:
```
/* Path to theme packages */
@themesFolder  : '~volto-themes'
/* Path to site override folder */
@siteFolder  : '~@package/../theme';
```
For the first one, themesFolder, it's a matter of cosmetics. The second one will make it easier for people new to Volto to understand which path it's about.
I'm also recommending to move themes to their own folder, to prepare for the addition of addon theming, so you could override an addon theme.
=> Provide a new webpack alias that makes it easier to reference Volto themes folder

CHANGELOG.md, src/components/manage/Contents/Contents.jsx
Solved https://github.com/plone/volto/issues/1695.
`mini` was used from the context. There also is another issue that makes the modals be displayed with a wrong position (not centered, the problem seems to be in `modal.less`).
=> Solved the issue 1695: console error in /contents view

CHANGELOG.md
The entry for the recurrence widget is gone under 6.5.0 release in the changelog, but that’s not correct
=> Fix changelog for recurrence widget entry

CHANGELOG.md, src/components/manage/Form/Form.jsx
The stuff this supposedly fixed wasn't even broken in the current volto build. So I removed it again.
=> remove componentWillReceiveProps from Form again

CHANGELOG.md, docs/source/customizing/add-ons.md
- Clear separation of "Use of an addon" and "Creating an addon".
- Changed order to first "Use of an addon" then "Creating an addon".
=> How to use an addon

CHANGELOG.md, src/components/manage/Form/Form.jsx
How to reproduce, before & after:
- Create two empty text blocks, one after the other
- In the first text block, change the type to "image"
- Before this PR, you'd now have three blocks: image block + two empty text blocks
- After this PR, you now have two blocks: image block + empty text block
It needs a Cypress test, but I can't run Cypress right now.
=> On mutating block, don't create placeholder block if already exists

CHANGELOG.md, src/components/manage/Toolbar/Types.jsx
In folders not under the root, the add links were generated like https://volto.kitconcept.com/news2/contents/add?type=News%20Item
=> Fix cosmetic issue, wrong Add link generated in Contents page

CHANGELOG.md, theme/themes/pastanaga/elements/input.overrides
Fixes checkbox widget in forms:
Before:
Now:
=> fix: checkbox widget styles

CHANGELOG.md, src/components/manage/Form/Form.jsx, src/config/index.js, theme/themes/pastanaga/extras/main.less
By default, forms are displayed with horizontal tab at the top.
If you have a content type with a lot of tab, the horizontal arrangement fails to contain them all.
You could define, in config.js to display form tab as a vertical list in all your project, changing the variabile `verticalFormTabs` to true.
=> Vertical form tabs

CHANGELOG.md, __tests__/fixtures/test-volto-project/package.json, addon-registry.js
A regression bug introduced in #1706 meant that customization paths that end with a slash, like `src/customizations/`, no longer worked. This fixes it.
=> Fix customization mechanism when paths end with a slash

CHANGELOG.md, src/components/manage/Blocks/Block/Edit.jsx
Appears to be a regression somewhere.
=> Fix bug in auto select sidebar tab by block, on mount

CHANGELOG.md, src/components/manage/Widgets/SelectWidget.jsx
Allow select widget to reset when the incoming props change. The react-select widget has its own internal state, so if you initialise the widget without choices, then populate the choices, it wouldn't properly show the default value (which is the value that's saved as the field value).
I've only done this for the react-select Select Widget, I haven't tested with the async widget.
=> Fix bug in select widget handling of choices

CHANGELOG.md, api/buildout.cfg, src/components/manage/Preferences/PersonalPreferences.jsx, src/components/theme/LanguageSelector/LanguageSelector.js, src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx, src/server.jsx
Without using **I18N_LANGUAGE** cookie we have the problem that edit interface (the one that came from Plone api) and toolbar aren't in the right language in LanguageSelector component because Volto use a different cookie (**lang**).
I'm not a master in js tests so i don't know how to test this. If we need some tests, someone can help me?
=> Use Plone's language cookie

CHANGELOG.md, src/components/manage/Blocks/Listing/ListingBody.jsx
When you use addon dropdownmenu, you can add some blocks into a dropdown menu. 
If you add some blocks and you try to access a non published content in private mode, an error is thrown because ListingBody expects a content to check if there's some items inside. 
With this fix, ListingBody could work without 'content'
=> Test if content exists in ListingBody, for addon Dropdownmenu

CHANGELOG.md, src/components/manage/Blocks/Image/Edit.jsx
Since we don't want to automatically set image-id as alt in image block ,we might use content title instead. #1503
=> Image block: modified alt tag to not use image id

CHANGELOG.md, docs/source/deploying/sentry.md
Fix docs examples. See https://docs.voltocms.com/deploying/sentry/#2-runtime
=> Fix sentry docs markdown fmt

CHANGELOG.md, src/helpers/Html/Html.jsx
This will allow runtime_config customization via volto-project / addons
=> Fix runtimeConfig relative vs absolute import

CHANGELOG.md, src/config/RichTextEditor/ToHTML.jsx
Removed default target for link in LinkEntity for text blocks, because was causing internal link to open in new tab.
=> Fix default target for links in text blocks

CHANGELOG.md, src/components/manage/Preferences/__snapshots__/PersonalInformation.test.jsx.snap, src/components/manage/Widgets/FileWidget.jsx, src/components/manage/Widgets/__snapshots__/FileWidget.test.jsx.snap, theme/themes/pastanaga/extras/main.less
@sneridagh I found out that in react-dropzone if we don't provide onChange to input it will use onDrop handler for request. So, I remove the onChange handler for the input. I also found that we are using semantic input which might don't work for some case. And also react-dropzone uses browser Input tag. I have just deleted the unnecessary code.
=> Refactoring FileWidget

CHANGELOG.md, src/components/manage/Toolbar/Toolbar.jsx, src/components/manage/Toolbar/Types.jsx
This pr shows the 'add' button on the toolbar, if a content type is not folderish and multilingual is enabled, to enable ct translations.
=> enabled no-folderish CT to be translated

CHANGELOG.md, src/components/manage/AnchorPlugin/components/LinkButton/AddLinkForm.jsx, theme/themes/pastanaga/extras/blocks.less
=> Fix leaking input CSS in the link widget in draftjs

CHANGELOG.md, razzle.config.js, webpack-bundle-analyze-plugin.js
Fix `yarn analyze` command by packing our own version of
webpack-bundle-analyzer integration. It has a few differences in
configuration to the previous integration: it saves the bundle stats by
default and doesn't open an HTTP server. Check output of `yarn analyze`
command to identify the path to the `reports.html` file @tiberiuichim
=> Fix bundle analyzer plugin

CHANGELOG.md, docs/source/recipes/appextras.md, src/components/theme/App/App.jsx, src/components/theme/AppExtras/AppExtras.jsx, src/components/theme/AppExtras/AppExtras.test.jsx, src/components/theme/AppExtras/__snapshots__/AppExtras.test.jsx.snap, src/config/index.js
The `AppExtras` component is a general use insertion point for things like
analytics, general purpose code spanning the whole application or third party
services code. AppExtras component inserts will be rendered by the `App`
component.
You can either use it by overriding it via Component Shadowing by placing
a custom `src/customizations/components/theme/AppExtras/AppExtras.jsx`...
Or you can use the new key of `config.settings`, the `appExtras`. This is
a list of registrations, each registration is an object with:
- `match`: The `match` key is for objects compatible with [react-router's
matchPath](https://reactrouter.com/web/api/matchPath), so it can be either
a simple string or a match object.
- `component`. Use the `component` to link the component to be used.
- `props`: Extra props to …
=> Add extendible AppExtras

CHANGELOG.md, src/sentry.js
Fix #1986 to also `setTags` and `setExtra` via `~config` settings.sentryOptions
=> Fix Sentry tags and extra via settings.sentryOptions

docs/mkdocs.yml, docs/source/configuration/backend.md, docs/source/getting-started/install.md
Make docker section more simple, 
Explain persistence for the plone docker container in a note,
move kitconcept.volto explanation to configuration chapter,
Use nodejs 14.x in nvm install/use example,
Remove reference to python2.7.,
explain installing Plone backend from source without using Docker.
=> Streamline getting started, update to nodejs 14.x

CHANGELOG.md, Makefile, api/buildout.cfg
For some reason the "wheel" package needs to be installed. At least on my system, ArchLinux up to date.
=> Python3.9 compatibility

CHANGELOG.md, src/components/theme/View/LinkView.jsx, src/server.jsx
These changes fixes the redirects for anonymous both accessing directly the Link object (the change in server.jsx) and navigating through it (with internal links, listing, contents view).
I removed _UNSAFE_componentWillReceiveProps_ because it seemed unused and generated recursion depth errors with _UNSAFE_componentWillMount_
=> fix redirects for Link objects

CHANGELOG.md, src/components/manage/Blocks/HeroImageLeft/View.jsx, src/components/manage/Blocks/HeroImageLeft/__snapshots__/View.test.jsx.snap, src/components/manage/Blocks/Image/View.jsx, src/components/manage/Blocks/Image/View.test.jsx, src/components/theme/Footer/__snapshots__/Footer.test.jsx.snap
add the loading=lazy attribute to the img tag for the Image and HeroImage blocks
* currently 73% browser support https://caniuse.com/loading-lazy-attr but no side effect for others
* no need to add 3rd-party javascript code https://web.dev/browser-level-image-lazy-loading
* improve performance and lighthouse score #2088
=> image loading lazy

CHANGELOG.md, docs/source/configuration/settings-reference.md, src/components/theme/Footer/__snapshots__/Footer.test.jsx.snap, src/config/index.js, src/helpers/Api/APIResourceWithAuth.js
By default superagent drops responses larger than 200mb.
This leads to an error (aka infinite page loading because errors are not well managed..se #2099 ) if we want to download files > 200 mb from Plone.
I don't know if you limit file sizes on Plone usually, but we have several files > 200 mb.
With this change i changed the default limit to 500 mb but i don't know if it's a good idea setting it higher or not.
=> Increase maxResponseSize for superagent calls

CHANGELOG.md, cypress/integration/blocks-copypaste.js, cypress/integration/content.js, src/components/manage/Form/BlocksToolbar.jsx
This fixes a problem with flashing errors in cypress due to multi-block copy/paste code.
=> Make cypress test more resiliant

CHANGELOG.md, docs/source/configuration/how-to.md, docs/source/upgrade-guide/index.md
I found that it's necessary to add addonRoutes to projects routes like
_routes.js:_
```js
import { addonRoutes } from '~/config';
const routes = [
{
path: '/',
component: App, // Change this if you want a different component
routes: [
// Add your routes here
...(addonRoutes || []),
...defaultRoutes,
],
},
];
```
=> Update docs: configuration of routes and addonRoutes

CHANGELOG.md, src/components/manage/Blocks/Listing/DefaultTemplate.jsx, src/components/manage/Blocks/Listing/SummaryTemplate.jsx, src/components/manage/ConditionalLink/ConditionalLink.jsx, src/components/manage/UniversalLink/UniversalLink.jsx, src/components/manage/UniversalLink/UniversalLink.stories.mdx, src/components/manage/UniversalLink/UniversalLink.test.jsx
if item is of @type Link (has the remoteUrl property), a direct link to remoteUrl is generated if user is not logged.
This avoids the passage from the Link detail view page even when users are not authenticated. Especially when Link-type objects appears in listing blocks.
=> UniversalLink and ConditionalLink accepts also an item to link to.

CHANGELOG.md, theme/themes/pastanaga/extras/sidebar.less
When you are on small mobile device (f.e. iPhone 5/SE) collapsed sidebar is not visibile and you cannot use it. 
This fix, makes sidebar-collapsed visibile on small mobile devices.
=> Sidebar on small mobile

CHANGELOG.md, docs/source/recipes/toolbar.md, src/components/manage/Toolbar/Toolbar.jsx, src/components/manage/Toolbar/ToolbarComponents.jsx, src/config/toolbar.js
```
const applyConfig = (config) => {
config.toolbar.activities.view.top.push(ButtonA)
config.toolbar.activities.view.bottom.push({
match: '/documentation',
component: ButtonB,
})
return config;
};
```
=> Let toolbar buttons and menues be restrictable to route

.storybook/preview.js, CHANGELOG.md, docs/source/blocks/editcomponent.md, src/components/manage/Sidebar/ObjectBrowserBody.jsx, src/components/manage/Widgets/ObjectBrowserWidget.jsx, src/components/manage/Widgets/ObjectBrowserWidget.stories.js, src/components/manage/Widgets/__snapshots__/ObjectBrowserWidget.test.jsx.snap, src/config/index.js, src/helpers/Url/Url.js, src/helpers/Url/Url.test.js, src/helpers/Url/urlRegex.js, src/helpers/index.js, theme/themes/pastanaga/extras/objectbrowser-widget.less
WIP
I wonder if we would like to reuse this in other scenarios, like the link chooser in the text block editor... we could refactor it to make it happen...
(sound on) 😄 
https://user-images.githubusercontent.com/486927/110161342-82cb1300-7ded-11eb-9b35-ee47d45ccf07.mov
=> Improved object browser with manual input field

CHANGELOG.md, docs/source/configuration/internalproxy.md
The internal API proxy  documentation now includes more information about src/config.js and
a tip on using console.log(config) to view configuration settings.
=> added explicit information about src/config.js to internal API proxy docs

CHANGELOG.md, src/components/manage/Sidebar/SidebarPortal.jsx, src/components/manage/Sidebar/__snapshots__/SidebarPortal.test.jsx.snap
Fixes the following visual bug when the sidebar content is higher than the screen height:
=> Fix SidebarPortal min-height

CHANGELOG.md, src/components/manage/Widgets/CheckboxWidget.jsx, src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap
_Before_
**Issue:** 
If the value of a checkbox is set to `true` going back to it and changing its value, the checkbox will remain checked even though the value is false.
Also a warning is popping out stating that the input needs to be either controlled or uncontrolled.
**Fix:**
Use a controlled input by defining a state which takes the value of `props.value` on mount or `false` by default.
_After_
=> Make CheckboxWidget behave as a controlled input

packages/generator-volto/CHANGELOG.md, packages/generator-volto/__tests__/app.js, packages/generator-volto/generators/app/index.js, packages/generator-volto/generators/app/templates/package.json.tpl
See #2266 and #2265
Test it:
```
git clone https://github.com/plone/volto simplify-interactive-generator
cd simplify-interactive-generator
git checkout simplify-interactive-generator
cd packages/generator-volto
npm link
```
Interactive:
```
yo @plone/votlo
```
Addon:
```
yo @plone/volto test-group-block --addon=@eeacms/volto-group-block
```
=> Simplify generator interactive questions; Add addons to dependencies

CHANGELOG.md, src/components/manage/Form/InlineForm.jsx, src/components/manage/Widgets/CheckboxWidget.jsx, src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap
**Issue:** If you have a boolean type Field (CheckboxWidget) with no default value and `props.value = false` then this condition `formData[field] || schema.properties[field].default` from InlineForm will evaluate as `false || undefined` which is equal to `undefined` hence the CheckboxWidget value will be `undefined` and will create the issue from here https://github.com/plone/volto/pull/2296.
**Fix:** Use the `default` property only if `default` is a defined property otherwise use the value of the Field.
=> Fixed InlineForm boolean false value

.babelrc, CHANGELOG.md, __tests__/create-addons-loader.test.js, babel.config.js, razzle.config.js
by using the root config using the nowadays accepted naming for the babel config:
https://babeljs.io/docs/en/config-files#project-wide-configuration
Projects are already using it.
Also, updated the adding the nodeExternals for testing addons
=> This fixes addons in Volto itself

packages/generator-volto/CHANGELOG.md, packages/generator-volto/README.md, packages/generator-volto/__tests__/addon.js, packages/generator-volto/generators/addon/index.js, packages/generator-volto/generators/addon/utils.js, packages/generator-volto/package.json, packages/generator-volto/yarn.lock
```
yo @plone/volto:addon --template eea/volto-addon-template @plone-collective/volto-test-addon
```
```
git clone https://github.com/plone/volto.git
cd volto/packages/generator-volto
git checkout remote-addon-template
npm link
```
```
yo @plone/volto my-volto-project --skip-install 
cd my-volto-project
```
```
yo @plone/volto:addon --template=eea/volto-addon-template @eeacms/volto-foo-bar
cd src/addons/volto-foo-bar
```
See github template example: [volto-addon-template](https://github.com/eea/volto-addon-template)
=> Support for Github addon --template

CHANGELOG.md, src/components/manage/Form/InlineForm.jsx
Using a default value of true for the checkbox widget using the InlineForm makes the widget unuseable since the logical operator always returns true for the comparison in the InlineForm.jsx line 97. Using nullish coalescing operator `??` instead of logical or `||` fixes the issue.
=> fix default value bug if default = true

CHANGELOG.md, src/components/manage/Widgets/DatetimeWidget.jsx, src/helpers/Utils/Utils.js, src/helpers/index.js
Extract parseDateTime helper from DatetimeWidget
So now we have a reusable (I had this need) helper from what we did for the widget:
- Fixes TimeZones issues on moment date objects
- Parses a DateTime and sets correct moment locale
=> refactor: extract parseDateTime from DatetimeWidget

CHANGELOG.md, src/actions/querystringsearch/querystringsearch.js, src/actions/querystringsearch/querystringsearch.test.js, src/components/manage/Blocks/Listing/ListingData.jsx
Fixes: #2397
Now listing blocks can order items with "reverse" using latest plone.restapi's rules.
Using a listing block ordered by title, in Edit mode when selecting "Reverse order" you can see contents with titles starting with Z or W, while finding the ones starting with A or B deselecting "Reverse order".
This PR uses two approaches:
- fix in the action which prevents us to migrate blocks to fix it, working with existing listing blocks
- ListingData saves correctly new blocks
=> Fix sort order: using 'ascending' and 'descending'

CHANGELOG.md, src/middleware/api.js
Passed 'params' prop into api Middleware to be available and used in Api.js helper
=> Use params prop in api middleware

packages/generator-volto/CHANGELOG.md, packages/generator-volto/generators/app/templates/package.json.tpl
Fix errors like within Jest tests:
```
● TextBlockEdit › renders w/o errors
TypeError: root.getSelection is not a function
> const { asFragment } = render(
```
=> Fix Jest testing environment. Changed to --env=jest-environment-jsdom-sixteen

CHANGELOG.md, docs/source/configuration/multilingual.md, package.json, src/components/manage/Add/Add.jsx, src/components/manage/Multilingual/CompareLanguages.jsx, src/components/manage/Multilingual/ManageTranslations.jsx, src/components/manage/Multilingual/TranslationObject.jsx, src/components/manage/Toolbar/Types.jsx, src/components/theme/LanguageSelector/LanguageSelector.js, src/helpers/LanguageMap/LanguageMap.js, src/helpers/LanguageMap/LanguageMap.test.js, src/helpers/index.js, yarn.lock
Fixes #2413
In config.js you should use **pt-br** (as it is used in Generic Setup and Plone) instead of **pt_BR** (as used in translation files)
```
isMultilingual: true,
supportedLanguages: ['pt-br', 'en'],
defaultLanguage: 'pt-br',
```
=> Fix multilingual support for languages with composite codes

CHANGELOG.md, docs/source/configuration/settings-reference.md, src/components/manage/UniversalLink/UniversalLink.jsx, src/components/manage/UniversalLink/UniversalLink.test.jsx, src/config/NonContentRoutes.jsx, src/config/index.js, src/routes.js
Fixes: #2411 
If another application is published under the same top domain as Volto, you could have a route like `/abc` which should be not rendered by Volto.
This can be achieved by a rule in the web server (Apache or Nginx) but when navigating client side, you may have references to that route so Volto is handling that as an internal URL but when fetching the content will break.
You can disable that path in `config.settings.internalUrlBlacklist` so it will be handled as an external link.
That route won't be rendered by View but I'm showing NotFound, while being in nonContentRoutes I'm assuring that it will not break the View.
Using UniversalLink will render an external link which will consent Apache/ngnix to pass the call to the external application or whatever.
=> Internal url blacklist

CHANGELOG.md, src/components/manage/Blocks/Block/EditBlockWrapper.jsx
I think this was missed in the blocks form refactoring
=> Fix select previous block when deleting block

.github/workflows/code-analysis.yml, .github/workflows/core-sandbox.yml, .github/workflows/core.yml, .github/workflows/generator.yml, .github/workflows/guillotina.yml, .github/workflows/multilingual.yml
Reverts plone/volto#2450
It duplicates the jobs, which we definitely we don't want. It seems that the cause might be that the user of the forked repo should also enable the actions in the forked repo. It seems it's a security feature...
Let's see if GH improves that in the future...
More info:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjg8-bUucnwAhWDyYUKHcOEDWsQFjAAegQICBAD&url=https%3A%2F%2Fgithub.community%2Ft%2Fduplicate-checks-on-push-and-pull-request-simultaneous-event%2F18012&usg=AOvVaw1xyHSNiVbuGLFMggxrArHm
https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054
=> Revert "Run gha in fork (pull_requests event) too"

CHANGELOG.md, src/components/manage/Blocks/Listing/DefaultTemplate.jsx, src/components/manage/Blocks/Listing/SummaryTemplate.jsx
The listing block Default and Summary templates doesn't render the LinkMore information with the new configurations.
I modify them to make it work. 
Before changes:
After changes:
=> Modify Default and Summary templates to render the LinkMore

CHANGELOG.md, Makefile, api/Makefile, docker-compose.yml, packages/generator-volto/Makefile, packages/generator-volto/generators/addon/templates/Makefile
Just some minor cleanup of the various `./**Makefile` files I ran across while setting
up a test bed for unifying ZMI login and JWT login.  There some tiny bits of opinion but
most of it is best practices, shouldn't interfere with existing developer workflows, and
so I hope will be uncontroversial.
=> build(make): Various minor Makefile cleanup

CHANGELOG.md, src/components/manage/UniversalLink/UniversalLink.jsx, src/components/manage/UniversalLink/UniversalLink.test.jsx, src/components/manage/UniversalLink/__snapshots__/UniversalLink.test.jsx.snap
We caught some edge cases in which UniversalLink was getting an error object as item from cache service.
This avoids any error from a non-nullish object passed as item but still not a Plone content, printing an error (useful for sentry).
=> feat: improve UniversalLink error handling

CHANGELOG.md, src/components/manage/Widgets/SelectWidget.jsx, src/helpers/Extensions/withBlockSchemaEnhancer.js
Before this fix, when you creating a listing block, variation field was empty in sidebar, even though a default option was set. 
Now, when you create a new listing block, in sidebar default option is selected for field 'variation'
=> Set default value selected for variation in listing block

CHANGELOG.md, src/components/manage/Blocks/Listing/ListingBody.jsx, src/components/manage/Blocks/Listing/ListingData.jsx
New blocks schema adds **querystring** prop to listing block data, but it was not considered in listing body. 
Added compatibility for new block schema and  backwards compatibility
=> Use querystring prop in ListingBody

CHANGELOG.md, src/components/manage/Blocks/Listing/ListingBody.jsx
Let's imagine we have 3 listing block in page, and each one has pagination. 
If we change page of the 3rd block, window page was scrolled to top and i had to manually scroll down to see results of second page. 
With this change, on listing page change, window is scrolled to the start of listing block.
=> In listing blocks, scroll to start of listing block instead page start

CHANGELOG.md, src/components/manage/Widgets/VocabularyTermsWidget.jsx, src/components/manage/Widgets/VocabularyTermsWidget.stories.js
The widget can now also act for editing vocabularies with translations. It takes config.settings.supportedLanguages to provide fields for eache language needed.
=> VocabularyTermsWidget option translations for config.settings.supportedLanguages

CHANGELOG.md, src/helpers/AuthToken/AuthToken.js, src/helpers/AuthToken/AuthToken.test.js
I saw that every anonymous request currently has a Set-Cookie to expire  token_auth, but it's unnecessary and make hard to manage any kind of caching.
p.s. anyone that has a better experience with jest than me, please improve my test....
=> Removed unnecessary set-cookies for the removal of the authentication cookie when the user is not logged in

CHANGELOG.md, src/components/manage/Sidebar/ObjectBrowserNav.jsx, theme/themes/pastanaga/extras/sidebar.less
Now you don't have to be pixel perfect for clicking the right arrow in link mode.
Regarding vertical we can't do much because it is space between li.
@tisto screenshot
=> Increasing the clickable area of right-arrow in objectBrowser

CHANGELOG.md, cypress/tests/core/objectBrowser.js, src/components/manage/Sidebar/ObjectBrowserBody.jsx
To search for a content within the object browser, we currently have to click on the lens icon, then click on the input to type some text.
With this PR I'm setting the focus on the search input when opening it from the button.
=> feat: set focus on search input in object browser

CHANGELOG.md, src/components/manage/Widgets/QueryWidget.jsx, theme/themes/pastanaga/extras/widgets.less
Fixes QueryWidget styling if we want to use it standalone.
Before:
After:
=> Fix QueryWidget styling

CHANGELOG.md, src/components/manage/Contents/ContentsItem.jsx, src/components/manage/Contents/ContentsTagsModal.jsx, src/config/Widgets.jsx
Fixes: #2615 
Adds:
- `array` and `token` as named widgets in the config
(this because I had conflicts in the widget retrieval due to choices attribute)
Fixes: 
- fixes correct behavior of the modal to change tags
Now you can correctly set or remove tags to one or more contents.
Retrieves Subject vocabulary to show options to set while you can also create a new one.
Shows contents' actual tags to remove.
=> Fix content tags modal

CHANGELOG.md, src/components/manage/Contents/Contents.jsx
=> Change the batch size of folder content

CHANGELOG.md, src/components/manage/Form/Form.jsx, src/components/manage/Form/ModalForm.jsx, src/helpers/FormValidation/FormValidation.js
Fixes https://github.com/plone/volto/issues/2528
The problem with "required fields" validation is they are all validated in one go, unlike other widget specific validations.
This is only required to be applied on `onBlur` method leaving `onSubmit` logic intact.
Before:
https://user-images.githubusercontent.com/22280901/131368199-7adaa1c7-622c-4d3b-8ad1-e31ee2afcfc9.mov
After:
https://user-images.githubusercontent.com/22280901/131368260-58b0c99c-add6-40ed-8299-1e13571e8869.mov
=> Validate touched-only `required` fields in Forms

CHANGELOG.md, src/components/manage/Widgets/ArrayWidget.jsx, src/components/manage/Widgets/SelectWidget.jsx
=> Fix SelectWidget vocabulary load on second component mount

CHANGELOG.md, cypress/tests/core/metadata.js, src/components/manage/Form/Form.jsx
So I've found a way of solving the `forwardRef` with `injectIntl` and a `connect` altogether... at last.
and with it, an historic wish in the validation of the block editor.
https://user-images.githubusercontent.com/486927/133855445-93c44916-8bd7-4f53-a1fd-6d2c9796b977.mov
=> Fix on form errors in block editor, not changing to metadata tab

CHANGELOG.md, src/helpers/FormValidation/FormValidation.js, src/helpers/FormValidation/FormValidation.test.js
I noticed that the messages when a required field is not filled out point to the internal id of the field,which might lead to confusion for users, as the internal names might not make much sense to an outsider. I switched to using the field title instead of the id. This should also make the errors better localized when using multilingual.
=> use proper fieldtitle for errormessages in add/edit form

CHANGELOG.md, src/components/manage/Controlpanels/ContentTypeLayout.jsx
- when enabling TTW editable DX Layout
=> Get `blocks` and `blocks_layout` defaults from existing behavior

CHANGELOG.md, src/components/manage/Widgets/QuerystringWidget.jsx
=> Fix disable mode of `QuerystringWidget` when all criteria are deleted

.github/workflows/docs.yml, CHANGELOG.md, cypress/tests/core/blocks-image.js, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/es/LC_MESSAGES/volto.po, locales/eu/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/pt/LC_MESSAGES/volto.po, locales/pt_BR/LC_MESSAGES/volto.po, locales/ro/LC_MESSAGES/volto.po, locales/volto.pot, src/components/manage/Blocks/Image/Edit.jsx, src/components/manage/Blocks/Image/ImageSidebar.jsx, src/components/manage/Blocks/Image/__snapshots__/ImageSidebar.test.jsx.snap, src/components/manage/Sidebar/ObjectBrowserBody.jsx, src/components/manage/Widgets/FormFieldWrapper.jsx
Fixes: #1503
1. `FormFieldWrapper` accepts now strings and elements for description
2. When uploading an image or selecting that from the object browser, Image block will set an empty string as alternative text
3. Adds a description to the alt-tag:
We know have the description as:
>  [Describe the purpose of the image](https://www.w3.org/WAI/tutorials/images/decision-tree). Leave empty if the image is purely decorative.
=> Fix alt image handling

CHANGELOG.md, src/components/index.js, src/components/manage/Contents/Contents.jsx, src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap, theme/themes/pastanaga/extras/contents.less
- The sort dropdown is now item dropdown as well, you need to click on it to show the menu items,
the secondary hover items still show up on menu item hover
- The dropdown menus from the breadcrumbs and the table headers are now forced to render downwards
in order to avoid clipping when the window is small such as when you have dev tools enabled
=> #2818 folder contents dropdown changes

docs/source/getting-started/others.md
It appears that there are no talks posted yet for 2021.
I am too lazy to dig into 2020. This at least improves it.
=> Add links to trainings and PloneConf 2020, 2021 YouTube playlists

CHANGELOG.md, src/helpers/Url/Url.js, src/helpers/Url/Url.test.js
For some reason my internalApiPath appears as empty string and it trips this edge case.
=> Fix isInternalUrl when settings.internalApiPath is empty string

CHANGELOG.md, src/actions/vocabularies/vocabularies.js, src/helpers/Vocabularies/Vocabularies.js
Fixes: #2865 
Changes #2862 with a different solution avoiding regex look behind since it's not supported by Safari
=> fix: retrieve vocabulary name in action without regex look behind

CHANGELOG.md, src/components/manage/Sidebar/ObjectBrowserBody.jsx
There was a problem on selected items number in object browser widget if maximumSelectionSize was 0. 
This video shows problem
https://user-images.githubusercontent.com/51911425/143557450-5df874ab-3a63-43f8-a0e9-7dff444cc87a.mov
=> fix: fixed object browser selected items number

CHANGELOG.md, theme/themes/pastanaga/extras/time-picker-overrides.less
...don't ask why 84px.
To have the same behavior on 12 and 24 hrs, if in the current case it's positioned on 24px from right. If it's in "narrow" mode (so 24h) I need 60px more to have the picker dropdown to be aligned correctly.
=> fix: timewidget positioning

CHANGELOG.md, src/components/theme/App/App.jsx, src/components/theme/ContentMetadataTags/ContentMetadataTags.jsx
Currently it's added on contents' views.
But in /add, /edit or other views, the browser doesn't have that attribute, which is important for screen readers, linters and some font variations (like hyphenation).
I'm adding it to App so it's always set.
=> fix: always add lang attr in html

CHANGELOG.md, src/components/manage/Blocks/HeroImageLeft/Edit.jsx, src/components/manage/Blocks/HeroImageLeft/Edit.test.jsx
Copied from image block where it already worked.
Without subrequest, we lost the lock token infos and we cannot save the changes.
=> Use subrequest in hero block to not lost locking token

CHANGELOG.md, src/components/manage/Blocks/Listing/withQuerystringResults.jsx
Actually, based on the `relative_path` changes needed, it's always a good idea to filter paths through Volto's api for URL mangling.
=> Properly generate URL for listing block when used with slots

CHANGELOG.md, src/components/manage/Widgets/QuerystringWidget.jsx
Gives QuerystringWidget more resilience on old schema
=> fix: querystring widget query param access

CHANGELOG.md, src/components/manage/Blocks/Search/hocs/withSearch.jsx
This makes the search block properly read a URL with `?SearchableText=something`.
=> Fix reading initial SearchableText param in search block

CHANGELOG.md, src/components/manage/DragDropList/DragDropList.jsx, src/components/manage/Widgets/__snapshots__/ObjectListWidget.test.js.snap
- Fix placeholder position to work with subtree margins.
The original calculation assumes that there are no margins. The update
works for all cases included when the subtree contains margins that
extend to the node's parent.
- Remove placeholder when dropping in all cases.
- Make placeholder disappear when the element is moved outside the
parent (thus, causes the place to be removed).
=> Fixed drag-and-drop list placeholder issues

CHANGELOG.md, docs/source/contributing/guidelines.md
The GitHub CI check for changelog entries misleads new, would be contributors [indicating that entries should be added in `./news/*` files](https://jenkins.plone.org/roboto/missing-changelog).
[Apparently](https://github.com/plone/volto/pull/2901#issuecomment-989581010) that check comes from [mr.roboto](https://docs.plone.org/develop/coredev/docs/roboto.html).  If that check successfully handles `./CHANGELOG.md` handles in addition to `towncrier` `./news/*` entries, then it's failure message should reflect which is the case for the repo it's checking.  As such, this does seem like a bug in `mr.roboto` or whatever code and/or configuration is responsible for that check and its output.
[This project instead uses simple entries added to …
=> docs(contrib): Changelog entry CI check exception

README.md
& bump to python3.8.  We don't mention node LTS 12 or 14 here either, even though it's technically still possible.
=> Remove python 2.7 from readme

CHANGELOG.md, theme/themes/pastanaga/extras/main.less
In https://github.com/plone/volto/pull/2723 @sneridagh  you did some great changes to the mobile menu.
There is however a small bug when the high z-index value of the wrapper made it appear above the sidebar
content.
This pull request fixes this issue
Here is how it looked before
And how it looks after my change
The hamburger icon is still visible within the nav menu to show or hide
=> Hamburger z-index bug on mobile resolutions

CHANGELOG.md, src/components/manage/Blocks/Listing/ListingBody.jsx, src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
As a first step to #2979, at least we can show a generic "No results" message when there are no results in the listing block
=> show "no results" message when there are no results in ListingBlock

CHANGELOG.md, src/components/manage/Widgets/ObjectListWidget.stories.js
This is a bug caused by the lazyloading of the DND component
=> Fix ObjectListWidget story

CHANGELOG.md, docs/source/cheatsheet.md
This PR also serves as a test of the newly documented process for working with `plone/documentation@6-dev` and submodules.
See also:
- https://github.com/plone/volto/pull/3001
- https://github.com/plone/documentation/pull/1160
=> Add MyST link examples and a seealso to documentation's MyST cheat sheet

CHANGELOG.md, api/Makefile
What an odd mistake to make!  I could have sworn I copied and pasted that from the
top-level `./Makefile` when I made this change but [no I
didn't](https://github.com/plone/volto/commit/c0f4e31c61ce0346937390706fe956f16abf1f27#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L57).
Fixes #2932
=> build(api): Fix redundant buildout install run

CHANGELOG.md, src/components/manage/Widgets/SelectAutoComplete.jsx
@reebalazs I added this optional chaining because what happens props has the choices but its value is null. Then we don't get the array initialization.
=> Fix the `null` error in SelectAutoComplete Widget

docs/source/configuration/how-to.md
Add a link to widget developer recipe at the end of Widget section. 
I think it is import to point developer where to find information about customizing and overriding widgets. 
Thanks @tiberiuichim  for the tip 
https://community.plone.org/t/using-react-currency-selector/14737
=> Add Widget additional information link

src/middleware/api.js
this is just a typo "paralel" vs "parallel" it seems to me that nothing changes, because it is the default behavior
=> typo paralel vs. parallel

CHANGELOG.md, docs/source/addons/index.md, docs/source/configuration/how-to.md, docs/source/configuration/internalproxy.md, docs/source/configuration/settings-reference.md, docs/source/developer-guidelines/language-features.md, docs/source/developer-guidelines/testing.md, docs/source/getting-started/install.md, docs/source/index.md, docs/source/recipes/i18n.md, docs/source/upgrade-guide/index.md
This PR must be merged at the same time as:
https://github.com/plone/documentation/pull/1191
- Make links be compatible between both Volto and Plone documentation
- Add missing html_meta values of files I touched
- Use an explicit lexer `shell` for environment variables
- Use proper casing of JavaScript and NodeJS
=> Fix Sphinx warnings when built in Plone 6 Documentation

CHANGELOG.md, README.md
I've changed the code block in README.md
Also see https://github.com/plone/volto/pull/3142
I've erased the $ symbol before the commands because it's an outdated format and the $ symbol also gets copied when we try to copy directly
Previously 
```
$ npm install -g yo @plone/generator-volto
$ yo @plone/volto
```
now,
```
npm install -g yo @plone/generator-volto
yo @plone/volto
```
Apart from this I also wish to move the other parts to the docs namely training, talks, videos, development directions, etc. from the `README` to `docs` folder.
=> updated code block in readme

CHANGELOG.md, docs/source/releases.md, docs/source/upgrade-guide/index.md
There are also many entries in `ROADMAP.md` and `CHANGELOG.md` at the root of the project, but those are not part of the main documentation. I did not bother with those.
=> Replace docs.voltocms.com with MyST references

CHANGELOG.md, src/express-middleware/sitemap.js, src/helpers/Sitemap/Sitemap.js
* generateSitemap use apiPath instead of preferring internalApiPath when it exists
* sitemap middleware returns wrong headers when errors occur in the sitemap generation
=> fixes in sitemap.xml.gz

Makefile
This break `Makefile` compat for MacOS users, so until is properly adapted, it's worth removing so people does not have to mess up with their environments.
=> Remove clean-tmp-worktrees from Makefile

CHANGELOG.md, package.json, yarn.lock
This new version exports the internal hook [``useDeepCompareMemoize``](https://github.com/kentcdodds/use-deep-compare-effect/blob/main/src/index.ts#L32) which I found useful in a complex view with a complex form and I think it might be useful to have it available for Volto itself o sites built with Volto.
=> Upgraded use-deep-compare-effect to 1.8.1

CHANGELOG.md, docs/source/blocks/editcomponent.md, src/components/manage/Widgets/ObjectBrowserWidget.stories.js
Just a quick PR to add an example of the `selectableTypes` to the `ObjectBrowserWidget`'s storybook.
Closes #2993
=> Docs: Add selectableTypes example to ObjectBrowserWidget storybook

CHANGELOG.md, src/components/manage/Blocks/Image/Edit.jsx, src/components/manage/Blocks/Image/ImageSidebar.jsx, src/components/manage/Blocks/LeadImage/LeadImageSidebar.jsx, src/components/manage/Blocks/Video/VideoSidebar.jsx, src/components/manage/Widgets/ObjectBrowserWidget.jsx
Fixed edit link and image url in this blocks:
- **image block** and **leadimage block**: if an internal url was manually pasted into the field, it wasn't flatten and Plone handled it as an external url. Also, if pasted url ended with '/' nothing was dispalyed in 'Origin' field in sidebar. 
- **video block**: if pasted url was internal and ended with '/' nothing was dispalyed in 'Preview image' field in sidebar. Also if an internal url was pasted in 'Link' field in sidebar, it wasn't flatted and handled from Plone as an external link.
- **objectBrowser**: also in objectBrowser, if pasted url was internal, it wasn't flatted and handled from Plone as an external..
=> fixed editing links and image url in blocks and ObjectBrowser

CHANGELOG.md, theme/themes/pastanaga/extras/contents.less
folder contents bugfix
- fixed the position of the dropdown menu of each table row
- added min-height for the table to better show the dropdown menu even when there is only one item
- added style to wrap titles on desktop monitor
=> fix: fixed the position of the dropdown menu and white-space of tbody

CHANGELOG.md, src/components/manage/Widgets/ArrayWidget.jsx
Fix https://github.com/plone/volto/issues/3214
https://github.com/JedWatson/react-select/blob/b0411ff46bc1ecf45d9bca4fb58fbce1e57f847c/packages/react-select/src/Creatable.js#L35-L37
https://react-select.com/props#creatable-props
Hi @giuliaghisini and @tiberiuichim would you please have a look on what is needed to restrict new keywords. You've seen way more use cases than me. My use case is variants of glossary terms, which obviously come along often as for example 'BEB' and 'BeB'.
It's for sure not OK to overwrite with a brutal `()=>true`.
=> Overwrite isValidNewOption of ArrayWidget. Ignore lower and upper case.

CHANGELOG.md, src/middleware/api.js, src/server.jsx
If content is loaded in a language other than the current locale, Volto tries to switch to the new locale, but it breaks if it's a locale with no Volto translation available. This includes language-specific variants like en_US when only the en locale is available.
To avoid that error, this takes a bit more care to only change to the new language if it's supported.
Fixes #3297
(This is my first Volto PR, so please let me know if I'm missing anything.)
=> Fix changing Volto locale to match the content language

CHANGELOG.md, src/express-middleware/files.js, src/helpers/Proxy/Proxy.js
HTTP Range [HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range)
actually implemented by Zope/Plone doesn't works when Volto act as proxy.
Test to reproduce.
Add a large video file and simulate a Range request:
Plone:
```
curl 'http://localhost:8080/Plone/video.mp4/@@download/file/video.mp4' -H 'Range: bytes=0-100' --dump-header - --output /dev/null
HTTP/1.1 206 Partial Content
Accept-Ranges: bytes
Content-Disposition: attachment; filename*=UTF-8'video.mp4
Content-Length: 101
Content-Range: bytes 0-100/169504558
Content-Type: video/mp4
Date: Tue, 24 May 2022 06:32:18 GMT
Server: waitress
Via: waitress
X-Frame-Options: SAMEORIGIN
X-Powered-By: Zope (www.zope.org), Python (www.python.org)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload …
```
=> HTTP Range support

CHANGELOG.md, src/components/theme/View/DefaultView.jsx
When state.content contains the lock informations, 
DefaultView was calling getSchema without type because content wasn't in state.content and this caused a failing request
Fixed
=> fix schema when content contains lock informations

CHANGELOG.md, theme/themes/pastanaga/extras/toolbar.less
all states should be visible or at least to be scrolled into view.
=> Fix visibility of toolbar workflow dropdown for more states as fitting in .toolbar-content

CHANGELOG.md, src/components/manage/Blocks/Search/layout/LeftColumnFacets.jsx, src/components/manage/Blocks/Search/layout/RightColumnFacets.jsx, src/components/manage/Blocks/Search/layout/TopSideFacets.jsx
Fixes this little bugger. I can't really understand why something like this happens sometimes with the `&&` based conditional rendering
=> Bugfix: avoid rendering a '0' in the search block when no facets were added

CHANGELOG.md, docs/source/conf.py
- Remove sphinx_sitemap configuration because Volto's docs are now imported into the main docs, making this setting unnecessary.
- Set the ogp_site_url to main docs, instead of training.
=> Fix docs configuration

CHANGELOG.md, cypress/tests/core/blocks/blocks.js, src/helpers/Loadable/__mocks__/Loadable.js
Adding more libraries for `lazyloading` is not evaluated in the mock of Loadable, my suggestion is to use `config.settings.loadables` in mock where the lazy loadable libraries are actually registered.
i.e.
https://github.com/RedTurtle/design-volto-theme/blob/master/src/config/italiaConfig.js#L112
=> mock all loadable libraries

CHANGELOG.md, docs/source/developer-guidelines/accessibility-guidelines.md
=> `aria-*` attributes are now parsed correctly by jsx-lexer 2.0

CHANGELOG.md, src/storeProtectLoadUtils.js
If redux middleware dispatches a new action while processing a LOCATION_CHANGED action, then connected-react-router will process the new action while the history still has the old path and will end up updating the history location extra times (see https://github.com/supasate/connected-react-router/issues/309), for example if trying to navigate from /my-page to /my-page/edit then the location will change from /my-page -> /my-page/edit -> /my-page -> /my-page/edit. This in turn was contributing to some flaky tests if the Edit component's asyncConnect handlers get started while the location is set to the old path, and loads the wrong content.
The workaround is to make sure that the middleware in storeProtectLoadUtils.js gives the LOCATION_CHANGED action a chance to be fully processed before …
=> Fix flaky cypress tests (block-listing)

CHANGELOG.md, src/components/theme/View/RenderBlocks.jsx
StyleWrapper will rewrite its children props and will override the id with the one from `props` so we need to specify the correct id of the block.
We can also remove some of the props passed to the Block as StyleWrapper passes all its props to it.
=> Pass the correct id to the blocks in RenderBlocks

CHANGELOG.md, docs/source/upgrade-guide/index.md
This addresses the missed review items from https://github.com/plone/volto/pull/3508
=> Volto slate upgrade guide cleanup

CHANGELOG.md, src/components/theme/ContentMetadataTags/ContentMetadataTags.jsx
(so they don't appear in browser tabs)
I'm not sure what the best way is to write a test for the metadata rendered by react-helmet
=> Remove soft hyphens from the title tag

CHANGELOG.md, src/components/manage/Widgets/ObjectBrowserWidget.jsx
@giuliaghisini Can you recall why is this spread needed? I'm sure that's because of something, so I kept it.
=> Fix and edge case, in case a `RelationList` has no default

CHANGELOG.md, cypress/tests/core/basic/groups-controlpanel.js
Test failed in https://github.com/plone/volto/pull/3644
I doubt that this change makes any difference, but the test succeeds.
=> Fix acceptence test groups controlpanel.

CHANGELOG.md, CONTRIBUTING.md, docs/source/developer-guidelines/contributing.md, docs/source/developer-guidelines/index.md
https://github.com/plone/volto/pull/3643#issuecomment-1248461207
=> Bring back "Guidelines for Contributing"

CHANGELOG.md, src/helpers/AsyncConnect/AsyncConnect.test.js, src/helpers/AsyncConnect/index.js, src/helpers/AsyncConnect/utils.js
Stupidly, the matchRoutes, although returns an Array, it does not match all possible routes. This made it impossible to use multiple asyncPropsExtenders for the same route.
=> Multiple async props extenders

CHANGELOG.md, docs/source/configuration/settings-reference.md
This PR fixes warnings when building the docs: `WARNING: glossary terms must not be separated by empty lines` by closing an unclosed glossary entry's triple-backticks.
=> Close glossary backticks

CHANGELOG.md, packages/volto-slate/src/blocks/Text/DefaultTextBlockEditor.jsx
Since setting the selection has a timeout an error occurs when you press backspace multiple times. This is because the editor tries to set the selection of the first update when the content is already updated and so the selection is out of range. The issue which is raised in the comments is tested and also works without the timeout;
- moving between blocks with up/down arrows
- clicking inside the text of a block should not reset the cursor position to head/end of block text
- split the block with enter in the text
=> Fix backspace selection error.

CHANGELOG.md, cypress/tests/core/blocks/blocks-autofocus.js, src/components/manage/Blocks/Block/BlocksForm.jsx
Fixes https://github.com/plone/volto/issues/3647.
I saw that all the time when  onAddBlock was executed, also the onSelectBlock was because we wanted to select the added block, but with an exception, that I fixed it now.
=> Press Enter in some blocks does not focus on the text block below

CHANGELOG.md, src/helpers/FormValidation/FormValidation.js, src/helpers/FormValidation/FormValidation.test.js
Fixes #3663 
Regex was taken from https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type=email)
Also included an additional test to show the longer domain TLD being correctly validated.
=> Update email widget validation regex

CHANGELOG.md, src/components/manage/Widgets/AlignWidget.stories.jsx
=> Storybook: Allow customising the action for the AlignWidget

CHANGELOG.md, docs/source/upgrade-guide/index.md, packages/generator-volto/CHANGELOG.md, packages/generator-volto/generators/addon/templates/package.json, packages/scripts/CHANGELOG.md, packages/scripts/package.json, packages/scripts/yarn.lock
I checked this out and I don't think it's necessary any longer. On dependency less!
Also, reminder that after this, we might want to remove the Volto dependency on `@plone/scripts` as well, and point `razzle.config.js` reference to i18n module in there for an static reference to `package/scripts/i18n`.
=> Remove Razzle as dep from `@plone/scripts`

CHANGELOG.md, packages/volto-slate/src/utils/blocks.js
When deselecting the list style from the toolbar the markup did replace the li-tags with p-tags but the wrapping ol or ul stayed which made the markup invalid and caused a bug when selecting the list style again (it became a list in a list).
=> Remove wrapping ul or ol when deselecting list

CHANGELOG.md, src/components/manage/Form/Form.jsx
This PR displays the description of any fieldsets in the control panel below the title, as shown below.
Needs plone/plone.restapi#1499
=> Display description in control panel if the field is available

.github/workflows/acceptance.yml, CHANGELOG.md, Makefile, api/buildout.cfg, cypress/tests/core/blocks/blocks-listing.js
Let's see how this goes.
- Upgrade to Plone 6 beta 2
- Flip testing matrix for acceptance tests, make Plone 6 principal subject, Plone 5 as secondary 
I tried to upgrade the convenience `api` folder and it broke. Maybe it's time to go to full mxdiv with it?
=> Update to use Plone 6 beta 2

CHANGELOG.md, locales/ca/LC_MESSAGES/volto.po, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/es/LC_MESSAGES/volto.po, locales/eu/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/pt/LC_MESSAGES/volto.po, locales/pt_BR/LC_MESSAGES/volto.po, locales/ro/LC_MESSAGES/volto.po, locales/volto.pot, src/components/manage/Controlpanels/AddonsControlpanel.jsx, src/components/manage/Controlpanels/__snapshots__/AddonsControlpanel.test.jsx.snap
- Mark Update indications as labels
- Show Update - Install - Uninstall actions as buttons
- Show a "Loading..." dimmer while the load / install / update / uninstall action is being done
- Show toasts with the Update / Install / Uninstall action results.
Fixes #3681
=> Usability fixes in addon control panel 

CHANGELOG.md, src/components/manage/Edit/Edit.jsx
The unlock has to be applied to the new id, if an id has been submitted to save.
=> Fix unlock after changing the id and saving a page

CHANGELOG.md, src/components/theme/App/App.jsx, src/middleware/crashReporter.js, src/start-client.jsx
This crashed development websites.
Also make sentry load only when configured.
=> Fix Sentry failing to load due to adblock

.github/workflows/update_remote_docs.yml, CHANGELOG.md
Calls an Action on the Plone 6 documentation repo that updates the documentation registry's submodules and triggers a new build and deploy of the Plone 6 docs.
Refs plone/documentation#1214
=> Trigger build of Plone 6 docs when documentation is updated

CHANGELOG.md, cypress/tests/core/basic/objectBrowser.js, src/components/manage/Sidebar/ObjectBrowser.jsx, src/components/manage/Sidebar/ObjectBrowserBody.jsx
- When searching by string, the result list limits to images only, in image mode
- Additional searchableTypes property added to openObjectBrowser, to override above default behaviour and restrict search to a list of desired content types
=> Object browser: image search should only show images

CHANGELOG.md, src/components/manage/ReactVirtualized/DynamicRowHeightList.jsx
If the user types a string into an autocomplete widget that has no results, an exception is thrown. This fixes this problem.
`Invalid offset NaN specified`
=> Fix autocomplete widget with an empty search result (Invalid offset NaN specified)

CHANGELOG.md, src/components/theme/Search/SearchTags.jsx, src/components/theme/Search/SearchTags.test.jsx
Includes changes to src/components/theme/Search/SearchTags.jsx and the associated SearchTags.test.jsx.
=> Solved #3455: SearchTags uses invalid vocabulary API

CHANGELOG.md, src/helpers/Extensions/withBlockSchemaEnhancer.js
=> Fix `schemaEnhancer` not being applied if nested `blocksConfig` is present

CHANGELOG.md, locales/ca/LC_MESSAGES/volto.po, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/es/LC_MESSAGES/volto.po, locales/eu/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/pt/LC_MESSAGES/volto.po, locales/pt_BR/LC_MESSAGES/volto.po, locales/ro/LC_MESSAGES/volto.po, locales/volto.pot, src/components/manage/Blocks/Block/BlocksForm.jsx, src/components/manage/Blocks/Block/BlocksForm.test.jsx, src/components/theme/View/RenderBlocks.jsx, src/components/theme/View/RenderBlocks.test.jsx, src/helpers/Blocks/Blocks.js, src/helpers/Blocks/Blocks.test.js
Be more robust towards invalid block configuration
Do not fail when the layout contains a block that does not exists.
This happened recently in a project where a bug caused faulty block
configuration in the history.
- Show missing blocks in the layout as "Invalid block ..."
- Remove such blocks when saving the page next
=> Be more robust towards invalid block configuration

CHANGELOG.md, packages/volto-slate/src/widgets/ErrorBoundary.jsx, packages/volto-slate/src/widgets/style.css
The css selector, in `packages/volto-slate`, for the error message is not specific enough.
As a result, for example, after a validation error in a `form`, the class `error` is added to the `form`  and elements within it unexpectedly turn red.
=> restrict css selector for error message (volto-slate)

CHANGELOG.md, src/components/manage/Form/Form.jsx, src/helpers/FormValidation/FormValidation.js, src/helpers/FormValidation/FormValidation.test.js
While developing the widgets for Quanta, I've found that the errors wasn't drilling down...
=> Fix `FormValidation` error object, use field `id` instead of field `title`

.gitignore, CHANGELOG.md
I use [asdf](https://asdf-vm.com/) for managing my python and node versions rather than pyenv and nvm. While it can read from the `.python-version` and `.nvmrc` files, it's sometimes easier to use it's own config too which is a `.tool-versions` file.
=> Ignore /.tool-versions

.gitignore, CHANGELOG.md, package.json, razzle.config.js
Thus, customizations made in Volto projects will be considered in the tests.
Fixes #3870
=> Configure Jest's moduleNameMapper with AddonConfigurationRegistry

CHANGELOG.md, Makefile, cypress/support/commands.js, cypress/tests/coresandbox/fields.js, docs/source/blocks/editcomponent.md, docs/source/upgrade-guide/index.md, package.json, packages/coresandbox/src/components/Blocks/TestBlock/Data.jsx, packages/coresandbox/src/components/Blocks/TestBlock/Edit.jsx, packages/coresandbox/src/components/Blocks/TestBlock/schema.js, packages/generator-volto/CHANGELOG.md, packages/generator-volto/__tests__/app.js, packages/generator-volto/generators/app/utils.js, packages/volto-slate/src/blocks/Text/DefaultTextBlockEditor.jsx, packages/volto-slate/src/elementEditor/PluginEditor.jsx, src/components/manage/Blocks/Block/BlocksForm.jsx, src/components/manage/Form/BlockDataForm.jsx, src/components/manage/Form/BlockDataForm.test.jsx, src/components/manage/Form/Field.jsx, src/components/manage/Form/InlineForm.jsx, src/components/manage/Form/InlineForm.test.jsx, src/components/manage/Widgets/ObjectListWidget.jsx, src/helpers/Blocks/Blocks.js, src/helpers/Blocks/Blocks.test.js
* Init data with block defaults
* Add start:coresandbox command; add some fields with default values
* WIP on cypress test
* Rest of test
* Add cy.wait
* Roll back changes to Field, no longer pass explicitely defaults; this is the job on the code that instantiates a new form, it needs to applySchemaDefaults
* Use onChangeFormData in InlineForm
* Pass down onChangeFormData from BlockDataForm
* Only pass down onChangeFormData if we have onChangeBlock
* Fix test block
* Fix defaults for ObjectListWidget
* Don't pass onChangeFormData
* Cleanup tests
* Remove comment
* Add ObjectWidget case
* Add cy.getContent; finish test for objectwidget / objectlistwidget defaults
* Code formatting
* Add changelog
* No need for async here
* One more test for the applySchemaDefaults helper
* Improve docs, …
=> Fix initial block settings data defaults, improve `applySchemaDefaults` and `ObjectWidget` schema support (#3925)

packages/generator-volto/CHANGELOG.md, packages/generator-volto/__tests__/app.js, packages/generator-volto/generators/app/utils.js
* Generator is aware of RC and beta versions when canary option is selected
* Fix tests
=> Generator is aware of RC and beta versions when canary option is selected (#3923)

CHANGELOG.md, src/components/manage/Widgets/ObjectListWidget.jsx
So you can do:
```
{
title: props.intl.formatMessage(messages.Slider),
block: 'slider',
fieldsets: [
{
id: 'default',
title: 'Default',
fields: ['slides'],
},
],
properties: {
slides: {
widget: 'object_list',
title: props.intl.formatMessage(messages.items),
schema: itemSchema(props),
activeObject: props.activeObject,
setActiveObject: props.setActiveObject,
default: [{ '@id': uuid() }],
},
},
required: [],
}
```
in the edit:
```
<Sidebar
{...props}
data={data}
block={block}
onChangeBlock={onChangeBlock}
activeObject={slideIndex}
setActiveObject={setSlideIndex}
/>
```
This allows to sync the current object selected from the UI and the block settings and viceversa.
=> Support for drilled down current state and updater function from schema in `ObjectListWidget`

CHANGELOG.md, packages/volto-slate/src/editor/plugins/Markdown/constants.js
This fixes an issue when you try to add a list using markdown syntax but the list is already active. The code tries to unwrap the list which will break and results in removing the entire block. I removed the preFormat for now so it won't be unwrapped. This means the list type will stay the same but the block won't be broken anymore.
=> Fix issue when using list markdown when list is already active.

CHANGELOG.md, src/components/manage/Controlpanels/Users/UsersControlpanel.jsx
Follow up on https://github.com/plone/plone.restapi/commit/6760d55d5fd5ce10adae86b8c79612d5b5545910
This is actually already implemented in the actions but the calling place still missed the change
In short, we want containment search in full name (`search` parameter) and not in the id (`query` parameter, the old way kept for compatibility)
=> Fix user search by full name in users control panel

docs/source/upgrade-guide/index.md, news/4001.documentation
Without the added line, one would find their blocks using draftJs and their richtext widgets using slate.
=> Added docs for proper usage of draftjs for richtext widgets

docker-compose.yml, news/4067.feature
This PR:
- Update Traefik to `v2.9`
- Update Traefik volume 'docker socket' to read-only
=> chore(docker-compose) update traefik config

news/4028.bugfix, src/components/theme/SearchWidget/SearchWidget.jsx
fixes #4028 
reset the value of text using setState() :
```js
onSubmit(event) {
const path =
this.props.pathname?.length > 0
? `&path=${encodeURIComponent(this.props.pathname)}`
: '';
this.props.history.push(
`/search?SearchableText=${encodeURIComponent(this.state.text)}${path}`,
);
// *** reset value of input field
this.setState({
text: '',
});
// ***
event.preventDefault();
}
```
https://user-images.githubusercontent.com/99530996/206274415-094fda89-88e9-4254-b48a-b66d48cad208.mp4
Feedback Welcome.
=> Reset value of input field of SearchWidget.

locales/fi/LC_MESSAGES/volto.po, news/4084.bugfix
=> Add Finnish translation

news/4115.bugfix, razzle.config.js
This removes CleanCSS from the minimiser build step in production mode. The project is unmaintained: 
https://github.com/clean-css/clean-css/discussions/1209
There was a problem when using container queries (@container) since it was unrecognising it, they were wiped out.
Razzle was using it (no clue why) instead of using cssnano (the default in css-minimizer-webpack-plugin). This change relies on it for the minimising step instead.
Also the build now seems to be improved by 600B 😱
```
114.61 KB (-691 B)    build/public/static/css/client.2a553559.chunk.css
```
So good riddance...
=> Remove clean-css from the CSS minimizing step

docs/source/conf.py, news/4145.documentation
This PR fixes a Sphinx warning. Sphinx tries to build the file as a separate page, instead of treating it as an included file. It still renders the file where it is included in the docs.
```
WARNING: Document headings start at H2, not H1 [myst.header]
```
Refs: https://github.com/plone/documentation/pull/1388
=> Exclude included file from sources

news/4182.bugfix, src/routes.js, src/routes.test.js
Spreading `...route.match` inside the routes array works only if `route.match` is an object, but the documentation defines a simpler version of routes as valid:
Using this kind of short routes with the current implementation leads to an SSR that returns 404 for every url.
This PR fixes that and also adds a few tests to try and prevent regressions.
=> Fix for externalRoutes short version not working anymore 

cypress/tests/core/volto-slate/09-block-slate-slashmenu.js, news/4187.bugfix, packages/volto-slate/src/blocks/Text/SlashMenu.jsx
Fixes #4173 
This adds matching on any substring (not just at the start of the block title & id), but scores the results so that initial matches are still preferred.
=> Improve matching in keyboard slash menu

news/4199.documentation, requirements-docs.txt
Refs: https://github.com/plone/documentation/issues/1407
=> Pin Sphinx<5,>=3 due to sphinx-book-theme 0.3.3 requirement.

news/4200.bugfix, src/components/manage/Widgets/ArrayWidget.jsx
In select without vocabulary you could not create more than one item in the form.
=> fix: fixed condition to select without vocabulary

docs/source/getting-started/install.md, news/4209.documentation
See https://github.com/plone/documentation/pull/1413 and https://github.com/plone/volto/issues/3289
This is the first step to incorporating the Volto installation docs into the main Plone 6 Documentation, instead of clicking all over the place. I also tested and cleaned up many of the commands.
=> Add message about the status of Volto and Plone 6 Installation docs.

docs/source/addons/index.md, docs/source/recipes/lazyload.md, news/4233.documentation
This information was very helpful to me when dealing with some add-ons (thanks Tiberiu Ichim for the blog post about untranspiled dependencies). I believe it would be good to have this in the docs.
=> docs additions for external add-ons usage

docs/source/configuration/settings-reference.md, news/4260.feature, src/components/manage/Blocks/Block/StyleWrapper.jsx, src/config/Style.jsx, src/config/index.js, src/helpers/Blocks/Blocks.js, src/helpers/Blocks/Blocks.test.js, src/helpers/index.js, test-setup-config.js
We've been using this to fine adjust the vertical spacing in our last projects. I had doubts about to push this for core, but I decided that could be beneficial for Volto. The drawback is that they could add quite a lot of classnames to the block, but still, my experience and feedback is quite good. Any help that could come from the code in order to style the blocks is welcomed.
=> Enhance the StyleWrapper classNames generator with generic pluggable extenders

news/4282.feature, src/registry.js, src/registry.test.js
This fixes this pattern in React dev tools was showing `Anonymous` as the name of the component.
```
const Image = config.getComponent('Image').component || DefaultImage;
```
Then in JSX
```
<Image .../>
```
=> Add displayName when registering a component in the component registry

news/4104.internal, package.json, packages/generator-volto/yarn.lock, packages/scripts/package.json, packages/scripts/yarn.lock, yarn.lock
Packages Updated:-
Closes #4104
=> Updated 4 Dependencies Closes #4104

news/4383.feature, package.json, razzle.config.js, yarn.lock
@plone/volto-team I just tested it with an add-on that re-added it and it does not break, so it's safe for projects that even declared and finally the plugin gets registered twice. Of course, it's better to remove the redundant one.
=> Add SCSS support in core

docs/source/release-notes/index.md, docs/source/user-manual/copy-paste-blocks.md, news/4404.documentation
It still gets included in the main documentation repo.
Fixes https://github.com/plone/documentation/issues/1431
Also improve alt text of inline images in `copy-paste-blocks.md`.
This change results in a lot of the following warnings only in the volto repo, which can be safely ignored. Basically we're shuffling the warnings from one repo to another to deal with this issue. The warning is irrelevant because `CHANGELOG.md` has a title, but Sphinx is not smart enough to recognize that fact.
`/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/index.md:38: WARNING: toctree contains reference to document 'release-notes/index' that doesn't have a title: no link will be generated`
=> Remove inclusion of CHANGELOG.md for volto repo only

news/4400.bugfix, packages/volto-slate/src/editor/plugins/Link/render.jsx
=> Fix External link Icon shows up in Grid-text block(#4400)

docs/source/addons/index.md, news/4441.documentation
=> Update link to Yarn 3 Workspaces to avoid redirect to Yarn Classic 1.x.

news/4413.internal, packages/generator-volto/generators/app/templates/src/routes.js, packages/generator-volto/news/4413.internal, src/components/theme/App/App.jsx, src/config/Components.jsx
With this it's possible to wrap the App in additional context providers. To do this, you need to:
- override the default app component registration:
```
config.registerComponent({name: 'App', component: MyApp})
```
- write your own component:
```
import { App, connectAppComponent} from '@plone/volto/components/theme/App/App';
const MyAppComponent = (props) => <MyContextProvider><App {...props} /><MyContextProvider>;
export default connectAppComponent(MyAppComponent)
```
The benefit of doing it like this is that the `MyApp` component is wrapped in asyncConnect so it has access to the store.
=> Export App and its connectorAppComponent as standalone

news/4473.bugfix, packages/volto-slate/src/blocks/Table/TableBlockView.jsx
If we have a very large table in Volto. In view mode when we are iterating using an object.Keys it is giving us the wrong order of table rows. Because object. keys don't give us keys in order of properties but it is different, which causes different rows in the edit as compared to the view.
Fixes #4473
=> Fix order of row of long table  in edit and view mode.

news/4495.breaking, packages/scripts/i18n.cjs
Fixes #4495 
Targeting volto 17 b/c it's not a backwards-compatible change.
=> i18n script: use dependency graph sort of addons

cypress/support/commands.js, cypress/tests/core/volto-slate/28-table-block-slate-paste.js, news/4301.bugfix, packages/volto-slate/src/blocks/Table/index.js
**Fix:** Fixed pasting content in Table Block returns an error.
Also added cypress test for pasting text in Table Block.
**Issue:** #4301
**Before:**
**After:**
**What I did:**
I turned on the **normalizeExternalData** extension for Table Block.
=> Fix: Fixed paste issue in table block and added cypress test for it

news/4110.bugfix, src/components/manage/Blocks/ToC/Edit.jsx
https://github.com/plone/volto/issues/4110
Added `block` prop to `BlockDataForm` in the `Edit` component of ToC. If `block` is not passed, `OnChangeBlock` will be called with `undefined` block id.
=> 4110 - default values in ToC

news/4601.bugfix, src/helpers/FormValidation/FormValidation.js, src/helpers/FormValidation/FormValidation.test.js
I cleaned a bit the regexp and fixed an issued that i had locally: links with localhost:8080 were invalid with previous regexp
=> Fix regexp that checks valid URLs and improve tests

.github/workflows/acceptance.yml, .github/workflows/code-analysis.yml, .github/workflows/unit.yml, news/4629.internal
@fredvd @sneridagh @mauritsvanrees This is what I would prefer instead of #4621. I tried it in https://github.com/plone/volto/pull/4628 and it seems to work.
=> Trigger CI on pull_request event

CHANGELOG.md, news/4667.documentation
This is the third time I have fixed this link to `ReactJS.org`. I don't have any clue why it does not stay fixed.
=> Make URL a literal string to fix broken link

docs/source/recipes/creating-views.md, news/4636.documentation
Improve creating views documentation page. 
In previous creating views documentation page, there was a reference with old configuration way. 
Now we use applyConfig to define the configuration, no? 
If we try creating a view and register it with the current documentation, we have an error. 
Edit: what is the right way to create a pull request, is this?
=> docs: improve creating view documentation

docs/source/recipes/widget.md, news/4614.feature, src/components/manage/Widgets/SelectUtils.js, src/components/manage/Widgets/SelectWidget.jsx, src/config/Widgets.jsx
**Please test with https://github.com/plone/plone.restapi/pull/1605**
---
See example.contenttype https://github.com/collective/example.contenttype for example content type with relation fields for testing purpose.
---
See also https://github.com/plone/volto/issues/3355
=> Support RelationList field with StaticCatalogVocabulary and SelectWidget.

packages/generator-volto/generators/app/templates/package.json.tpl, packages/generator-volto/news/4687.bugfix
When an error occurs, the screen appears to be frozen, but the thing is that an empty iframe is covering the whole page, making impossible to click on anything. This is caused by `react-error-overlay` > `6.0.9` in latests Razzle. 
A console log is also there: `Uncaught ReferenceError: process is not defined`.
The latests versions of `react-error-overlay` only works well together with `react-scripts` which Razzle is not using. So we are on our own on this one. 
All projects using Volto 16 onwards should update their `package.json` to use it.
=> Force the resolution of the `react-error-overlay` package to `6.0.9`

news/4697.bugfix, src/components/manage/Blocks/Search/SearchBlockEdit.jsx, src/components/manage/Blocks/Search/hocs/withSearch.jsx
Multiple issues fixed:
SearchBlockEdit calls onTriggerSearch without parameters. But
onTriggerSearch does not ignore toSearchText in case it's not specified
in the call.
If there are multiple blocks in the page, this causes the search text
of all the other block's reset and re-queried with the wrong condition.
Previous to this fix, onTriggerSearch triggered 28 times during loading
and edit page with two search blocks in it. After the fix, it's just 2
times.
The fix is that the deep comparison condition for the query also has to
be applied in withSearch.jsx. Without that, the deep comparison in
SearchBlockEdit.jsx has no effect. This is because the onTriggerSearch
function will be regenerated each time there is an identity change in
data.query anyway. So the hook guard in SearchBlockEdit …
=> Fix search block in edit mode re-queries multiple blocks with an empty search text

news/4638.bugfix, src/express-middleware/sitemap.js, src/helpers/Robots/Robots.js, src/helpers/Sitemap/Sitemap.js
`sitemap.xml.gz` remains identical.
`sitemap-index.xml` can be used instead as an index file, which will link to `sitemap1.xml.gz`, `sitemap2.xml.gz`, ...
The default index size is 2000 which also considers the max file size to remain under Google's limit. (50k)
Also:
- Fix robots.txt to not contain an internal link
=> Generate a split sitemap (also fix robots.txt)

CHANGELOG.md, CONTRIBUTING.md, README.md, docs/source/configuration/settings-reference.md, docs/source/contributing/style-guide.md, docs/source/getting-started/install.md, docs/source/getting-started/others.md, docs/source/recipes/creating-project.md, docs/source/upgrade-guide/index.md, docs/source/user-manual/copy-paste-blocks.md, news/4727.documentation, packages/scripts/CHANGELOG.md, packages/scripts/README.md
This PR backports most of the differences in docs from `master` to `16.x.x`.
A few differences will remain after this is merged, and they should be reviewed for accuracy. Sorry, I don't follow releases closely enough to advise.
=> Backport master docs to 16.x.x.

docs/source/getting-started/install.md, docs/source/getting-started/others.md, docs/source/recipes/creating-project.md, news/4728.documentation
This PR tidies up some stuff that got into 16.x.x which should also be in master.
=> Tidy up from synch with 16.x.x

packages/generator-volto/generators/app/templates/locales/de/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/es/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/eu/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/fr/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/it/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/ja/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/nl/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/pt/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/pt_BR/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/ro/LC_MESSAGES/volto.po, packages/generator-volto/generators/app/templates/locales/volto.pot, packages/generator-volto/news/4737.bugfix
This avoids creation of changes when i18n is synced, which causes the i18n check in a plone cookiecutter project to fail. Fixes https://github.com/collective/cookiecutter-plone-starter/issues/63
Also removed the translator names from the empty locale files, since these are locales for a new project, not the existing translations that those people worked on.
=> Fix whitespace in locales created by the generator

CHANGELOG.md, news/4558.bugfix, src/helpers/Url/Url.js, src/helpers/Url/Url.test.js
I found out that if somehow it happens that a link has a null value, it can be caused by a faulty copy-paste, this error can happen. This is due to the fact that the "email"/"telephone" is null or "res.url" is null.
=> (fix):Object.normaliseMail: Cannot read properties of null

news/4644.bugfix, src/actions/language/language.js, src/components/manage/Add/Add.jsx, src/components/manage/Blocks/Search/components/DateRangeFacet.jsx, src/components/manage/Multilingual/CreateTranslation.jsx, src/components/manage/Multilingual/TranslationObject.jsx, src/components/manage/Preferences/PersonalPreferences.jsx, src/components/manage/Toolbar/Types.jsx, src/components/manage/Widgets/DatetimeWidget.jsx, src/components/manage/Widgets/RecurrenceWidget/ByDayField.jsx, src/components/manage/Widgets/RecurrenceWidget/MonthOfTheYearField.jsx, src/components/manage/Widgets/RecurrenceWidget/Occurences.jsx, src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx, src/components/manage/Widgets/RecurrenceWidget/WeekdayOfTheMonthField.jsx, src/components/theme/Footer/Footer.jsx, src/components/theme/LanguageSelector/LanguageSelector.js, src/components/theme/Logo/Logo.jsx, src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx, src/components/theme/Navigation/NavItem.jsx, src/components/theme/Sitemap/Sitemap.jsx, src/components/theme/View/EventDatesInfo.jsx, src/components/theme/Widgets/DateWidget.jsx, src/components/theme/Widgets/DatetimeWidget.jsx, src/helpers/Utils/Utils.js, src/helpers/Utils/Utils.test.js, src/helpers/index.js, src/middleware/api.js, src/server.jsx
This aims to fix how volto handles language codes when there is a suffix for the region/country (e.g. `pt-br`/`pt_BR`/`pt-BR`).
Unfortunately volto needs to deal with 3 different formats:
- `pt-br`: This is stored in the Plone backend, and documented as the format expected in volto config.
- `pt-BR`: This format is expected by react-intl. After this PR, it also becomes the standard format used in the volto Redux store
- `pt_BR`: This format is expected by gettext and used in .po filenames. Also used in the I18N_LANGUAGE cookie.
So I've created helper functions to convert to each of these formats, and have tried to use them consistently everywhere:
- `toBackendLang`: converts to `pt-br`
- `toReactIntlLang`: converts to `pt-BR` (new name for `toLangUnderscoreRegion`)
- `toGettextLang`: …
=> Try to sort out volto's use of language codes

src/components/manage/Controlpanels/Relations/BrokenRelations.jsx, src/components/manage/Controlpanels/Relations/Relations.jsx, src/components/manage/Controlpanels/Relations/RelationsListing.jsx, src/components/manage/Controlpanels/Relations/RelationsMatrix.jsx, src/reducers/relations/relations.js
@ksuess I tried to update the control panel to use the updated result format that you worked on this morning. Please check my work (especially the broken relations component, which I'm not sure how to test).
Edited to add: I was working on this quickly at the end of the day and I am not confident it is right yet.
=> Update relations control panel to use new result format from relations endpoint

news/4799.bugfix, razzle.config.js
Fixes #4798 
With webpack 5, we need to also exclude node_modules/@plone/volto from the webpack cache, in addition to not ignoring it when watching for file updates. -- based on https://webpack.js.org/configuration/other-options/#managedpaths
Don't backport to volto 16.
=> Fix HMR of @plone/volto

docs/source/configuration/settings-reference.md, news/4820.documentation
- Also remove extra blank line
=> Fix glossary warning due to lack of empty line before a term

news/4841.bugfix, src/helpers/FormValidation/FormValidation.js, src/helpers/FormValidation/FormValidation.test.js
old validation handle 0 as an empty value, and this breaks number fields that can set value as 0
=> Do not break requires validation on number fields with value 0

docs/source/configuration/settings-reference.md, locales/ca/LC_MESSAGES/volto.po, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/es/LC_MESSAGES/volto.po, locales/eu/LC_MESSAGES/volto.po, locales/fi/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/pt/LC_MESSAGES/volto.po, locales/pt_BR/LC_MESSAGES/volto.po, locales/ro/LC_MESSAGES/volto.po, locales/volto.pot, locales/zh_CN/LC_MESSAGES/volto.po, news/4868.feature, packages/volto-slate/src/blocks/Text/DefaultTextBlockEditor.jsx, packages/volto-slate/src/blocks/Text/extensions/withDeserializers.js, src/components/manage/Blocks/HeroImageLeft/Edit.jsx, src/components/manage/Blocks/Image/Edit.jsx, src/components/manage/Contents/ContentsUploadModal.jsx, src/components/manage/Toast/Toast.jsx, src/components/manage/Widgets/FileWidget.jsx, src/config/index.js, src/helpers/FormValidation/FormValidation.js, src/helpers/MessageLabels/MessageLabels.js, src/helpers/index.js
Add a config setting `maxFileUploadSize`, and check it when files are selected for upload.
If anyone has an idea about how to do this in a more centralized way, please let me know!
=> Enforce max upload size

news/4923.internal, src/helpers/Utils/UseDetectClickOutside.stories.jsx
The hook as it is works well... This is the right way to instantiate it along with popper, and it behaves as expected.
The usage inside the accordion has been fixed (my bad). However the usage in the core grid PR is strange and has nothing to do with the one in the demos... no clue why. It works, but not as expected.
=> Add Storybook story for useDetectClickOutside hook with several demos

news/4351.bugfix, src/components/manage/Blocks/Listing/withQuerystringResults.jsx
Fixes https://github.com/plone/volto/issues/4351
=> Fix temporary rendering of folder contents while query is loading

news/4997.feature, src/components/manage/Blocks/Search/SearchBlockView.jsx
Made `selectedView` and `className` props available to the `SearchBlockView.jsx`, following the behavior of Listing Block, to improve styling development.
=> make selectedView and className props available for Search block

news/4984.bugfix, src/express-middleware/files.js, src/express-middleware/images.js
Existing middleware for files and images only add specific headers to the response.
When using [collective.xsendfile](https://github.com/collective/collective.xsendfile), upstream servers rely on the X-Accel-Redirect or X-Sendfile headers.
This PR:
- adds `x-sendfile` and `x-accel-redirect` headers to the list that are added to the response. 
- normalises `files.js` to use `request.headers[header]` instead of `request.get(header)` which ensures comparisons are case insensitive.
Main reason for using xsendfile is that middleware responses get buffered in memory by node, which for large files creates 2 issues:
- Increased memory usage
- Noticeable delay before the file is served to the client while it is buffered from the backend
xsendfile means that only a tiny response is sent and the …
=> Add XSendfile headers to files and images middleware

news/5039.bugfix, src/components/manage/Blocks/Container/EditBlockWrapper.jsx, src/components/manage/Blocks/Grid/Edit.jsx, theme/themes/pastanaga/extras/blocks.less
1. It was no longer possible to select a block in a grid column by clicking unless the grid was already selected.
2. Setting the z-index of the block outline to auto was blocking clicks in some cases.
=> Fix regressions from v17a22

news/5106.bugfix, src/components/theme/Sitemap/Sitemap.jsx, src/components/theme/Sitemap/Sitemap.test.jsx
The plone.restapi navigation endpoint will compute a navigation root from a context path, but the problem is that Volto will trigger the navigation endpoint either on root or on the lang folder. 
https://github.com/plone/plone.restapi/blob/ed070e0769c4ac3efda05448db8846f61dae255c/src/plone/restapi/services/navigation/get.py#L40
https://github.com/plone/volto/blob/4523b13d6586891b9dad7db1caedaab5f6f7dd4b/src/components/theme/Sitemap/Sitemap.jsx#L115C21-L115C21
https://github.com/plone/volto/blob/4523b13d6586891b9dad7db1caedaab5f6f7dd4b/src/actions/navigation/navigation.js#L21
=> Fixes #5105; For the Sitemap component, don't hardcode root as navigation action path

news/5115.bugfix, src/components/manage/Widgets/FormFieldWrapper.jsx, src/components/manage/Widgets/__snapshots__/IdWidget.test.jsx.snap, theme/themes/pastanaga/collections/form.overrides, theme/themes/pastanaga/collections/message.overrides, theme/themes/pastanaga/elements/input.overrides, theme/themes/pastanaga/elements/label.overrides
**Edit:** It seems that we overlooked the original error messages in PastanagaUI form fields elements for over six years (shame on us) without noticing (or caring).
We realised (about time), when trying to fix this overlap:
This is the original mockup from the original PastanagaUI mocks:
=> [Visual bugfix] Match the original mockups for PastanagaUI in regards of the error messages in form field elements

CHANGELOG.md, README.md, docs/source/conf.py, news/5131.documentation
Because we don't include the `CHANGELOG.md` in the build of Volto docs, broken links make it into that automatically generated file. They then show up as broken links in the build of Plone 6 Documentation. The following issue proposed a solution https://github.com/plone/volto/issues/4422, but has not gotten any feedback from a maintainer. @tisto @sneridagh @davisagli I'd do this myself, but I am not sure of how you do a release. In a perfect world, I'd like `CHANGELOG.md` to get copied to `docs/source/release-notes/index.md`, add the `html_meta` stuff for SEO, and remove the include. It would probably be best to add that `html_meta` stuff to `CHANGELOG.md`.
=> Fix linkcheckbroken 301 redirect to https://www.dlr.de/de

news/5019.bugfix, webpack-plugins/webpack-less-plugin.js
In `webpack 5`, when we use the plugin `mini-css-extract-plugin`, the variable `loaderContext._module.matchResource` is filled. This variable is considered when generating the hash of the CSS class name. However, in Volto, the `mini-css-extract-plugin` plugin is only used in the client build. So the CSS class name looked different on the client and the server.
Then, the function that generates the class name was customized, so as not to consider the `loaderContext._module.matchResource` variable.
fixes #5019
=> Fix use of CSS modules in webpack 5

news/5207.bugfix, package.json, razzle.config.js, yarn.lock
The restriction of moment locales in webpack no longer works, probably after an update of moment.
This is the detail of the current bundle
According to the documentation I added a webpack specific plugin, this is the result
=> fix: restrict moment.js locales to supported languages

docs/source/configuration/settings-reference.md, news/5206.documentation
See https://github.com/plone/volto/pull/4658 and https://github.com/plone/plone.restapi/issues/1252
The setting is not documented in the setting reference, and it is worth to have it there.
=> document the querystringSearchGet setting

locales/ca/LC_MESSAGES/volto.po, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/es/LC_MESSAGES/volto.po, locales/eu/LC_MESSAGES/volto.po, locales/fi/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/pt/LC_MESSAGES/volto.po, locales/pt_BR/LC_MESSAGES/volto.po, locales/ro/LC_MESSAGES/volto.po, locales/volto.pot, locales/zh_CN/LC_MESSAGES/volto.po, news/5124.bugfix, src/components/manage/Sharing/Sharing.jsx, src/components/manage/Sharing/__snapshots__/Sharing.test.jsx.snap
fixes #5124
Issue:
The search icon on the CMS UI's sharing page lacked an aria-label, affecting accessibility.
Resolution:
Added an aria-label to the icon in the Input component, enhancing screen reader support.
=> (fixes #5124) Enhance Accessibility, Add aria-label to search. 

news/5215.feature, src/components/theme/ContentMetadataTags/ContentMetadataTags.jsx
Add the canonical link tag in the head, the data were already managed for the meta `og:url`.
=> feat: add canonical link

cypress/tests/core/blocks/block-anchors.js, locales/ca/LC_MESSAGES/volto.po, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/es/LC_MESSAGES/volto.po, locales/eu/LC_MESSAGES/volto.po, locales/fi/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/pt/LC_MESSAGES/volto.po, locales/pt_BR/LC_MESSAGES/volto.po, locales/ro/LC_MESSAGES/volto.po, locales/volto.pot, locales/zh_CN/LC_MESSAGES/volto.po, news/5225.breaking, packages/volto-slate/src/blocks/Text/TextBlockView.jsx, packages/volto-slate/src/editor/render.jsx, src/components/manage/Blocks/Listing/ListingBody.jsx, src/components/manage/Blocks/Title/View.jsx, src/components/manage/Blocks/Title/__snapshots__/View.test.jsx.snap, src/components/manage/Blocks/ToC/variations/DefaultTocRenderer.jsx, src/components/manage/Blocks/ToC/variations/HorizontalMenu.jsx, src/helpers/MessageLabels/MessageLabels.js, src/helpers/Utils/Utils.js, src/helpers/Utils/Utils.test.js, src/helpers/index.js
Closes: #5174
As discussed in https://github.com/plone/volto/issues/5174
Unfortunately this is a Chrome issue, it does works well in FF and Safari :( This only happens in SSR. At least, on links, and when the router is present, it does well.
=> Improve linked headlines

.github/workflows/docs.yml, news/5253.documentation
Disable GHA vale checking, it started to fail with a gazillion of violations, could be that it's related to the renaming, but seems not likely that... We need to review it closely.
/cc @stevepiercy
=> Disable Vale validation in GHA for now

.github/workflows/docs.yml, docs/source/contributing/branch-policy.md, news/5256.documentation
Resolve failing CI build due to reviewdog breakage. See https://github.com/plone/volto/pull/5253
=> Bypass reviewdog and install Vale directly

news/5261.bugfix, src/start-server.js
If the OS returns both ipv4 and ipv6 addresses when resolving a hostname, prefer the ipv4 one.
For example, this fixes connection errors that happen when volto is connecting to the backend on `localhost` (the default) but `/etc/hosts` has `::1` listed before `127.0.0.1` as an IP address for localhost.
=> Prefer resolving DNS to ipv4

news/5263.bugfix, src/components/manage/UniversalLink/UniversalLink.jsx
Not that I think there's any valid use case for it, but at least we avoid a nasty warning
=> Emit a proper URL for the Plone root in a listing

CHANGELOG.md, news/5281.documentation
@ksuess I've figured out what happened: The PR started just before we did the transition to Towncrier, then the change log info was in  `CHANGELOG.md` so it did made to the wrong place, then towncrier didn't pick it up.
Sorry about it!
=> Add note in release notes for Volto 17 final

news/5280.bugfix, src/components/theme/Logo/Logo.Multilingual.test.jsx, src/components/theme/Logo/Logo.jsx, src/components/theme/Logo/Logo.test.jsx, src/components/theme/Logo/__snapshots__/Logo.Multilingual.test.jsx.snap
Following up what we said during the Volto Team Meeting, it's better to not rely in `toPublicURL`, and do not rely on the router sync in Redux store. I changed all to use pathnames, and fallback to `/` if an error is found and no info is in the store.
=> Refactor Logo component to improve the conditional link to the root

news/5096.bugfix, src/components/manage/Blocks/LeadImage/__snapshots__/LeadImageSidebar.test.jsx.snap, src/components/theme/Image/Image.jsx, src/components/theme/Image/__snapshots__/Image.test.jsx.snap
Fixes #5096 
As discussed in the latest team meeting, and also in the issue mentioned above, it was redundant and hard to override.
=> Removed default aspect-ratio from Image component

news/5327.bugfix, src/components/manage/Edit/Edit.jsx
It seems it was a while since it was not working... I guess we will need some tests around it. A simple `flattenToAppURL` missing :(
=> Fix compare translations view

.github/workflows/acceptance.yml, Makefile, news/5332.internal
After #5327 I was wondering how it didn't break cypress, since there was a test in place testing the feature already.
It seems that didn't break in non-seamless mode. So I've enabled a set of acceptance tests that uses the fixture for multilingual using seamless mode. The tests did break using a checkout prior to the test, and they were fixed after applying the fix.
=> Add new multilingual acceptance tests with Seamless mode enabled

news/5305.bugfix, src/components/manage/Blocks/Search/components/SelectStyling.jsx, src/components/manage/Blocks/Search/components/__snapshots__/SelectFacet.test.jsx.snap
=> (FIX): put padding so the text is not clipped

Makefile, news/5375.documentation
When running `make docs-html`, the build will fail because a symlink exists. This pull request checks for the existence of a good symlink and creates one if it does not exist. Whether it exists or not, an appropriate statement is echoed.
=> Check for existence of news symlink

.github/workflows/acceptance.yml, packages/generator-volto/news/5406.bugfix, packages/generator-volto/package.json, packages/generator-volto/yarn.lock
`yo` 5.0.0 has been released, and it broke compatibility with `yeoman-generator` v4 series. Upgrading `yeoman-generator` to latest possible (5) before going to full ESM module, which will force us to move the generator to ESM too.
Update: The tests are not passing now after the upgrade. I've tried a combo of versions of the related test packages, with no luck. They have changed to ESM everywhere, which is not fun at all. Either we move the generator to be full ESM or we can't make them work again. 
/cc @plone/volto-team Any takers?
=> Update yeoman-generator to match changes in latest yo

docs/source/contributing/documentation.md, docs/source/contributing/index.md, news/5377.documentation
The documentation policies are now documented explicitly for Volto, instead of implicitly inherited from `plone/documentation`.
This includes a new Storybook policy, so it should get reviewed and approved by the @plone/volto-team. Also closes #5369.
It also reorganizes contributing toctree so that code quality checks are grouped together.
=> Add documentation chapter to Volto contributing

news/5429.bugfix, src/helpers/Api/APIResourceWithAuth.js
This fix changes how images are fetched from the backend. By default in development mode the images are fetched using the backend url throught the middleware, then ++api++ is added. This url suffix should only be used in either the frontend or in production. When using a different backend which doesn't use the ++api++ suffix this will break otherwise.
=> Fix image paths in development mode

news/5416.bugfix, src/components/manage/Blocks/Video/Body.jsx, src/components/manage/Blocks/Video/Body.test.jsx, src/components/manage/Blocks/Video/__snapshots__/Body.test.jsx.snap
Solved #5416 
Added an extra conditional statement for extracting 'videoID' from youtube video urls containing '/live/'
=> Adding extraction of videoID from youtube videos url which contain '/live/'

docs/source/contributing/version-policy.md, news/5467.documentation
Per discussion with Victor. See https://github.com/plone/volto/pull/5465. This PR should be merged before the others, to ensure that links in the other PR actually work.
=> Added `volto-generator` compatibility with Volto to documentation

.vscode/settings.json, Makefile, package.json, packages/scripts/.eslintrc.cjs, packages/scripts/addon/utils.js, packages/scripts/backportpr.js, packages/scripts/news/5483.feature, packages/scripts/package.json, packages/scripts/vscodesettings.js, pnpm-lock.yaml
Enable proper linting in `packages/scripts` too.
=> Fixes lint inside monorepo packages in VSCode

.github/workflows/acceptance.yml, packages/volto/news/5498.internal
and use v3 of actions/cache, since v2 logs a warning about using an old Node version
=> Fix path for cypress artifacts

Makefile, docs/source/contributing/documentation.md, packages/volto/news/5508.documentation, requirements-docs.txt
~Requires https://github.com/plone/documentation/pull/1591 to be merged first, because of a main documentation reorganization of Vale installation and configuration.~ It was merged.
=> Move Vale from a manual installation to pip

packages/volto/news/5536.bugfix, packages/volto/src/components/theme/Login/Login.jsx, packages/volto/src/components/theme/Unauthorized/Unauthorized.jsx
While developing, could be that you are switching projects, then one token you had from the previous version is tried to be used in the new one. In that case, the unauthorised page pops, then the login route sees that you have a token and not coming from the logout form, then sends you to the root, then the unauthorised pops again, getting into an endless loop.
=> Fixed edge case error in Unauthorised page and Login route behavior.

docs/source/contributing/developing-core.md, packages/volto/news/5537.bugfix
Fixed typo `pnp` to `pnpm` in developing-core.md file
=> fix- #5537

docs/source/recipes/index.md, packages/volto/news/5546.documentation
Unfortunately, the warning type `WARNING: document isn't included in any toctree` does not cause the build to fail, and we decided to not enforce it in Volto because we need to validate change log entries to have correct MyST syntax and links. Also we don't want to turn all warnings into errors at this time because we have a couple of other warning types that we want to allow, such as the LESS lexer in Pygments and html_meta checking.
=> Add how-to-restrict-blocks to recipes/index.md

docs/source/blocks/block-style-wrapper.md, packages/volto/news/5581.feature, packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx, packages/volto/src/components/manage/Blocks/Block/StyleWrapper.jsx, packages/volto/src/components/manage/Blocks/Grid/View.jsx, packages/volto/src/components/manage/Blocks/Image/View.jsx, packages/volto/src/components/manage/Blocks/Listing/View.jsx, packages/volto/src/components/manage/Blocks/Teaser/DefaultBody.jsx, packages/volto/src/config/Style.jsx, packages/volto/src/helpers/Blocks/Blocks.js, packages/volto/src/helpers/Blocks/Blocks.test.js, packages/volto/src/helpers/index.js
This is a pattern I use lately, and it makes a lot of sense to me.
A couple of questions:
- Would it be useful/needed to also inject a className in order to hook to? I was about to do it, but I don't know if that would be required... maybe to know if a value is set or not... but you can always have a default fallback value.
- Naming... what not! I chose `CSSProperty` as the sufix... any other suggestions?
I'm well aware that this opens the door to fine grained style customizations, if we extend the pattern not only to use custom CSS properties but also use random CSS properties (another converter should be created, then do not append the -- and disable nested support, then) I leave it up to the community. However, the initial feeling when we came up with the style wrapper stands: I …
=> Added support for custom CSS properties in the StyleWrapper

docs/source/blocks/block-style-wrapper.md, packages/volto/news/5586.feature, packages/volto/src/helpers/Blocks/Blocks.js, packages/volto/src/helpers/Blocks/Blocks.test.js
Feedback from testing the new feature. Sometimes, you might not want to build the custom CSS property name from the a nested structure (eg. the ColorPickerWidget).
Now you can use the `:noprefix` suffix in the nested property.
Given this block enhancer:
```js
schema.properties.styles.schema.fieldsets[0].fields = [
...schema.properties.styles.schema.fieldsets[0].fields,
'theme',
];
schema.properties.styles.schema.properties['theme'] = {
widget: 'color_picker',
title: "Theme",
colors,
default: defaultBGColor,
};
```
It will generate this values for the StyleWrapper to use:
```js
{
"styles": {
"theme": {
"--background-color": "#222",
"--font-color": "white"
}
}
}
```
The resultant injected custom CSS properties will have prefixed the name of the key.
```html
<div class="block teaser" …
```
=> Allow to bail off the nested name build in the custom CSS properties style name generator

packages/volto/news/5359.bugfix, packages/volto/src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx, packages/volto/src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.test.jsx, packages/volto/src/components/manage/Widgets/RecurrenceWidget/__snapshots__/RecurrenceWidget.test.jsx.snap
Fixes #5359, In the recurrence widget, set the vertical alignment of the `edit` button to `middle`.
=> edit recurrence button is aligned properly

packages/volto/news/5652.bugfix, packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx
This fixes the D&D bug introduced in https://github.com/plone/volto/pull/5581
=> Merge the StyleWrapper styles with the draggable props from b-D&D

packages/volto/news/5656.documentation, requirements-docs.txt
See https://github.com/plone/documentation/issues/1602
=> Pin Vale to 2.30.0 to allow build of documentation until we can upgrade to v3.x

docs/source/addons/index.md, packages/volto/news/5671.bugfix, packages/volto/package.json, pnpm-lock.yaml
Volto has never used the functionality of this plugin because it uses directly the webpack plugin that we
have in the webpack plugins https://github.com/plone/volto/blob/main/packages/volto/webpack-plugins/webpack-bundle-analyze-plugin.js#L8
https://github.com/plone/volto/blob/main/packages/volto/razzle.config.js#L353
See the readme for the plugin that shows that you need to load bundle-analyzer in the plugins of razzle and we never do
https://www.npmjs.com/package/razzle-plugin-bundle-analyzer#usage-in-razzle-projects
yarn analyze or bundle analyze works without having this unmaintained plugin which forced us in 17.x.x to pin webpack-bundle-analyze-plugin in order to avoid using an old version of it because of the razzle-plugin.
=> Removed unmaintained and unused razzle-plugin-bundle-analyze

packages/volto/news/5632.internal, packages/volto/package.json, pnpm-lock.yaml
@ichim-david @pnicolli @tiberiuichim @davisagli I checked the changelog and seems safe. Even for 17, I'd say. What do you think?
The version we are using is broken when used with TS.
=> Update Semantic UI React to version 2.1.5

packages/volto/news/5617.feature, packages/volto/src/components/manage/Contents/Contents.jsx, packages/volto/src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap
=> Added aria-live='polite'

packages/generator-volto/README.md, packages/generator-volto/generators/app/index.js, packages/generator-volto/news/5439.bugfix
Honestly, I hope this triggers a bug acknowledgment that the generator shouldn't automatically create a theme add-on whenever the generator is used to generate the volto project, however in case this is still seen as a feature and not a bug then we should document this behavior and bring it into the awareness of anyone who uses the volto generator.
Added also some extra content to the readme and modified the example project name given from my-volto-project -> myvoltoproject since this is what we use in the documentation.
=> 5439 clarify defaultAddonName option and mention to the generator readme the creation of the theme add-on

packages/volto/locales/ca/LC_MESSAGES/volto.po, packages/volto/locales/de/LC_MESSAGES/volto.po, packages/volto/locales/en/LC_MESSAGES/volto.po, packages/volto/locales/es/LC_MESSAGES/volto.po, packages/volto/locales/eu/LC_MESSAGES/volto.po, packages/volto/locales/fi/LC_MESSAGES/volto.po, packages/volto/locales/fr/LC_MESSAGES/volto.po, packages/volto/locales/it/LC_MESSAGES/volto.po, packages/volto/locales/ja/LC_MESSAGES/volto.po, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/locales/pt/LC_MESSAGES/volto.po, packages/volto/locales/pt_BR/LC_MESSAGES/volto.po, packages/volto/locales/ro/LC_MESSAGES/volto.po, packages/volto/locales/volto.pot, packages/volto/locales/zh_CN/LC_MESSAGES/volto.po, packages/volto/news/5722.bugfix, packages/volto/src/components/theme/Logo/Logo.jsx, packages/volto/src/components/theme/Logo/__snapshots__/Logo.Multilingual.test.jsx.snap, packages/volto/src/components/theme/Logo/__snapshots__/Logo.test.jsx.snap
fixes #5720 
Fixed the Alt-Title of the Logo to say "Back to Homepage" in various Languages for a11y and Screenreader conformity
=> fixed a11y Logo Issue and added Translations

packages/generator-volto/generators/app/templates/package.json.tpl, packages/generator-volto/news/5743.bugfix
`@plone/volto-slate` it's now a standalone package.
=> Fix @plone/volto-slate path in moduleNameMapper

packages/volto/cypress/tests/core/blocks/listing/blocks-listing.js, packages/volto/news/5753.bugfix
- Using only wait('@content') mean that every x times the assert command failed due to running too quick before proper page load
=> Add wait commands to flaky block-listing tests

docs/source/configuration/settings-reference.md, docs/source/user-manual/links-to-item.md, packages/volto/news/5756.documentation
~~@stevepiercy It's a bit more complicated than this... the feature was also backported to Volto 16, but there it is disabled by default. Should we mention this here?~~
The setting which controls it is documented here: https://6.docs.plone.org/volto/configuration/settings-reference.html#term-excludeLinksAndReferencesMenuItem ...should it also be mentioned on this page, or not since this is more for an editor audience?
=> Mention what version the 'links and references' view was added

docs/source/conf.py, packages/volto/news/5761.documentation
chromewebstore recently changed its URL and has "too many redirects" during linkcheck, no matter what I tried. This might be fixed with a more recent version of Sphinx, so I put in a TODO to check when that happens.
=> Exclude chromewebstore from linkcheck

docs/source/upgrade-guide/index.md, packages/volto/news/5762.breaking, packages/volto/src/components/manage/Form/Form.jsx, packages/volto/src/components/manage/Multilingual/TranslationObject.jsx, packages/volto/src/config/index.js
So they can be selected and copied over, for better UX.
=> Remove the isDisabled from all fields in the left side form of the babel view

docs/source/contributing/developing-core.md, docs/source/contributing/install-git.md, packages/volto/news/5769.documentation
@sneridagh do we need to add Yeoman or Yarn as requirements, aligning https://6.docs.plone.org/volto/contributing/developing-core.html with https://6.docs.plone.org/install/create-project.html?
See also https://github.com/plone/documentation/pull/1628
=> Add include for use in main docs and Develop Volto core

packages/volto/news/5805.bugfix, packages/volto/src/components/manage/Widgets/ArrayWidget.jsx
there was a problems sorting items in ArrayWidget, it doesn't work
Now it's fixed:
https://github.com/plone/volto/assets/51911425/65f1f2c7-8801-439d-a7e1-6faa3451a843
=> fix: array widget sort

news/5804.bugfix, src/components/manage/Widgets/ArrayWidget.jsx
there was a problems sorting items in ArrayWidget, it doesn't work 
Now it's fixed:
https://github.com/plone/volto/assets/51911425/08534b7b-feed-43ad-a940-7306083984a5
=> Fix array widget sort

news/4978.bugfix, src/config/index.js, src/helpers/Blocks/Blocks.js, src/helpers/Blocks/Blocks.test.js, src/helpers/Utils/usePagination.js, src/helpers/index.js, test-setup-config.js
into account container blocks as well (#4978)
This is a backport of the fix introduced to usePagination in 17.x.x also in 16.x.x.
My intention is to merge afterwards this pull request from 17.x.x 
https://github.com/plone/volto/pull/5799
so that in Volto 16 websites for users that use volto-tabs-blocks or volto-accordion-block
and they have listing blocks with pagination, that pagination will work for them
=> Fix the condition deciding on listing pagination format so it takes 

packages/volto/Makefile, packages/volto/news/5825.bugfix
After the slots merge when I wanted to bring pull request https://github.com/plone/volto/pull/4252 up to date
Volto crashed with config.getSlots isn't a function.
This change to build-deps checks if there are newer files within the registry folder as opposed to the dist in
which case it should run the registry compile again.
That compile then adds the getSlots config and the instance can properly run again.
=> Updated build-deps command to check if registry is newer than dist to force rebuild

packages/volto/locales/ca/LC_MESSAGES/volto.po, packages/volto/locales/de/LC_MESSAGES/volto.po, packages/volto/locales/en/LC_MESSAGES/volto.po, packages/volto/locales/es/LC_MESSAGES/volto.po, packages/volto/locales/eu/LC_MESSAGES/volto.po, packages/volto/locales/fi/LC_MESSAGES/volto.po, packages/volto/locales/fr/LC_MESSAGES/volto.po, packages/volto/locales/it/LC_MESSAGES/volto.po, packages/volto/locales/ja/LC_MESSAGES/volto.po, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/locales/pt/LC_MESSAGES/volto.po, packages/volto/locales/pt_BR/LC_MESSAGES/volto.po, packages/volto/locales/ro/LC_MESSAGES/volto.po, packages/volto/locales/volto.pot, packages/volto/locales/zh_CN/LC_MESSAGES/volto.po, packages/volto/news/1868.bugfix, packages/volto/src/components/manage/Add/Add.jsx, packages/volto/src/components/manage/Edit/Edit.jsx, packages/volto/src/helpers/FormValidation/FormValidation.js, packages/volto/src/helpers/index.js
In cases where the error is shown in the field itself, do not repeat the message in Toast. It also no longer shows the error code, as this is irrelevant to a manager.
Fixes #1868
=> Show validation error message as string instead of list

packages/volto/news/5742.bugfix, packages/volto/theme/themes/pastanaga/extras/contents.less
- Due to having small table headers such as ID or UID which meant that there was no room to show those ids
This commit fixes https://github.com/plone/volto/issues/5742 by removing the change made in this pull request https://github.com/plone/volto/pull/3245/files#diff-741dc58bf11002ee21b76a53bd83a19041a2dc2e06fcd838346af8ed52c040e6R143
=> Removed word-break:break-word from contents table tbody

packages/volto/news/5880.feature, packages/volto/src/components/manage/Widgets/FileWidget.jsx, packages/volto/src/components/manage/Widgets/__snapshots__/FileWidget.test.jsx.snap
Added a UniversalLink tag around the filename to allow users to download the file directly from the widget in other views.
It's useful if a user needs to download the file but didn't create the content and does not have the original file.
=> Added download link to filename in file widget

docs/source/configuration/volto-slate/index.md, packages/volto/news/5342.documentation
Fixes #5342 for volto docs to indicate that volto-slate is now part of the core
=> Update volto-slate configuration to indicate it is now part of the core.

docs/source/contributing/acceptance-tests.md, docs/source/contributing/developing-core.md, docs/source/contributing/linting.md, docs/source/contributing/testing.md, docs/source/development/overview.md, packages/volto/news/5341.documentation
Fixes #5341 code analysis after some much-needed magic from @stevepiercy  :)
=> #5341 code analysis documentation

docs/source/robots.txt, netlify.toml, news/5916.documentation
Block search engines from indexing content on Netlify preview builds.
See #5725
=> Backport #5725 16.x.x

packages/volto/cypress/tests/core/basic/locking.js, packages/volto/news/5933.internal
Sometimes this test fails because it does not find the alert with the message that the content is locked. What may be happening is that the test runs too quickly, and Plone does not consider that the content has been locked. Then we wait a bit for Plone to consider it locked.
This fix: https://github.com/plone/volto/actions/runs/8403447599/job/23013937367#step:10:649
=> Fix cypress test "As editor, I can unlock a locked page"

packages/volto/news/5919.bugfix, packages/volto/src/components/manage/Widgets/FormFieldWrapper.jsx
Fixes https://github.com/plone/volto/issues/5919
This is my first Volto fix. :-)
=> Fix `error is null` in `FormFieldWrapper.jsx`.

packages/volto/news/5935.bugfix, packages/volto/src/components/theme/Register/Register.jsx
Fixes #941
Requires:
- working SMTP configuration
- `showSelfRegistration: true` in volto settings
- In security control panel:
- "Enable self-registration" checked
- "Use email address as login name" checked
More work would be needed to be support use cases where the user can choose their own username or set a password without email confirmation.
=> Fix self-registration

packages/volto/cypress/tests/core/blocks/blocks-image.js, packages/volto/cypress/tests/core/blocks/blocks-slate.js, packages/volto/cypress/tests/core/blocks/blocks-table.js, packages/volto/cypress/tests/core/blocks/blocks-title.js, packages/volto/news/5894.bugfix, packages/volto/theme/themes/pastanaga/extras/blocks.less
We made the css selector more generic, so that it can also be applied to addon blocks.
Fixes #5894
=> Does not show borders in addon block inputs

.github/ISSUE_TEMPLATE/bug_report.md, packages/volto/news/5940.internal
We need to verify that a bug report is in fact a bug. Once the issue is confirmed, then this label can be replaced with `21 status: confirmed`. This label differs from `needs: confirmation` in that the latter is for old issues that have been hanging around for a long time.
=> Add a new label `needs: triage` to new bug reports

packages/volto/news/5963.bugfix, packages/volto/src/components/manage/ConditionalLink/ConditionalLink.jsx
If no children are given, this rendered `undefined` causing the site to break.
=> Fix rendering if ConditionalLink has no children

packages/volto/cypress/tests/core/volto-slate/06-block-slate-format-link.js, packages/volto/news/5965.bugfix
This should fix the failing test in https://github.com/plone/volto/actions/runs/8726201362/job/23941446900?pr=5295
Locally I could reproduce the failure with Electron and fix it like this by using cy.getSlateEditorAndType.
=> Fix flaky test 'As editor I can add links' by using getSlateEditorAndType

news/5963.bugfix, src/components/manage/ConditionalLink/ConditionalLink.jsx
Backport of #5963 for Volto 17
=> Fix rendering if ConditionalLink has no children (Volto 17)

packages/volto/news/5976.bugfix, packages/volto/src/storybook.jsx
Add possibility to pass down `locale`, `messages` and `defaultLocale` properties inside the `customStore` object to `IntlProvider`. With this change we can control react-intl language provider from inside storybook and switch for example from english to german with storybook args.
=> fix: pass down locale to IntlProvider

Makefile, packages/volto/news/5997.internal
This way we can modify any of the makefile commands or add extra without having to touch the
Volto core file.
=> Allow Makefile to be modified by Makefile.local if present

packages/volto/news/5999.bugfix, packages/volto/src/components/theme/View/View.jsx, packages/volto/src/helpers/Api/Api.js, packages/volto/src/helpers/Api/Api.plone.rest.test.js, packages/volto/src/helpers/Api/Api.test.js
This reverts commit 0fbeea4ec9e21dfca80a61d1c2e73055caf4a381.
It is causing redirects to API URLs when there is a plone.app.redirector alias, instead of to the correct frontend URL.
=> Revert "Fix 301 and 302 redirects. (#5999)"

docs/source/conf.py, docs/source/contributing/documentation.md, docs/source/upgrade-guide/index.md, packages/volto/news/6011.documentation, requirements-docs.txt
See also https://github.com/plone/documentation/pull/1661
=> Add Sphinx examples, align doc requirements with main documentation

packages/volto/news/5961.feature, packages/volto/src/config/ControlPanels.js, packages/volto/src/config/config.test.js
=> Removes navigation settings that are not used by Volto

packages/volto/news/6043.bugfix, packages/volto/src/express-middleware/files.js, packages/volto/src/express-middleware/images.js
----
📚 Documentation preview 📚: https://volto--6043.org.readthedocs.build/
=> Allow X-Robots-Tag header in images/files middleware

packages/volto/news/5866.bugfix, packages/volto/src/components/manage/BlockChooser/BlockChooserSearch.jsx
Fix #5866 
https://github.com/plone/volto/assets/61353484/a27b4519-5cb0-4f3c-aebb-5b1a89699ddb
=> Fix block chooser search is not focusable when clicked on add button

packages/volto/cypress/tests/core/basic/objectBrowser.js, packages/volto/locales/ca/LC_MESSAGES/volto.po, packages/volto/locales/de/LC_MESSAGES/volto.po, packages/volto/locales/en/LC_MESSAGES/volto.po, packages/volto/locales/es/LC_MESSAGES/volto.po, packages/volto/locales/eu/LC_MESSAGES/volto.po, packages/volto/locales/fi/LC_MESSAGES/volto.po, packages/volto/locales/fr/LC_MESSAGES/volto.po, packages/volto/locales/hi/LC_MESSAGES/volto.po, packages/volto/locales/it/LC_MESSAGES/volto.po, packages/volto/locales/ja/LC_MESSAGES/volto.po, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/locales/pt/LC_MESSAGES/volto.po, packages/volto/locales/pt_BR/LC_MESSAGES/volto.po, packages/volto/locales/ro/LC_MESSAGES/volto.po, packages/volto/locales/volto.pot, packages/volto/locales/zh_CN/LC_MESSAGES/volto.po, packages/volto/news/5279.feature, packages/volto/src/components/manage/Sidebar/ObjectBrowserBody.jsx, packages/volto/src/components/manage/Sidebar/ObjectBrowserNav.jsx, packages/volto/theme/themes/pastanaga/extras/objectbrowser-widget.less
----
📚 Documentation preview 📚: https://volto--6054.org.readthedocs.build/
=> Object browser icon view v2

packages/components/news/6062.bugfix, packages/components/src/styles/basic/BlockToolbar.css, packages/components/src/styles/basic/Form.css, packages/components/src/styles/basic/Toolbar.css
----
📚 Documentation preview 📚: https://volto--6062.org.readthedocs.build/
=> [components] Fix `align-items: start` to make autoprefixer happy

packages/components/news/6065.bugfix, packages/components/src/styles/basic/Button.css
This also allows `@plone/components` to play nicely with tailwindcss. See https://github.com/tailwindlabs/tailwindcss/discussions/6694#discussioncomment-3489265
They say they will allow a more flexible use of layers in v4 in order to overcome this issue, but who knows when it's gonna be there.
----
📚 Documentation preview 📚: https://volto--6065.org.readthedocs.build/
=> Make css layer more specific

packages/volto/news/6070.bugfix, packages/volto/theme/themes/pastanaga/extras/widgets.less
This PR fixes
- the byday field buttons in the recurrence widget when font-size is >16px.
- the byyear-byday buttons for the yearly recurrence when font-size is >16px.
----
📚 Documentation preview 📚: https://volto--6070.org.readthedocs.build/
=> Byday and byyear-byday buttons padding in recurrence form

packages/volto/news/6085.bugfix, packages/volto/src/components/manage/Controlpanels/Relations/RelationsMatrix.jsx
This link is outdated after https://github.com/plone/volto/pull/5809, and its anchor never existed. This PR corrects both issues.
----
📚 Documentation preview 📚: https://volto--6085.org.readthedocs.build/
=> Fix link in pop-up RelationsMatrix.jsx

news/5448.bugfix, src/components/manage/Controlpanels/Users/UserGroupMembershipControlPanel.jsx
This fix is needed for the control panel to work with plone.restapi 9.
=> Backport #5448 -- fix restapi version check in group membership control panel

packages/volto/news/6087.bugfix, packages/volto/src/components/theme/FormattedDate/FormattedDate.jsx
Fixes https://github.com/plone/volto/issues/6087
This shows a basic error message, instead of completely crashing the page.
We could also leave this empty.
----
📚 Documentation preview 📚: https://volto--6088.org.readthedocs.build/
=> Fix Uncaught RangeError: date value is not finite in DateTimeFormat.format

packages/volto/news/6046.bugfix, packages/volto/src/components/manage/Blocks/Image/__snapshots__/ImageSidebar.test.jsx.snap, packages/volto/src/components/manage/Blocks/Image/schema.js
Fixes #6046 pass proper defaults to align and size fields of Image block
----
📚 Documentation preview 📚: https://volto--6093.org.readthedocs.build/
=> Fixes #6046 pass proper defaults to align and size fields of Image block

packages/registry/news/6096.feature, packages/registry/src/addon-registry.js, packages/volto/__tests__/addon-registry-project.test.js, packages/volto/news/6096.feature
... and add them to the build resolve aliases
This was missing in the new setup, so now the roundtrip is supported, since the add-ons will declare their resolve paths in `tsconfig.json`, so IDEs JS and TS will be happy, and then the build will recognize them.
In the future this will be also important since we want this to be passed to other builds. Until now, Razzle was who was reading this (only in the main project root) and adding them lately to the Webpack aliases. Now we have it per add-on, independent of the build, `@plone/registry` powered.
=> Add support for reading the add-ons `tsconfig.json` paths

docs/source/upgrade-guide/index.md, packages/types/news/6099.breaking, packages/types/src/config/Settings.d.ts, packages/volto/news/6099.breaking, packages/volto/src/config/index.js, packages/volto/src/helpers/Blocks/Blocks.js, packages/volto/src/helpers/Blocks/Blocks.test.js
This fixes the order tab to detect all containers, including EEA's nested ones in `data` keys.
@ichim-david I updated also the pagination `findBlocks` helper too, with the new code, please take a look.
----
📚 Documentation preview 📚: https://volto--6099.org.readthedocs.build/
=> Improve container detection, `config.settings.containerBlockTypes` is no longer needed

packages/volto/news/6100.bugfix, packages/volto/src/helpers/index.js
In this pr: https://github.com/plone/volto/pull/4731/files, the authors forgot to export the getFieldURL, so you can't import it like this:
`import { getFieldURL } from '@plone/volto/helpers';`
=> (fix): export getFieldURL from Url.js in helpers

packages/volto-slate/news/6106.feature, packages/volto-slate/src/blocks/Text/DetachedTextBlockEditor.jsx, packages/volto-slate/src/blocks/Text/extensions/breakList.js, packages/volto-slate/src/blocks/Text/extensions/insertBreak.js, packages/volto/src/components/theme/Logo/Logo.jsx
Now you could break lists also in DetachedTextBlockEditor, like in text block inside a Grid block
https://github.com/plone/volto/assets/51911425/da08bdea-ee63-4aeb-aeb2-6e2c56f70486
----
📚 Documentation preview 📚: https://volto--6106.org.readthedocs.build/
=> feat: handle breakList in detached TextBlockEditor

cypress/tests/core/basic/metadata.js, news/5982.bugfix, src/components/manage/Form/Form.jsx
When editing metadata externally, as in the case of our EEA metadata block, the current functionality causes the sidebar to automatically gain focus. However, this behavior is unnecessary in this context and results in the sidebar capturing focus inappropriately. To address this, I propose a solution where the sidebar will only receive focus if the user is actively working within it. This can be achieved by checking the activeElement to determine if the sidebar should be focused.
[screen-capture.webm](https://github.com/plone/volto/assets/50819975/6a771fa6-dabf-49c4-82a8-2ea579f9f5bf)
=> Ensure that sidebar field will not steal focus when metadata is edited 17.x.x backport

packages/volto/news/6132.bugfix, packages/volto/src/components/manage/Blocks/Image/Edit.jsx, packages/volto/src/components/manage/Widgets/ImageWidget.jsx
@dobri1408 @ichim-david integrating it into VLT I found this.
----
📚 Documentation preview 📚: https://volto--6132.org.readthedocs.build/
=> Cleanup Image widget and pass down `onSelectItem` prop if any

apps/plone/package.json, packages/generator-volto/generators/app/templates/package.json.tpl, packages/generator-volto/news/6133.bugfix, packages/volto/news/6133.bugfix, packages/volto/src/components/manage/Add/Add.jsx, packages/volto/src/components/manage/Multilingual/CreateTranslation.jsx, packages/volto/src/components/manage/Multilingual/TranslationObject.jsx, packages/volto/src/components/manage/Preferences/PersonalPreferences.jsx, packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx, packages/volto/src/middleware/api.js, packages/volto/src/server.jsx
----
📚 Documentation preview 📚: https://volto--6133.org.readthedocs.build/
=> rename test-setup-config.js to test-setup-config.jsx

docs/source/development/i18n.md, packages/volto/news/6135.documentation
We missed this in https://github.com/plone/volto/pull/6130.
----
📚 Documentation preview 📚: https://volto--6135.org.readthedocs.build/
=> Fix link to renamed `src/constants/Languages.cjs`

packages/volto-slate/news/6159.breaking, packages/volto-slate/news/6159.feature, packages/volto-slate/src/editor/less/editor.less, packages/volto-slate/src/editor/ui/PositionedToolbar.jsx, packages/volto/news/6159.breaking, packages/volto/news/6159.bugfix, packages/volto/src/components/manage/AnchorPlugin/components/LinkButton/AddLinkForm.jsx, packages/volto/src/components/manage/AnchorPlugin/useLinkEditor.jsx, packages/volto/src/components/manage/Form/InlineForm.jsx, packages/volto/src/components/manage/Widgets/ImageWidget.jsx, packages/volto/theme/themes/pastanaga/collections/form.overrides, packages/volto/theme/themes/pastanaga/extras/blocks.less
=> Fixes for Image widget

.gitignore, docs/source/contributing/developing-core.md, packages/volto/Makefile, packages/volto/news/6157.bugfix
This way we make it easy for the beginners that have the docs to use backend-docker-start to run Plone backend to have their data persisted
=> Added data folder as volume for backend-docker-start

docs/source/upgrade-guide/index.md, packages/volto/news/6189.breaking, packages/volto/news/6189.bugfix, packages/volto/src/components/manage/Controlpanels/ContentTypeSchema.jsx, packages/volto/src/config/Widgets.jsx, packages/volto/theme/themes/pastanaga/collections/form.overrides
- Improve CSS for the `SchemaWidget` widget.
- Remove widget registration as `id`, move to `widget` type instead.
=> `SchemaWidget` CSS and registration

docs/source/development/i18n.md, packages/volto/news/6188.documentation
Fixes #1846
In addition to improving the customizations docs which I think might be clearer now, I would change the suggestion regarding overriding translations. I would in fact suggest to keep overridden translations in a dedicated file. The name is actually not important, but I would advide against cluttering the `src/config.js` file with translated messages and would suggest using a dedicated file. The name of the file is not important, but `src/messages.js` sounds like a sane default suggestion imho. Any thoughts?
----
📚 Documentation preview 📚: https://volto--6188.org.readthedocs.build/
=> Improved i18n docs for customizations

docs/source/contributing/developing-core.md, packages/volto/news/6184.documentation
Closes #6157
----
📚 Documentation preview 📚: https://volto--6184.org.readthedocs.build/
=> Add references for contributing to latest and earlier versions of Volto

docs/source/blocks/introduction.md
the full Interface dotted name is the old 'native' python dotted path, but volto.blocks is the official behavior name and should be used.
----
📚 Documentation preview 📚: https://volto--6222.org.readthedocs.build/
=> Update volto.blocks behavior name

packages/volto/locales/ca/LC_MESSAGES/volto.po, packages/volto/locales/de/LC_MESSAGES/volto.po, packages/volto/locales/en/LC_MESSAGES/volto.po, packages/volto/locales/es/LC_MESSAGES/volto.po, packages/volto/locales/eu/LC_MESSAGES/volto.po, packages/volto/locales/fi/LC_MESSAGES/volto.po, packages/volto/locales/fr/LC_MESSAGES/volto.po, packages/volto/locales/hi/LC_MESSAGES/volto.po, packages/volto/locales/it/LC_MESSAGES/volto.po, packages/volto/locales/ja/LC_MESSAGES/volto.po, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/locales/pt/LC_MESSAGES/volto.po, packages/volto/locales/pt_BR/LC_MESSAGES/volto.po, packages/volto/locales/ro/LC_MESSAGES/volto.po, packages/volto/locales/volto.pot, packages/volto/locales/zh_CN/LC_MESSAGES/volto.po, packages/volto/news/5274.bugfix, packages/volto/src/components/manage/Add/Add.jsx, packages/volto/src/components/manage/Controlpanels/Controlpanel.jsx, packages/volto/src/components/manage/Controlpanels/Controlpanel.test.jsx, packages/volto/src/components/manage/Controlpanels/__snapshots__/Controlpanel.test.jsx.snap, packages/volto/src/components/manage/Edit/Edit.jsx, packages/volto/src/helpers/FormValidation/FormValidation.jsx, packages/volto/src/helpers/index.js
Fixes: #5274
Now the error is displayed:
To works properly, it needs: https://github.com/plone/plone.restapi/pull/1771
But it can be merged separately without any problems.
=> Displays validation error messages on control panel forms

packages/volto/news/6237.bugfix, packages/volto/razzle.config.js
(Make sure it doesn't get processed by the file-loader)
Fixes #6219
=> Fix loading .cjs in webpack

packages/volto/locales/ca/LC_MESSAGES/volto.po, packages/volto/locales/de/LC_MESSAGES/volto.po, packages/volto/locales/en/LC_MESSAGES/volto.po, packages/volto/locales/es/LC_MESSAGES/volto.po, packages/volto/locales/eu/LC_MESSAGES/volto.po, packages/volto/locales/fi/LC_MESSAGES/volto.po, packages/volto/locales/fr/LC_MESSAGES/volto.po, packages/volto/locales/hi/LC_MESSAGES/volto.po, packages/volto/locales/it/LC_MESSAGES/volto.po, packages/volto/locales/ja/LC_MESSAGES/volto.po, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/locales/pt/LC_MESSAGES/volto.po, packages/volto/locales/pt_BR/LC_MESSAGES/volto.po, packages/volto/locales/ro/LC_MESSAGES/volto.po, packages/volto/locales/volto.pot, packages/volto/locales/zh_CN/LC_MESSAGES/volto.po, packages/volto/news/6247.bugfix, packages/volto/src/components/manage/Controlpanels/Aliases.jsx, packages/volto/src/components/manage/Controlpanels/__snapshots__/Aliases.test.jsx.snap
The Plone redirection tool allows creating aliases that redirect to an external URL, which is occasionally useful. But currently this is blocked by validation in Volto's control panel for aliases. This PR removes that validation so that it's also possible to do this in Volto.
=> Allow aliases that redirect to an external URL

packages/volto/news/6244.bugfix, packages/volto/src/helpers/Blocks/cloneBlocks.ts, packages/volto/src/helpers/FormValidation/FormValidation.jsx, packages/volto/src/helpers/FormValidation/validators.ts
When we shadow a module in an addon and this module is imported relatively in some `.ts` file used in the addon tests, we receive the error:
```
Could not find a declaration file for module './Module'. '../Module.jsx' implicitly has an 'any' type
```
So we use absolute import in `.ts` files to avoid this problem.
Fixes #6244
=> Fixes imports to avoid type errors in addons tests

packages/volto/news/6167.feature, packages/volto/src/components/manage/Blocks/ToC/Edit.jsx
Ref: #4460 
This PR refactored 
> packages/volto/src/components/manage/Blocks/ToC/Edit.jsx
from class based to functional component
**Before:**
https://github.com/user-attachments/assets/84673f37-1e76-4382-a247-02ac82645ea4
**After**
https://github.com/user-attachments/assets/b007d68f-960b-4105-b9b1-682136457548
This is my first time contrubuting to Volto .So,if I have done anything wrong in my PR, please give feedback and I will try to rectify that.
=> Refactored Blocks/ToC/Edits.jsx to functional component

.github/workflows/acceptance.yml, Makefile, cypress/tests/core/blocks/listing/blocks-listing-templates.js, g-api/README.md, news/6253.internal, packages/generator-volto/Makefile
See https://github.com/plone/volto/pull/6250#issuecomment-2286845833
=> Bump actions/upload-artifact to v4

cypress/tests/core/blocks/listing/blocks-listing-templates.js, news/6250.bugfix, src/components/manage/Add/Add.jsx
When submitting the Add form upon creating a new Content Type, if the connection is too slow, the button will start loading and the spinner will appear, but it will remain clickable, thus allowing to submit the form and trigger the query multiple times, which in turn results in creating more instances of the same CT.
Adding the disabled prop to the button when the query is still loading prevents this issue from happening.
=> fix: disable save button upon submitting

packages/volto/news/6248.feature, packages/volto/src/components/manage/Contents/Contents.jsx, packages/volto/src/components/manage/Contents/ContentsPropertiesModal.jsx, packages/volto/src/config/index.js
This has a couple improvements for the "properties" modal in the Contents view.
1. It makes it possible for an addon to add more properties with a schema enhancer, without needing to shadow the ContentsPropertiesModal component.
2. If all selected items have the same value for a field, the form is now prepopulated with that value.
=> Allow enhancing the ContentsPropertiesModal schema

news/6248.feature, src/components/manage/Contents/Contents.jsx, src/components/manage/Contents/ContentsPropertiesModal.jsx, src/config/index.js
(Note, I've taken care that the component will still function even if Contents.jsx was shadowed and does not pass `values`)
=> 16.x backport: Allow enhancing the ContentsPropertiesModal schema (#6248)

packages/volto/news/6258.bugfix, packages/volto/src/components/manage/Contents/Contents.jsx
The item can be undefined if it's in this.state.selected but not this.state.items. This can happen after navigating to a different folder.
=> Fix edge case in ContentsPropertiesModal

packages/volto/news/6232.internal
Merge after the inclusion of the merged PR https://github.com/twisted/towncrier/pull/647, which closed https://github.com/twisted/towncrier/issues/643, in the next release of towncrier. 
Closes #6225.
=> Revert rename of .gitkeep for consistency

docs/source/configuration/settings-reference.md, packages/volto/news/4819.feature, packages/volto/src/components/manage/Controlpanels/Controlpanel.jsx, packages/volto/src/config/ControlPanels.js, packages/volto/src/config/index.js, packages/volto/test-setup-config.jsx
`filterControlPanelsSchema` has been migrated to `Controlpanel.jsx` and uses the `unwantedControlPanelsFields` setting. So, if any portal wants to add fields in the Control Panel, it will be necessary to customize only the `unwantedControlPanelsFields` configuration, instead of customizing the entire `filterControlPanelsSchema` function.
This is an improvement for #3904
=> Add setting unwantedControlPanelsFields and use it in the function filterControlPanelsSchema

packages/volto/news/6213.feature, packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx
Refactored DatetimeWidget.jsx from class-based to functional-based component.
=> Refactor DatetimeWidget

packages/volto/news/6278.bugfix, packages/volto/src/config/ControlPanels.js, packages/volto/src/config/config.test.js
The help for this field says:
`By default, any content item in the root of the portal will appear as a tab. If you turn this option off, only folders will be shown. This only has an effect if 'automatically generate tabs' is enabled.`
This doesn't make sense in Volto. Volto doesn't display item as tab.
=> Remove "Generate tabs for items other than folders" field from navigation control panel

packages/volto/news/6279.bugfix, packages/volto/src/components/manage/Blocks/Grid/View.jsx
Fixes #6279 
This can be a single line fix:
https://github.com/plone/volto/blob/7690677589ad881d794a9484d9a8ee1aa005fbcf/packages/volto/src/components/manage/Blocks/Grid/View.jsx#L10
adding this check just before the above mentioned line will fix this
```js
if (data.blocks_layout === undefined) {
return null;
}
```
then this won't render any Grid block since its empty so it makes sense too, but yeah it remains in the formData so going into edit again will open up the TemplateChooser again.
=> Empty GridBlocks will not be rendered in 'View'

docs/source/upgrade-guide/index.md, packages/volto/news/6286.documentation
----
📚 Documentation preview 📚: https://volto--6286.org.readthedocs.build/
=> Added a notice in the upgrade guide for CookiePlone as the recommended way for generating projects and add-on boilerplate

docs/source/upgrade-guide/index.md, packages/volto/news/6290.documentation
I updated the Upgrade Guide Cookieplone section. This also brings up new issues that must be resolved before the final Volto 18 release.
See also:
- https://github.com/plone/documentation/issues/1706
- https://github.com/plone/volto/issues/6289
- https://github.com/plone/documentation/pull/1707
----
📚 Documentation preview 📚: https://volto--6290.org.readthedocs.build/
=> Upgrade Guide Cookieplone review

packages/volto/cypress/tests/core/basic/a11y.js, packages/volto/news/2570.bugfix, packages/volto/theme/themes/pastanaga/collections/form.overrides
The PR #2573 is quite old, and since then, the structure of Volto 18 has changed. This PR aims to bring it up to date.
It was approved 3 years ago.
=> Updated #2573 to Volto 18: Change text color to black for input:focus

packages/volto/news/6330.bugfix, packages/volto/theme/themes/pastanaga/modules/accordion.variables
=> Use consistent text colour for accordion titles to improve contrast and CMS consistency

packages/volto/news/6332.bugfix, packages/volto/src/components/manage/Widgets/ArrayWidget.jsx, packages/volto/src/components/manage/Widgets/SelectWidget.jsx, packages/volto/src/components/manage/Widgets/TokenWidget.jsx, packages/volto/src/components/manage/Widgets/__snapshots__/ArrayWidget.test.jsx.snap, packages/volto/src/components/manage/Widgets/__snapshots__/SelectWidget.test.jsx.snap, packages/volto/src/components/manage/Widgets/__snapshots__/TokenWidget.test.jsx.snap
Readable labels for https://github.com/plone/volto/issues/5139
=> Labels accessibility for ArrayWidget,SelectWidget,TokenWidget

packages/volto/news/6295.bugfix, packages/volto/src/components/manage/Form/Form.jsx, packages/volto/src/components/manage/Toast/Toast.jsx, packages/volto/src/components/manage/Toast/__snapshots__/Toast.test.jsx.snap, packages/volto/theme/themes/pastanaga/extras/main.less
With this changes error messages (and labels on single fields) are updated each time a POST/PATCH return a validation error (before this, error messages in fields weren't updated).
I've also joined error messages in one single toast because i've found that raising multiple toasts, only last will be shown.
For me it's also more readable a single toast with all the informations, but this can be reverted if you don't like it (i had to change also a wrapper into Toast component to allow insert an ul tag).
This is an example of the result:
=> Join validation errors in one single toast and update api error resp

news/6294.bugfix, src/components/manage/Toolbar/Toolbar.jsx, src/components/manage/Toolbar/__snapshots__/Toolbar.test.jsx.snap, theme/themes/pastanaga/extras/toolbar.less
Porting of PR for Volto 18 to Volto 17. 
This is what the PR for Volto 18 entailed the following:
Added a new class for the toolbar handler in the homepage based on the path.
The homepage is the only page with path ''.
The homepage is always public, so it needs a style regardless of the review state of the page
Since it's always public, I used the @teal-blue color used for public pages
=> fix: state and styles for toolbar handler for hp for volto17

docs/source/contributing/developing-core.md, packages/volto/news/6289.documentation
Fixes #6289 
----
📚 Documentation preview 📚: https://volto--6352.org.readthedocs.build/
=> Update refs to old cookiecutter in docs

docs/source/upgrade-guide/index.md, packages/volto/news/6360.documentation
----
📚 Documentation preview 📚: https://volto--6360.org.readthedocs.build/
=> Fix the syntax for the label `upgrade-18-cookieplone-label`

docs/source/contributing/developing-core.md, packages/volto/news/6362.documentation, styles/Vocab/Plone/reject.txt
See https://github.com/plone/documentation/issues/1720
----
📚 Documentation preview 📚: https://volto--6362.org.readthedocs.build/
=> Fix spelling of prerequisites

packages/volto/news/6313.bugfix, packages/volto/theme/themes/pastanaga/extras/toolbar.less
=> Add outline to toolbar buttons

packages/volto/news/6315.bugfix, packages/volto/src/components/manage/Sidebar/SidebarPopup.jsx
As an extension of https://github.com/plone/volto/pull/2509#issuecomment-1016368522
The problem with block losing focus on ESC was originating from https://github.com/plone/volto/blob/355bbad4e61420c4ede481a1bcae21a3ed82148e/packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx#L77
The solution was to intercept the event by making `<aside>` focusable. Since non-interactive elements should not be made focusable, therefore added tabIndex={-1}.
=> fix(SideBarPopup): close sidebarPopup on ESC keypress

docs/source/addons/best-practices.md
This merely adds a reference label so it can be reached from the main documentation. Consider it a typo fix.
=> Add a reference label

docs/source/recipes/how-to-restrict-blocks.md, news/6264.feature, packages/volto-slate/src/blocks/Text/SlashMenu.jsx, src/components/manage/BlockChooser/BlockChooser.jsx, src/components/manage/BlockChooser/BlockChooser.test.jsx, src/hooks/index.js, src/hooks/user/useUser.js
Backport of #6271 and #6293 to Volto 17
Fixes #6264
=> Pass the `user`, `navRoot` and `contentType` objects to the `restricted` function of the block settings

packages/volto/news/6381.bugfix, packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx
=> Added missing arg for `buildStyleClassNamesExtenders`

news/6384.feature, src/components/manage/Diff/DiffField.jsx, src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap, src/components/manage/Diff/__snapshots__/DiffField.test.jsx.snap
This is a backport PR for [PR #6309](https://github.com/plone/volto/pull/6309).
**Why I believe this is not a breaking change:**
1) This can be viewed as a bug fix, as the History page appears broken when used on a complex page. This PR aims to resolve that issue.
2) Although the snapshot changes, it doesn't introduce a breaking change since there is no visual impact. The removal of the span occurs because this fix ensures that RenderBlocks, rather than DefaultView, is used to render the block changes, as it should be.
=> Backport #6309 to Volto 17

Makefile, packages/volto/news/6403.internal
Closes https://github.com/plone/volto/pull/6403
-----
=> Fix clean make command

apps/nextjs/package.json, apps/vite-ssr/package.json, apps/vite/package.json, packages/components/news/6405.bugfix, packages/components/src/components/Select/Select.stories.tsx, packages/components/src/components/Select/Select.tsx, pnpm-lock.yaml
=> [components] Fix Select component logic to support `items` use case

packages/client/news/6400.feature, packages/client/src/restapi/content/add.test.tsx, packages/client/src/restapi/navigation/get.test.tsx, packages/client/src/restapi/navigation/get.ts
-----
I am not fully satisfied with the unit test I have added as it only checks the new `depth` parameter is accepted but it is not checking how deep is the obtained nav tree.
The thing is I was not able to created nested contents in the unit test (I tried `createContent` with `path: '/news'` but it was failing).
=> support depth in getNavigationQuery

docs/source/backend/index.md, packages/registry/news/6422.bugfix, packages/registry/src/index.ts, packages/registry/src/registry.test.tsx, packages/volto/news/6422.feature, packages/volto/src/reducers/content/content.js
I have no clue where to document this feature...
-----
Closes #
=> Client transforms for reducer data

docs/source/backend/index.md
Since this is a clean up of #6422, no change log is needed.
----
📚 Documentation preview 📚: https://volto--6443.org.readthedocs.build/
=> Clean up #6422

docs/source/upgrade-guide/index.md, packages/volto/news/6426.documentation
-----
Closes #
----
📚 Documentation preview 📚: https://volto--6426.org.readthedocs.build/
=> Add deprecation notices to the Upgrade guide

apps/nextjs/README.md, apps/nextjs/next.config.mjs, apps/nextjs/src/app/config.ts
@pnicolli to integrate with your Next.js branch
=> [Next.js] Better Vercel deployment

docs/source/upgrade-guide/index.md, packages/volto/news/6446.documentation
Added upgrade guide fix for HMR
----
📚 Documentation preview 📚: https://volto--6446.org.readthedocs.build/
=> Added upgrade guide fix for HMR

news/3839.bugfix, src/components/manage/Blocks/Listing/getAsyncData.js
When you add a listing block with no criteria, it will give a backend error.
Fixes #3839
=> Refs #3839 - Fix error where there is no query supplied

packages/volto/news/6451.bugfix, packages/volto/src/components/manage/Blocks/Block/Edit.jsx, packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx
The defaults were applied later in the Edit component tree, we need them too in the top of the editWrapper to calculate the styles too.
=> Moved `applyBlockDefaults` one component up so the style is computed correctly

docs/source/conf.py, docs/source/contributing/install-nvm.md, packages/volto/news/6460.documentation
We previously consolidated these instructions into a single include file, so the replacement is no longer needed, and it stopped working when we moved it into a code block.
See https://github.com/plone/documentation/pull/1746/
----
📚 Documentation preview 📚: https://volto--6460.org.readthedocs.build/
=> Fix display of nvm version when installing it for Contributing to Volto.

packages/components/news/+packagingfix.internal, packages/components/package.json, packages/providers/news/+packagingfix.internal, packages/providers/package.json, packages/registry/news/+packagingfix.internal, packages/registry/package.json, packages/scripts/.npmignore, packages/scripts/news/+packagingfix.internal, packages/volto/news/6470.internal
Fix missing export `src` in @plone/components Also improve packaging in packages.
=> Fix packaging and plone/components src export

packages/volto/news/6473.bugfix, packages/volto/src/components/manage/Controlpanels/Aliases.jsx
=> URL Management control panel: show errors from CSV upload

PACKAGES.md, apps/rr7/README.md
No change log needed as this is my review of the already merged #6472 PR.
=> Docs 6472 tidy

packages/volto-slate/locales/nl/LC_MESSAGES/volto.po, packages/volto-slate/news/6476.feature, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/news/6476.feature
Contributed to by the Flemish Environment…
These are translations only. I tried to run the linting etc. by following the instructions at https://6.docs.plone.org/volto/contributing/developing-core.html and then run 'pnpm lint', in the packages/volto directory but I get a message that more than 10 errors are present.  Also my pnpm-lock.yaml file gets local changes when I have pulled out the latest main and am using corepack to pick the correct pnpm version:
```
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index d17950b41..f4ff0050c 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -25399,7 +25399,7 @@ snapshots:
babel-plugin-polyfill-corejs2@0.4.10(@babel/core@7.25.8):
dependencies:
-      '@babel/compat-data': 7.25.8
+      '@babel/compat-data': 7.24.4
```
-----
=> Dutch Translations update. 

docs/source/conf.py, docs/source/tutorials/index.md, docs/source/user-manual/copy-paste-blocks.md, packages/volto/news/6486.documentation, requirements-docs.txt
This PR needs to be merged before the main documentation PR (coming soon).
Closes #5301.
----
📚 Documentation preview 📚: https://volto--6486.org.readthedocs.build/
=> Add support for sphinxcontrib-youtube and alt tags for videos

packages/volto/news/6485.bugfix, packages/volto/src/components/manage/Display/Display.jsx
documentation) for my changes, either in the Storybook or narrative documentation.
=> Do not break toolbar if layout id is not registerd in layoutViewsNamesMapping

packages/volto/news/6487.bugfix, packages/volto/src/components/theme/App/App.jsx
When you search for a string with spaces in search site, page brokes because section body class  is wrong calculated
-----
Closes #
=> fix: BodyClass depending on sections

docs/source/configuration/volto-slate/index.md, docs/source/tutorials/index.md, packages/volto/news/4203.documentation
Fixes https://github.com/plone/volto/issues/4203
_To minimize the use of cookies and protect user privacy, leverage the "no-cookie" domain provided by YouTube. Instead of using the standard www.youtube.com domain, utilize www.youtube-nocookie.com in the embed URL. This prevents YouTube from setting cookies on the user's device._
_Add the privacy_mode=1 parameter to the embed URL. This parameter further enhances privacy by ensuring YouTube doesn't store user information or track their activity while watching the embedded video._ 
https://usercode.de/blog/how-to-embed-youtube-videos-with-maximum-privacy-gdpr-compliant
----
📚 Documentation preview 📚: https://volto--6494.org.readthedocs.build/
=> More privacy concerning youtube links and fixing link check warnings for youtube playlist links

docs/source/conf.py, packages/registry/docs/conf.py, packages/registry/news/6502.documentation, packages/volto/news/6502.documentation
- html_use_opensearch value must not have a trailing slash
- Clean up comments
----
📚 Documentation preview 📚: https://volto--6502.org.readthedocs.build/
=> Fix linkcheck

packages/volto/news/6511.bugfix, packages/volto/razzle.config.js
It still seems to work without this, and it was showing some warnings on startup. (Reported in https://community.plone.org/t/warnings-durung-volto-start-using-2024-training/20205)
=> Remove devserver settings for HMR of volto

packages/volto/news/6524.bugfix, packages/volto/src/config/Components.jsx, packages/volto/src/config/index.js
For 18.2.0, after move the core code to use direct imports in #6509 in projects still using some barrel imports, in dev mode, HMR errored due to a circular import error. 
```
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
```
Investigating, I managed to pinpoint the problem in the default config of the component registry, since we have in there `App` registered. It seems that it's in there to provide maximum flexibility for providing a complete different `App`, if needed. It's used by the old generator, but not anymore by the project-less setup. So it has to go, and use shadowing for that purpose.
I'll add a note for React 19 to remove it.
I workaround it by not relying on import/export as side effect for the apply the setting for components, but as a …
=> Fixed circular import error in dev with HMR in `App` component when imported in the main default config

packages/volto/news/6525.bugfix, packages/volto/src/config/Blocks.jsx, packages/volto/src/config/index.js
More fixes related to https://github.com/plone/volto/pull/6509 and #6524 .
Moved the blocks config to use a init function too, plus some reordering in the `src/config/index.js`
=> Fixed circular import error in dev with HMR in core Blocks shadow customizations

packages/volto/news/6526.bugfix, packages/volto/src/config/Views.jsx, packages/volto/src/config/Widgets.jsx, packages/volto/src/config/index.js
More refining of #6509 HMR still failing in some use cases.
Used the usual solution reorder imports and use function for applying the config instead of relying on the import side effect.
=> Fixed circular import error in dev with HMR in core Views and Widgets shadow customizations

locales/ca/LC_MESSAGES/volto.po, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/es/LC_MESSAGES/volto.po, locales/eu/LC_MESSAGES/volto.po, locales/fi/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/pt/LC_MESSAGES/volto.po, locales/pt_BR/LC_MESSAGES/volto.po, locales/ro/LC_MESSAGES/volto.po, locales/volto.pot, locales/zh_CN/LC_MESSAGES/volto.po, news/6517.bugfix, src/components/manage/Contents/Contents.jsx, src/components/manage/Contents/ContentsDeleteModal.jsx, src/components/manage/Rules/Rules.jsx, src/reducers/index.js, src/reducers/linkIntegrity/linkIntegrity.js, src/reducers/linkIntegrity/linkIntegrity.test.js
backport of https://github.com/plone/volto/pull/6516/
fixed and improved link integrity popup when deleting item/items from folder contents. 
Moved all code in a separate component 'ContentsDeleteModal'.
Added loader when loading references. If the call to @linkintegrity took a long time to load, it wasn't clear to the user that it was checking for broken references:
If only one item is selected to delete, it will display all the possibile broken references in a table, instead in a list. In the last column could be more than one reference: 
If more than one item is selected to delete, it will not display the possibile broken references, but only the number, because it  will be a very long list (It worked like that before too):
----
📚 Documentation preview 📚: …
=> Improve link integrity popup volto17

packages/volto/news/6527.bugfix, packages/volto/news/6527.feature, packages/volto/src/components/manage/Blocks/Container/EditBlockWrapper.jsx, packages/volto/src/components/manage/Blocks/Teaser/schema.js
This PR fixes the missing style information for inner container/grid blocks.
Adds a schemaEnhancer for disabling Teaser align handlers for inner container teaser elements.
=> Add missing styleWrapper style builder information in container/Grid

README.md, docs/source/contributing/developing-core.md, packages/components/news/6542.internal, packages/components/package.json, packages/volto/news/6542.documentation
- Update `@plone/components`'s URLs in its `package.json`.
- Update the monorepo structure file tree.
----
📚 Documentation preview 📚: https://volto--6542.org.readthedocs.build/
=> Add monorepo structure to the README

packages/volto/news/6493.bugfix, packages/volto/src/components/theme/App/App.jsx
-----
After fix body class only include the ?type= query_string in is-adding-contenttype class. All other query strings are ignored. If there's no type, no is-adding-contenttype class will be present.
Screenshots after fixing bug:
Closes #6493
=> Bugfix remove query string inclusion in body class generation logic

packages/volto/news/6554.bugfix, packages/volto/src/components/manage/Contents/Contents.jsx
Closes #5209
Closes #5931
Reset the selection when navigating, when changing page and when sorting items.
The idea is basically to reset the selection when you could have selected items that are now shown on the page.
I left one case where this is possible, but I am open for discussion about it: since the default page size is 50, a user might want to filter the contents using the text filter in the top right corner to find items in a quicker way, while still keeping the multiselection. What do you think?
=> Fixed folder contents issues with persistent selection

packages/volto/news/5856.bugfix, packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx
- [✅] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [✅] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [✅] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [✅] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [✅] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [✅] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my …
=> Depth search issue

apps/rr7/app/content.tsx, apps/rr7/app/root.tsx, apps/rr7/app/routes.ts, packages/client/news/6594.feature, packages/client/src/client.ts
So, I finally think that it's better go the whole way with the RR way for loaders, instead of perverting the default way, forcing people to have to learn this way.
The most we stick to the framework, the better.
=> Export the getContent bare fetcher

packages/coresandbox/src/index.ts, packages/registry/news/6600.feature, packages/registry/src/index.ts, packages/registry/src/registry.test.tsx, packages/types/news/6600.feature, packages/types/src/config/index.d.ts, packages/types/src/utils.d.ts
Added `registerRoute` API for the config. 
It allows to add a ReactRouter route to the configuration, that we can process and load later.
Quite simple, it only saves the configuration given a specific object.
=> Route registry

packages/volto/news/6576.bugfix, packages/volto/src/components/manage/Widgets/ObjectBrowserWidget.jsx
Instead of requiring to press enter to validate the value, it does it on blur too.
Also, moved to use the URL validator from the main Validators.
=> Improve the usability of the ObjectBrowser when inputting a manual value, checking it on blur, and adding a local validator

news/6615.feature, src/components/theme/AlternateHrefLangs/AlternateHrefLangs.jsx, src/components/theme/AlternateHrefLangs/AlternateHrefLangs.test.jsx, src/components/theme/View/View.jsx
-----
The same as #6603 for Volto 16.x
=> hreflangs for Volto 16

packages/volto/news/6634.bugfix, packages/volto/src/components/manage/Blocks/LeadImage/__snapshots__/LeadImageSidebar.test.jsx.snap, packages/volto/src/components/theme/Image/Image.jsx, packages/volto/src/components/theme/Image/__snapshots__/Image.test.jsx.snap, pnpm-lock.yaml
If we have for example image size defined in volto images controlpanel as:
and so we have scales ... 300x, 400x, 600px
and we have an image with original sizes 587x459, the generated image code and srcSet was: 
`<img src="/prova-news-immagine/test.png/@@images/image-587-0afb5e6bcbb1f1d0c94fc4256f78242f.png" **width="587"** **height="459"** class="responsive" srcset="/prova-news-immagine/test.png/@@images/image-16-a9e4943c736618d13a06af5bd63d5567.png 16w, /prova-news-immagine/test.png/@@images/image-32-22c97716e33946569fe9afa6d96bfd93.png 32w, /prova-news-immagine/test.png/@@images/image-64-ef5dc45106de9cd160b3a7da27f452b9.png 64w, /prova-news-immagine/test.png/@@images/image-128-f2750d92f764c72ea24226b78dff4d1a.png 128w, /prova-news-immagine/test.png/@@images/image-200-39b7501cf4c9616c05a3 …
=> Fix blurry images

packages/volto-slate/news/6529.bugfix, packages/volto-slate/src/blocks/Text/DefaultTextBlockEditor.jsx, packages/volto-slate/src/blocks/Text/extensions/breakList.js, packages/volto-slate/src/blocks/Text/extensions/insertBreak.js, packages/volto-slate/src/blocks/Text/keyboard/joinBlocks.js, packages/volto-slate/src/utils/volto-blocks.js, packages/volto/news/6529.bugfix, packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx, packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx, packages/volto/src/helpers/Blocks/Blocks.js, packages/volto/src/helpers/Blocks/Blocks.test.js, packages/volto/types/helpers/Blocks/Blocks.d.ts
-----
The function that calls `initialValue` is `applyBlockInitialValue`. So all functions that call `applyBlockInitialValue` must receive `intl`.
Closes #6529
=> Pass intl object to initialValue function

news/6637.bugfix, src/components/manage/Blocks/LeadImage/__snapshots__/LeadImageSidebar.test.jsx.snap, src/components/theme/Image/Image.jsx, src/components/theme/Image/__snapshots__/Image.test.jsx.snap
backport for Volto 17 of https://github.com/plone/volto/pull/6634
___________________
If we have for example image size defined in volto images controlpanel as:
and so we have scales ... 300x, 400x, 600px
and we have an image with original sizes 587x459, the generated image code and srcSet was: 
`<img src="/prova-news-immagine/test.png/@@images/image-587-0afb5e6bcbb1f1d0c94fc4256f78242f.png" **width="587"** **height="459"** class="responsive" srcset="/prova-news-immagine/test.png/@@images/image-16-a9e4943c736618d13a06af5bd63d5567.png 16w, /prova-news-immagine/test.png/@@images/image-32-22c97716e33946569fe9afa6d96bfd93.png 32w, /prova-news-immagine/test.png/@@images/image-64-ef5dc45106de9cd160b3a7da27f452b9.png 64w, /prova-news-immagine/test.png/@@images/image-128-f2750d92f764c72ea24226b78d …
=> Fix blurry images (volto17)

packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/news/6476.bugfix
This turns two Dutch terms introduced in PR #6476 back to their English version: teaser and grid. With @fredvd and the client we agreed that in this case the English terms are better, less surprising. So this reverts a small part of that PR.
@fredvd I left one case of 'voorproefje' untouched, as it seems a fine translation of 'preview':
```
msgid "Results preview"
msgstr "Resultaten voorproefje"
```
=> Update Dutch translations.

.github/ISSUE_TEMPLATE/1_bug_report.md
This does not need a news item because it's a follow up to #6683. I realized it was not correct after #6736 was published.
=> Fix the '30 needs: triage' label for bug reports template

packages/volto/news/6602.feature, packages/volto/src/components/theme/AlternateHrefLangs/AlternateHrefLangs.jsx, packages/volto/src/components/theme/AlternateHrefLangs/AlternateHrefLangs.test.jsx
> [!CAUTION]
-----
-----
Add the so called "self link" in the alternate language links as per [#6602](https://github.com/plone/volto/issues/6602#issuecomment-2636419544)
Closes #
=> Alternate hreflang v2

packages/volto/news/6561.bugfix, packages/volto/src/express-middleware/sitemap.js, packages/volto/src/helpers/Sitemap/Sitemap.js
We generate sitemap-index.xml which is also put correctly into robots.txt. However we still provide the old sitemap.xml.gz.
But, while this serves no purpose in addition to the index, it can cause problems if Google somehow parses it (for example it's submitted to the Google Search console). For this reason, we  stop providing sitemap.xml.gz.
-----
Closes #6561
=> Stop generating sitemap.xml.gz (#6561)

packages/volto/cypress/support/commands.js, packages/volto/news/6755.internal
Waits for the slate editor to be visible before attempting to insert text.
This fixes the error:
```
1) Block Indexing Tests
Index Text Block:
AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Noam Avram Chomsky' within the element: <div> but never did.
at Context.eval (webpack://@plone/volto/./cypress/tests/core/blocks/blocks-indexing.js:19:51)
```
See: https://github.com/plone/volto/actions/runs/13332572803/job/37240061119?pr=6754#step:4:445
> [!CAUTION]
----- …
=> Fixes intermittent error in cypress "Index Text Block" test

packages/volto/news/6751.bugfix, packages/volto/news/6751.bugifx, packages/volto/src/components/manage/BlockChooser/BlockChooserButton.jsx
problem: with 
config.experimental.addBlockButton.enabled=true prop
the placement of block chooser was wrong sometimes and search bar or some portion of block ckooser was not visible and usable (expecially when you have a lot of blocks in a block chooser section). See the problem here:
https://github.com/user-attachments/assets/fb37ec0e-9027-4103-a210-ea6522d73fa9
With this fix, block chooser will placed bottom to the block, without mentioned problems:
https://github.com/user-attachments/assets/3337bdee-5ad1-44ab-81e2-57bc730c2cf2
=> fix: block chooser position in experimental.addBlockButton

docs/source/_inc/_install-browser-reqs-volto.md, docs/source/contributing/version-policy.md, docs/source/user-manual/blocks.md, packages/volto/news/6760.documentation
- `link.svg`
- `_inc/_install-browser-reqs-volto.md`
----
📚 Documentation preview 📚: 
- https://volto--6760.org.readthedocs.build/contributing/version-policy.html#supported-web-browsers
- https://volto--6760.org.readthedocs.build/user-manual/blocks.html#copy-headings-as-anchor-links
=> Fix broken references

packages/volto/news/6788.bugfix, packages/volto/src/components/theme/Image/Image.jsx, packages/volto/src/components/theme/Image/Image.test.jsx, packages/volto/src/components/theme/Image/__snapshots__/Image.test.jsx.snap
This was happening when the c`lassName` prop was not passed and the `responsive` prop was `false`.
> [!CAUTION]
-----
-----
Closes #6788
=> Does not show empty class attribute when rendering img tag with Image component

packages/volto/news/6802.bugfix, packages/volto/src/components/manage/Widgets/CheckboxWidget.jsx, packages/volto/src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap, packages/volto/src/config/index.js
Screen readers are not correctly reading the checkbox because the label, although present, is not properly referenced.
While it suggests an htmlFor attribute, the necessary association is missing, causing it to be ignored.
To resolve this issue, an id has been added to the checkbox, ensuring proper identification and correct label functionality for assistive technologies.
V17 PR: https://github.com/plone/volto/pull/6771/
=> Added id to Checkbox component to proper a11y identification

news/6771.bugfix, src/components/manage/Blocks/LeadImage/__snapshots__/LeadImageSidebar.test.jsx.snap, src/components/manage/Widgets/CheckboxWidget.jsx, src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap
Screen readers are not correctly reading the checkbox because the label, although present, is not properly referenced. 
While it suggests an htmlFor attribute, the necessary association is missing, causing it to be ignored.
To resolve this issue, an id has been added to the checkbox, ensuring proper identification and correct label functionality for assistive technologies.
v18 PR: https://github.com/plone/volto/pull/6802
=> Add id to Checkbox component to proper a11y identification

README.md, docs/source/configuration/backend.md, docs/source/contributing/developing-core.md, docs/source/contributing/index.md, docs/source/development/folder-structure.md, packages/volto/README.md, packages/volto/news/6812.documentation
This PR removes a cookiecutter-plone-starter link and fixes other MyST reference warnings. Merge before https://github.com/plone/documentation/pull/1891.
----
📚 Documentation preview 📚: https://volto--6812.org.readthedocs.build/
=> Fix warnings in Sphinx 8

packages/volto-testing/news/6813.bugfix, packages/volto-testing/package.json, pnpm-lock.yaml
I've discovered that `@plone/volto-testing` is leaking React 19 in its resolutions.
=> Leaking React19 in `volto-testing` package

docs/source/contributing/developing-core.md, docs/source/development/creating-project.md, docs/source/development/overview.md, docs/source/index.md, packages/volto/news/6820.documentation
This was an oversight and is urgent to fix. I'll merge it without a review, but we should have caught this with the release of Plone 6.1, as we did elsewhere in the docs.
----
📚 Documentation preview 📚: https://volto--6820.org.readthedocs.build/
=> Use Cookieplone for installation and project generation

docs/source/configuration/validation.md, packages/volto/locales/ca/LC_MESSAGES/volto.po, packages/volto/locales/de/LC_MESSAGES/volto.po, packages/volto/locales/en/LC_MESSAGES/volto.po, packages/volto/locales/es/LC_MESSAGES/volto.po, packages/volto/locales/eu/LC_MESSAGES/volto.po, packages/volto/locales/fi/LC_MESSAGES/volto.po, packages/volto/locales/fr/LC_MESSAGES/volto.po, packages/volto/locales/hi/LC_MESSAGES/volto.po, packages/volto/locales/it/LC_MESSAGES/volto.po, packages/volto/locales/ja/LC_MESSAGES/volto.po, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/locales/pt/LC_MESSAGES/volto.po, packages/volto/locales/pt_BR/LC_MESSAGES/volto.po, packages/volto/locales/ro/LC_MESSAGES/volto.po, packages/volto/locales/volto.pot, packages/volto/locales/zh_CN/LC_MESSAGES/volto.po, packages/volto/news/6811.feature, packages/volto/src/components/manage/Widgets/SelectWidget.jsx, packages/volto/src/config/validation.ts, packages/volto/src/helpers/FormValidation/validators.ts, packages/volto/src/helpers/MessageLabels/MessageLabels.js
Fixes the use case that you can save a new default language without adding it to the list of available languages.
Now it complains, on blur and on save.
Probably, it would need a server side validator too.
Depends on https://github.com/plone/plone.i18n/pull/73 but not requires it.
Also fixes a section of the docs that was incorrect.
----
📚 Documentation preview 📚: https://volto--6811.org.readthedocs.build/
=> Add validator for `default_language` in language control panel

packages/volto/src/helpers/FormValidation/validators.ts
> [!CAUTION]
-----
-----
Closes #
=> Fix typescript return value for emailValidator

docs/source/configuration/environmentvariables.md, docs/source/configuration/settings-reference.md, packages/volto/news/6830.feature, packages/volto/src/config/index.js, packages/volto/src/helpers/Html/Html.jsx, packages/volto/src/start-client.jsx
This PR allows you to setup the default language (`config.settings.defaultLanguage`) from a RUNTIME variable `SITE_DEFAULT_LANGUAGE`.
This is a non-breaking change workaround for 18, since we decided that #6807 will be targeted for 19. 
The idea is to incorporate this also in #6807 since it might be valuable to have both ways of doing it.
=> Allow setting the default language via a RUNTIME environment variable

docs/source/blocks/block-style-wrapper.md, packages/volto/news/6832.bugfix, packages/volto/src/components/manage/Blocks/Block/StyleWrapper.jsx, packages/volto/src/components/manage/Blocks/Container/EditBlockWrapper.jsx, packages/volto/src/components/theme/View/RenderBlocks.jsx, packages/volto/src/helpers/Blocks/Blocks.js, packages/volto/src/helpers/Blocks/Blocks.test.js
There were some edge cases in blocks contained in container blocks (blocks in block) when the style applied was incorrect.
This was mainly because at the moment of applying the styles, there was no way of telling if a block is a contained block or not.
This PR fixes this, passing down the container block data and accounting for this fact along the way.
=> Stylewrapper `buildStyleObjectFromData` fixes accounting for container blocks

packages/volto/news/6853.bugfix, packages/volto/razzle.config.js
This is the process where it copies over the `public` folder for add-ons into the build resultant folder.
It happens that if something go wrong in the build, this error swallows any previous error with the build, which makes you look into the wrong direction. Now, it will be more resilient and show the real error happening.
=> Check first if the destination (build public directory) exists before trying to create it in `AfterBuildPlugin`

packages/volto/news/6852.bugfix, packages/volto/src/components/theme/ContactForm/ContactForm.jsx
Updates the icon in the toolbar for the back navigation in the contact form to be in sync with the other back navigation icons in the controlpanel.
=> fix toolbar icon for back navigation in contact form

.github/stale-items.yml
Adds an action for checking stale issues and PRs and marking them as stale.
As discussed in the last Volto team meeting, there is not automatic closing of Issues/PRs right now, let's see how this works for us.
=> Added stale checker

Makefile, apps/seven/news/6913.internal, apps/seven/package.json, apps/seven/registry-publicui.config.ts, apps/seven/registry.config.ts
This sets the full application with CMSUI as the default one, while the extra option that has just the publicui is the one people have to opt-in. Even if the latter is the most complete at this time, I feel this will make it easier to jump in into working towards Seven.
=> [Seven] Change default script

docs/source/_inc/_branch-policy.md, docs/source/_inc/_install-nodejs.md, docs/source/_inc/_install-uv.md, docs/source/contributing/developing-core.md, docs/source/upgrade-guide/index.md, packages/volto/news/6917.documentation
- Also fix cross-references
This PR must be merged before https://github.com/plone/documentation/pull/1929.
----
📚 Documentation preview 📚:
- https://volto--6917.org.readthedocs.build/6917/contributing/index.html#branch-policy
- https://volto--6917.org.readthedocs.build/6917/contributing/version-policy.html#branch-policy
- https://volto--6917.org.readthedocs.build/6917/upgrade-guide/index.html#upgrading-to-volto-18-x-x
- https://volto--6917.org.readthedocs.build/6917/contributing/developing-core.html#node-js
=> Move includes from `plone/documentation` to `plone/volto`

docs/source/_inc/_hardware-requirements.md, packages/volto/news/6918.documentation
I forgot this one. I'll merge it. No review needed.
----
📚 Documentation preview 📚: https://volto--6918.org.readthedocs.build/
=> Move _hardware-requirements.md include from documentation to volto

packages/client/news/6901.bugfix, packages/client/src/api.ts, pnpm-lock.yaml
This also catches errors like ECONNREFUSED, while the current implementation breaks because `error.response.data` is not defined.
=> Fixed handling of errors that are not coming from the backend

docs/source/conf.py, packages/volto/news/6933.documentation
----
📚 Documentation preview 📚: https://volto--6933.org.readthedocs.build/
=> Remove duplicate configuration item `html_title`

.github/workflows/docs-rtd-pr-preview-volto.yml, .readthedocs.yaml, packages/volto/news/6950.documentation
This time with the correct base to see if it triggers RTD PR preview builds.
https://volto--6950.org.readthedocs.build/6950/
Well, I goofed. PR previews build. It's just a matter of opening up a PR against `seven` with changes to docs, and it should add the link of the preview to the description.
=> Enable pull request previews on Read the Docs

packages/volto-slate/news/6952.bugfix, packages/volto-slate/src/utils/volto-blocks.js, packages/volto/news/6952.bugfix, packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx, packages/volto/src/helpers/Blocks/Blocks.js
> [!CAUTION]
-----
-----
Closes #6952
=> Fix: Consistent initialValue call on block insertion

packages/volto-slate/news/6952.bugfix, packages/volto-slate/src/utils/volto-blocks.js, packages/volto/news/6952.bugfix, packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx, packages/volto/src/helpers/Blocks/Blocks.js
> [!CAUTION]
-----
-----
Closes #
=> Backport: Fix consistent initialValue call on block insert (#6958)

packages/volto/cypress/support/commands.js, packages/volto/news/6957.internal
Locally and I had the error:
```
As editor I can add a page with a text block:
AssertionError: Timed out retrying after 4000ms: Expected to find content: 'This is the text' within the element: <div> but never did.
```
This error occurred on the line:
https://github.com/plone/volto/blob/81d0369e1628b3072f9e47d14831a2618d2633b6/packages/volto/cypress/tests/core/content/content.js#L53
This PR's change waits until text is entered in `getSlateEditorAndType` and `getSlateEditorSelectorAndType` before testing continues.
There are situations where cypress commands are entered and we cannot verify the text. For example:
https://github.com/plone/volto/blob/c2c4f0f2db89eeb9ea8c1846cdafe3258581842c/packages/volto/cypress/tests/core/volto-slate/06-block-slate-format-link.js#L64-L66
> [!CAUTION]
The …
=> Makes the cypress getSlateEditorAndType and getSlateEditorSelectorAndType commands more robust

packages/volto/cypress/tests/core/blocks/blocks-indexing.js, packages/volto/news/6965.internal
Wait for the search field to be enabled before trying to enter something.
Fix the error:
```
1) Block Indexing Tests
Index Text Block:
CypressError: `cy.type()` failed because it targeted a disabled element.
```
See: https://github.com/plone/volto/actions/runs/14365190416/job/40276279370#step:4:457
> [!CAUTION]
-----
-----
If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue …
=> Fixes Cypress "Index Text Block" test

packages/volto/locales/ca/LC_MESSAGES/volto.po, packages/volto/locales/de/LC_MESSAGES/volto.po, packages/volto/locales/en/LC_MESSAGES/volto.po, packages/volto/locales/es/LC_MESSAGES/volto.po, packages/volto/locales/eu/LC_MESSAGES/volto.po, packages/volto/locales/fi/LC_MESSAGES/volto.po, packages/volto/locales/fr/LC_MESSAGES/volto.po, packages/volto/locales/hi/LC_MESSAGES/volto.po, packages/volto/locales/it/LC_MESSAGES/volto.po, packages/volto/locales/ja/LC_MESSAGES/volto.po, packages/volto/locales/nl/LC_MESSAGES/volto.po, packages/volto/locales/pt/LC_MESSAGES/volto.po, packages/volto/locales/pt_BR/LC_MESSAGES/volto.po, packages/volto/locales/ro/LC_MESSAGES/volto.po, packages/volto/locales/ru/LC_MESSAGES/volto.po, packages/volto/locales/volto.pot, packages/volto/locales/zh_CN/LC_MESSAGES/volto.po, packages/volto/news/6964.feature, packages/volto/src/components/manage/Contents/ContentsDeleteModal.jsx
=> Fix translations default of ContentsDeleteModal: 'linkintegrity: delete' -> 'delete' if no link to break. 

packages/volto/.eslintrc.core.js, packages/volto/news/6974.internal, packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx
The `Image` component from `@plone/volto/components/theme/Image/Image` must be used.
See: https://github.com/plone/volto/pull/6754
> [!CAUTION]
-----
-----
Closes #
=> Add eslint rule to avoid importing Image from semantic-ui-react

packages/volto/news/6982.internal, packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx
> [!CAUTION]
-----
-----
Closes #
=> Use Image from @plone/volto/components/theme/Image/Image instead of semantic-ui-react in ContentsUploadModal

docs/source/configuration/expanders.md, docs/source/configuration/settings-reference.md, packages/volto/news/7012.feature, packages/volto/src/middleware/Api.test.js, packages/volto/src/middleware/api.js
----
📚 Documentation preview 📚: https://volto--7012.org.readthedocs.build/
=> Added current evaluated `querystring` as a parameter in expander `querystring` key when it is a function

docs/source/contributing/bundle-size-optimization.md, packages/volto/news/7024.documentation
> [!CAUTION]
-----
-----
Closes #7024 
----
📚 Documentation preview 📚: https://volto--7025.org.readthedocs.build/
=> updated docs for vitest in bundle-size-optimiazation

docs/source/contributing/documentation.md
- Minor grammar fix
No change log needed. Trivial maintenance.
----
📚 Documentation preview 📚: https://volto--7026.org.readthedocs.build/
=> Fix title to "Microsoft Writing Style Guide"

packages/volto/news/7045.bugfix, packages/volto/src/components/manage/Widgets/ImageWidget.jsx
This merge request addresses two key issues in the Image Upload Widget: the `uploading` state remaining stuck when an oversized image is uploaded, and the `dragging` state persisting after an image is deleted or a drag event ends. Below is a detailed explanation of the changes made to resolve these problems.
---
**Problem:**
When a user uploads an image that exceeds the allowed size limit, the `uploading` state remains `true`, causing the loading CSS (`Dimmer` active) to stay visible. This prevents the user from interacting with the widget further.
**Solution:**
The `handleUpload` function was updated to explicitly reset the `uploading` state to `false` when the size validation fails. This ensures that the loading state is cleared, and the user can retry the upload.
**Changes Made:**
- …
=> fix ImageWidget state handling in upload and drag-and-drop functional.

.github/workflows/docs-rtd-pr-preview-volto.yml, packages/volto/news/7066.documentation
Fix the path in which to detect changes to documentation files for the `seven` branch.
----
📚 Documentation preview 📚: https://volto--7066.org.readthedocs.build/
----
📚 Documentation preview 📚: https://plone-registry--7066.org.readthedocs.build/
=> Fix rtd preview builds for Seven

packages/volto/news/7083.feature, packages/volto/src/components/manage/Widgets/SelectWidget.jsx
This PR adds the `isClearable` prop to the `SelectWidget` component, allowing configuration of whether the select input can be cleared by the user. By default, the select remains clearable for backward compatibility, but now it can be set to `false` when needed. This makes the widget more flexible and suitable for different form requirements.
Closes #7083
=> Add isClearable prop to SelectWidget component

packages/volto/news/7048.feature, packages/volto/src/components/manage/Add/Add.jsx
This PR updates the `Add` page component to use the schema title (`this.props.schema.title`) in the `Helmet` title instead of the technical identifier (`props.type`). This change ensures that the browser title is more user-friendly and descriptive, improving the overall user experience.
- Fallback to `props.type` remains in place to ensure compatibility.
- Aligns with other parts of the system that already use the schema title.  
- Ability to translate the schema title.
1. Navigate to the page for creating new content (e.g., `Page`).  
2. Verify that the browser title now displays the schema title (e.g., "Add Page") instead of the technical identifier.  
3. Confirm that the fallback to `props.type` works if `schema.title` is unavailable.
Retains the current behavior as a fallback.
Closes …
=> Use schema title in Helmet for `Add` page component.

packages/cmsui/components/Form/Field.tsx, packages/cmsui/components/TextField/TextField.stories.tsx, packages/cmsui/config/widgets.ts, packages/cmsui/news/7141.feature, packages/registry/news/7141.feature, packages/registry/src/index.ts, packages/registry/src/registry.test.tsx, packages/types/news/7141.bugfix, packages/types/src/config/Widgets.d.ts
This PR adds getWidget and registerWidget methods in registry, and updates Field component and widgets config in cmsui.
Widget registration is now done by calling registerWidget method
```
config.registerWidget({ key: 'default', definition: TextField });
```
You can get a widget from config by using getWidget
```
(method) Config.getWidget(key: string): React.ComponentType<any> | undefined
```
Both methods provide intellisense via Typescript, docstrings are
```
(method) Config.getWidget(key: string): React.ComponentType<any> | undefined
```
```
@param key — A key from the WidgetsConfig interface.
(method) Config.registerWidget<"default">(options: {
key: "default";
definition: ComponentType<any>;
}): void
Registers a widget configuration into the registry.
@template K — A key from the …
```
=> feat: add getWidget and registerWidget methods in registry

packages/blocks/news/7260.internal, packages/blocks/package.json, packages/client/news/7260.internal, packages/client/package.json, packages/components/news/7260.internal, packages/components/package.json, packages/slots/news/7260.internal, packages/slots/package.json, packages/volto-slate/news/7260.internal, packages/volto-slate/package.json, packages/volto/news/7260.internal, packages/volto/package.json, packages/volto/src/components/manage/Widgets/RegistryImageWidget.test.jsx, pnpm-lock.yaml
> [!CAUTION]
-----
This also synchronizes the version of `@testing-library/react` across all packages in the repository.
I had an issue in an addon test where version `9.5.0` was used, but version 14 should have been used.
=> Update @testing-library/react to 14.3.1

packages/volto/news/7267.bugfix, packages/volto/src/components/manage/Form/InlineForm.jsx
This PR fixes an issue where the `InlineForm` component would pass the `error` prop as an object instead of an array, causing prop type errors and warnings in widgets that use `FormFieldWrapper`, such as Checkbox.
**How to test:**
1. Add a Teaser block to the page.
2. Check the browser console and confirm that prop type errors related to the error prop are no longer present.
Closes #7267
=> Fix InlineForm to always pass error as array to prevent prop type errors

packages/volto/cypress/support/commands.js, packages/volto/news/7290.internal
The text was entered into the editor, but a re-render caused the editor reference to become stale when verifying whether the text was present. We now re-fetch the editor to ensure we always have an up-to-date reference.
This fixes the error:
```javascript
1) Block Tests: Basic text format
Heading (h2):
AssertionError: Timed out retrying after 4430ms: expected '<div>' to contain 'Colorless green ideas sleep furiously.'
at Context.eval (webpack://@plone/volto/./cypress/support/commands.js:839:14)
```
See: https://github.com/plone/volto/actions/runs/17314600477/job/49155144015#step:4:402
=> Fixed a random failure in Cypress tests when using `getSlateEditorAndType` or `getSlateEditorSelectorAndType`

packages/volto/news/7292.internal, packages/volto/src/components/manage/Widgets/RegistryImageWidget.test.jsx
Wait for a more consistent state, where the image has the correct src
This fixes the error:
```javascript
Error: Error: Snapshot `RegistryImageWidget > renders a file widget component with value 1` mismatched
- Expected
+ Received
@@ -24,36 +24,10 @@
</div>
<div
class="eight wide column"
>
<div
-             class="file-widget-dropzone"
-             tabindex="0"
-           >
-             <img
-               alt=""
-               class="image-preview small ui image"
-               fetchpriority="high"
-               id="field-my-field-image"
-               src="http://localhost:3000/@@site-logo/logo.cab945d8.svg"
-             />
-             <label
-               class="label-file-widget-input"
-             >
-               Replace existing file
-             </label>
- …
```
=> Fix random failure in 'renders a file widget component with value' test of RegistryImageWidget

packages/volto/cypress/tests/core/blocks/listing/blocks-listing.js, packages/volto/news/7293.internal
Wait until the `querySearch` request finishes before clicking the pagination item. Also wait for the "Loading" to disappear from the screen.
This fixes:
```javascript
1) Listing Block Tests
Navigate to different pages on two different listings:
CypressError: Timed out retrying after 4050ms: `cy.click()` failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:
> cy.get(@paginationItem)
```
See: https://github.com/plone/volto/actions/runs/17345525928/job/49246764836#step:4:262
=> Fixes random error in Listing Block tests 2

packages/volto/news/7287.internal, packages/volto/src/middleware/storeProtectLoadUtils.test.js
=> Fix test storeProtectLoadUtils.test.js > storeProtectLoadUtils > loadProtector store > pass when not counting

packages/cmsui/.storybook/preview.ts, packages/layout/.storybook/preview.ts, packages/layout/package.json, pnpm-lock.yaml
Storybook build is broken for cmsui and layout.
These pages are outdated:
- https://plone-layout.readthedocs.io
- https://plone-cmsui.readthedocs.io
----
📚 Documentation preview 📚: https://volto--7328.org.readthedocs.build/
=> Seven storybook fix

packages/cmsui/config/widgets.ts, packages/cmsui/news/7334.feature, packages/registry/news/7334.bugfix, packages/registry/src/index.ts, packages/registry/src/registry.test.tsx, packages/types/news/7334.internal, packages/types/src/config/Widgets.d.ts
> [!CAUTION]
-----
@sneridagh here is the pr for what we debugged this morning, and some very tentative docs
- Added validation in `registerWidget()` to prevent `key: 'default'`
- Throws error: `"Use registerDefaultWidget to set the default widget"` when trying to add a default widget with registerWidget method instead of registerDefaultWidget
- Added test for error throwing behavior and improved test reliability
- Fixed test using wrong API (`registerWidget({ key: 'default' })` → …
=> Widget registry fixes

packages/volto/.eslintrc, packages/volto/.eslintrc.core.js, packages/volto/news/7401.bugfix, packages/volto/src/components/theme/Image/Image.jsx
Since it was a breaking change.
I added it to `.eslintrc.core.js` so it's still enforced in core.
=> Revert #7389 ESlint rule definition
